### ISSUE TITLE
Datadog agent Vector integration config

### ISSUE THREAD

**Issue by NasAmin** [DataDog/helm-charts#1008]
**Describe what happened:**
Enable vector integration. 
I have the following config:

```yaml
  agents:
    useConfigMap: true
    customAgentConfig:
      kubelet_tls_verify: false
      vector:
        metrics:
          enabled: true
          url: "http://vector:8001"
        logs:
          enabled: false
        traces:
          enabled : false
```

Datadog agent doesn't send any metrics to Vector. What is the right config for this? 
Also when sending data to Vector, is there a way to turn off providing an API key as the agent should not be directly talking to Datadog.

**Describe what you expected:**
Expected metrics to flow to vector.
Datadog logs are full of API key invalid errors because I provided a dummy key.
If I don't provide a key then it still fails.

Expected behaviour is:
- No need to provide an API key when forwarding to Vector
- Providing an API key is optional and should not be communicating to Datadog directly even if a valid key is provided.

**Steps to reproduce the issue:**
Add the config mentioned above.
Enable `kubestatemetriccore`

```yaml
    kubeStateMetricsEnabled: false
    kubeStateMetricsCore:
      enabled: true
      rbac:
        create: true
```

Deploy the DD agent and Vector to a k8s cluster.

**Vector config:**

```yaml
  sources:
    dd-agent-k8s:
      type: datadog_agent
      address: 0.0.0.0:8001
      store_api_key: false
      multiple_outputs: true
```

**Additional environment details (Operating System, Cloud provider, etc):**
