### ISSUE TITLE
Datadog breaks gke-connect

### ISSUE THREAD

**Issue by CmdrSharp** [DataDog/helm-charts#1010]
**Describe what happened:**
Possibly related to #986.

We use Google Anthos, and have been running Datadog successfully for some time. Yesterday, we performed a cluster update (scaling up nodes), which Anthos does by replacing existing nodes. This meant that all workloads were evicted and re-scheduled on a fresh node.

This is when we started seeing an issue. The `gke-connect` deployment can no longer spin up because Datadog's volume injection breaks the PSP.

```
  Warning  FailedCreate     16m                replicaset-controller  Error creating: pods "gke-connect-agent-20221020-05-00-645f57c96d-rrj6x" is forbidden: violates PodSecurity "restricted:latest": restricted volume types (volume "datadog" uses restricted volume type "hostPath")
```

We didn't notice this initially because Datadog gets deployed _after_ the Anthos workloads during initial cluster bootstrapping - so this only becomes an issue on _later_ changes to the clusters.

A potential workaround for us would be to create another `MutatingWebhookConfiguration` that adds the `admission.datadoghq.com/enabled: false` to the workloads; but I feel like this should be handled within Datadog.

**Steps to reproduce the issue:**
1. Install Google Anthos
2. Install Datadog
3. Replace Google Anthos nodes

**Additional environment details (Operating System, Cloud provider, etc):**

v1.25.5-gke.100
Google Anthos (on-premises)

**Comment by CmdrSharp** [comment]
For other readers, this is our temporary workaround using Kyverno.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-datadog-for-gke-connect
  annotations:
    policies.kyverno.io/subject: Deployment,ReplicaSet,Pod,Label
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: disable-datadog-for-gke-connect
      match:
        any:
        - resources:
            kinds:
            - Deployment
            names:
            - "gke-connect-agent-*"
            namespaces:
            - gke-connect
      mutate:
        targets:
          - apiVersion: apps/v1
            kind: Deployment
            namespace: gke-connect
        patchStrategicMerge:
          spec:
            template:
              metadata:
                labels:
                  +(admission.datadoghq.com/enabled): "false"
```
