### ISSUE TITLE
setting agents.useConfigMap causes system-probe container to fail

### ISSUE THREAD

**Issue by pdeva** [DataDog/helm-charts#1024]
**Describe what happened:**
setting the `useConfigMap` property with some additional endpoints causes system-probe to fail.

the only workaround is to comment out the `datadog.networkMonitoring.enabled` and `datadog.serviceMonitoring.enabled` items in the yaml below, thus turning off system-probe completely, to allow the agent pods to startup.

**Describe what you expected:**
the additional endpoint are related to traces so shouldnt be affecting system-probe at all.

**Steps to reproduce the issue:**
set the following properties of helm chart:
```yaml
          - name: "agents.useConfigMap"
            value: "true"
          - name: "agents.customAgentConfig.additional_endpoints"
            value: |-
              "https://blah.com":
              - apikeytest123
          - name: "datadog.networkMonitoring.enabled"
            value: "true"
          - name: "datadog.serviceMonitoring.enabled"
            value: "true"
```

**Additional environment details (Operating System, Cloud provider, etc):**

EKS 1.26 running on BottlerocketOS arm64
chart 3.27.0
