### ISSUE TITLE
configured images from gcr.io/datadoghq/* are blocked in china

### ISSUE THREAD

**Issue by cforce** [DataDog/helm-charts#105]
Which images to be used instead?

```
clusterAgent:
  image:
    repository: ???/datadog/cluster-agent

clusterChecksRunner:
  image:
    repository: ???//datadog/agent

agents:
  image:
    repository: ???//datadog/agent
```

**Comment by vboulineau** [comment]
Hi @cforce ,

The images are still available from DockerHub at `datadog/agent` if that's an option for you.

**Comment by clamoriniere** [comment]
Hi @cforce 

We advise to use the `gcr.io/datadoghq/*` images to avoid any issue with the docker hub rate limit, but if you can't have access to gcr.io, you can still use the docker hub images

```yaml
clusterAgent:
  image:
    repository: datadog/cluster-agent

clusterChecksRunner:
  image:
    repository: datadog/agent

agents:
  image:
    repository: datadog/agent
```
