### ISSUE TITLE
APM functionality on GKE Autopilot doesn't work

### ISSUE THREAD

**Issue by huib-coalesce** [DataDog/helm-charts#1052]
**Describe what happened:**
APM functionality on a GKE Cluster in Autopilot mode doesn't work.
Instrumented pods fail to be created, so the application doesn't deploy at all.

![image](https://github.com/DataDog/helm-charts/assets/127156493/23e90870-37ab-42f1-8813-fa3a754b4c92)

![image](https://github.com/DataDog/helm-charts/assets/127156493/cea62c38-0c20-4bae-b747-ed3ec377032c)

This happens for both NodeJS and Python apps (I haven't tried any other ones).

Every now and then however when redeploying the Datadog agent a pod will start successfully, but I wonder if that's because of the order of deployment (i.e. Datadog admission controller timing).

And if I try the same on a GKE cluster in Standard mode then it seems to all work fine.

**Describe what you expected:**
Applications with the tracer injected should successfully deploy.

**Steps to reproduce the issue:**

Create a GKE cluster in Autopilot mode.

Create kube secrets in the default namespace
```
kubectl create secret generic datadog-api-key --from-literal api-key="<your api key>"
kubectl create secret generic datadog-app-key --from-literal app-key="<your app key>"
kubectl create secret generic datadog-cluster-agent-token --from-literal token="<random>"
```

Deploy the helm chart for the agent
```
helm install datadog-agent datadog/datadog -f datadog-agent-values.yaml --version 3.29.3
```

with `datadog-agent-values.yaml`
```
datadog:
  apiKeyExistingSecret: datadog-api-key
  appKeyExistingSecret: datadog-app-key

  clusterName: test-k8s

  kubeStateMetricsCore:
    enabled: true
  kubeStateMetricsEnabled: false

  logs:
    enabled: true
    containerCollectAll: false

  apm:
    portEnabled: true
    port: 8126
    socketEnabled: false

  leaderElection: true
  collectEvents: true

  prometheusScrape:
    enabled: false

  processAgent:
    enabled: true
    processCollection: true

  dogstatsd:
    useHostPort: true
    port: 8125
    useSocketVolume: false

clusterAgent:
  enabled: true
  tokenExistingSecret: datadog-cluster-agent-token
  metricsProvider:
    enabled: false
  rbac:
    create: true
  admissionController:
    configMode: service

agents:
  enabled: true
  priorityClassCreate: true
  tolerations:
    - effect: NoSchedule
      key: kubernetes.io/arch
      operator: Equal
      value: amd64
  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

    processAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

providers:
  gke:
    autopilot: true
```

That should deploy the agent successfully (unless you run into https://github.com/DataDog/helm-charts/issues/1033 of course).

In a Node app define:
```
const tracer = require("dd-trace").init({
  logInjection: true,
  profiling: true,
  env: "dev",
  service: "nodejs",
  version: "latest",
});
export default tracer;
```

Deploy the Node app:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "nodejs"
    tags.datadoghq.com/version: "latest"
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "nodejs"
        tags.datadoghq.com/version: "latest"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/js-lib.version: "v3.21.0"
    spec:
      containers:
      - env:
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_STARTUP_LOGS
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_AGENT_HOST
          value: "datadog-agent.default.svc.cluster.local"
        - name: DD_ENV
          value: "dev"
        - name: DD_SERVICE
          value: "nodejs"
        - name: DD_VERSION
          value: "latest"
        name: nodejs
        image: my-repo/nodejs:latest
```

Deploy a Python app:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "python"
    tags.datadoghq.com/version: "latest"
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      component: python
  template:
    metadata:
      labels:
        component: python
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "python"
        tags.datadoghq.com/version: "latest"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: "1.13.3"
    spec:
      containers:
      - env:
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_STARTUP_LOGS
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_AGENT_HOST
          value: "datadog-agent.default.svc.cluster.local"
        - name: DD_ENV
          value: "dev"
        - name: DD_SERVICE
          value: "python"
        - name: DD_VERSION
          value: "latest"
        image: my-repo/python:latest
        name: python
      restartPolicy: Always
```

If I try the same on a GKE cluster in Standard mode then it all works fine.

**Additional environment details (Operating System, Cloud provider, etc):**
Cluster:
Release channel `Regular channel`
Version `1.24.11-gke.1000`
in `us-central1`
Autopilot mode
