### ISSUE TITLE
[AWS] How to force cluster agent to use imdsv2?

### ISSUE THREAD

**Issue by irl-segfault** [DataDog/helm-charts#1073]
For the datadog agent, there is a field in the `values.yaml` file called `agents.customAgentConfig.ec2_prefer_imdsv2` you can set to `true` to use the IMDSv2 API.  For the cluster agent, is there a similar option?  I'm still seeing IMDSv2 usage coming from the cluster agent.  Thanks!

**Comment by sergei-ivanov** [comment]
It took me a lot of time to figure this out, and here it is:

```yaml
datadog:
  env:
  - name: DD_EC2_PREFER_IMDSV2
    value: "true"

clusterAgent:
  rbac:
    serviceAccountAnnotations:
      # Optional for describing EC2 instances
      "eks.amazonaws.com/role-arn": "arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxxxxx"
  env:
    - name: DD_EC2_PREFER_IMDSV2
      value: "true"
```

Passing the environment variable removes the need to pass `customAgentConfig`, unless you also need a custom config for something else.

Note that the two agents are configured separately.

Setting the environment variable has forced IMDSv2, and the cluster agent happily resolved it. But it still complained that it could not retrieve EC2 instance tags using the attached IAM role. For completeness, you will either need to enable instance metadata option "InstanceMetadataTags=enabled", or you will need to set up an IRSA for service account `datadog-agent-cluster-agent` that will have the following permissions:

```json
        {
            "Action": [
                "ec2:DescribeTags",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceStatus"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "InspectEC2"
        }
```
