### ISSUE TITLE
Datadog agent config listeners and config_providers (docker vs containerd)

### ISSUE THREAD

**Issue by dudo** [DataDog/helm-charts#1074]
I'm looking at the [default values for the datadog helm chart](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/datadog-yaml-configmap.yaml#L22-L26).

We do have some custom bits in there because we're redacting some logs/tags.

So, `{{- if .Values.agents.customAgentConfig }}` means I need to put your defaults back in. What exactly does this do? 

```yaml
# Autodiscovery for Kubernetes
listeners:
  - name: kubelet
config_providers:
  - name: kubelet
    polling: true
```

Do we need a docker config_provider? We have it in our config, and I can't figure out why.

I've checked out these docs, but I'm still rather confused.
- https://docs.datadoghq.com/containers/kubernetes/integrations
- https://docs.datadoghq.com/getting_started/containers/autodiscovery
- https://docs.datadoghq.com/containers/docker/integrations/

We have a kubernetes cluster deployed via helm (3.1.9 currently). We're on EKS 1.23, and about to upgrade to 1.24 (which means we'll be going to containerd). Do I need to make any changes to Autodiscovery bits to make containerd work?
