### ISSUE TITLE
datadog chart: Unable to provide DaemonSet credentials via `envFrom`

### ISSUE THREAD

**Issue by drewfradette** [DataDog/helm-charts#1077]
**Describe what happened:**
Our secrets are externally managed and sync'd via an operator. Due to a limitation of the operator, I want to use one of these managed secrets to provide Datadog agents with `DD_API_KEY` and `DD_APP_KEY` via `datadog.envFrom`.

Unfortunately, Without `datadog.apiKeyExistingSecret` or `datadog.apiKey` set, no `DaemonSet` resource is produced ([link](https://github.com/DataDog/helm-charts/blob/datadog-3.30.6/charts/datadog/templates/daemonset.yaml#L3)).

**Describe what you expected:**
* Initially, I expected the environment variables to be exposed to the agents.
* Looking into the chart, I expected at least one of the following options to be available:
  1. I can specify the secret key value instead of needing it to conform to `api-key` and `app-key` ([example](https://github.com/DataDog/helm-charts/blob/datadog-3.30.6/charts/datadog/templates/_containers-common-env.yaml#L11))
  2. `datadog.envFrom` would allow me to provide all the config variables available to the agent.

**Steps to reproduce the issue:**

This is a unfortunately limitation of the operator but the fix is easier on the datadog chart side. Here is a minimal reproduction without any of the operator bits:

* `datadog-managed-secret.yaml`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: managed-datadog-secret
type: Opaque
data:
  DD_API_KEY: b64-api-secret
  DD_APP_KEY: b64-app-secret
```

* `values.yaml`
```yaml
datadog:
  envFrom:
    - secretRef:
        name: doppler-datadog-secret
```

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes 1.26 (EKS)
Chart version 3.30.6 (but it applies to the latest version as well)
