### ISSUE TITLE
Datadog chart: use the global container registry setting for admission controller instrumentation init container

### ISSUE THREAD

**Issue by sergei-ivanov** [DataDog/helm-charts#1078]
**Describe what happened:**

By default, the admission controller injects an init container with the image of `gcr.io/datadoghq/dd-lib-java-init`, even though we override the registry value as:
```yaml
registry: public.ecr.aws/datadog
```

Pod events:
```
Container image "gcr.io/datadoghq/dd-lib-java-init:v1.14.0" already present on machine
```

**Describe what you expected:**

We expected that the admission controller inherited the global registry setting for the injected init container.

**Workaround:**

We had to additionally inject the following environment variable through the value file.
The reference documentation is [here](https://docs.datadoghq.com/tracing/trace_collection/library_injection_local/?tab=kubernetes).

```yaml
clusterAgent:
  env:
    - name: DD_ADMISSION_CONTROLLER_AUTO_INSTRUMENTATION_CONTAINER_REGISTRY
      value: public.ecr.aws/datadog
```

Now it looks better:
```
Pulling image "public.ecr.aws/datadog/dd-lib-java-init:v1.14.0"
```

**Proposal:**

Integrate it into the chart [here](https://github.com/DataDog/helm-charts/blob/5d4eb04e37754bfce11e9fc6512fad2de0fd193d/charts/datadog/templates/cluster-agent-deployment.yaml#L188) by adding something like this:
```
          - name: DD_ADMISSION_CONTROLLER_AUTO_INSTRUMENTATION_CONTAINER_REGISTRY
            value: {{ .Values.registry | quote }}
```

**Comment by wadexu007** [comment]
We also met same issue, we'd like to set a different container registry

```
  podAnnotations:
    admission.datadoghq.com/java-lib.version: "v1.8.3"
```

**Comment by ksubileau** [comment]
We still have the same issue after upgrading to the latest version including PR #1376 
Indeed, the fix proposed in #1376 can only have an effect when `clusterAgent.admissionController.agentSidecarInjection.enabled` is `true`, which is not the default configuration, nor the one we use : 
```
registry: public.ecr.aws/datadog
clusterAgent:
  admissionController:
    enabled: true

    agentSidecarInjection:
      enabled: false
```

Could you please reopen this issue ?
