### ISSUE TITLE
Does the datadog agent helm support all the variables of Datadog agent?

### ISSUE THREAD

**Issue by LiuKay** [DataDog/helm-charts#1089]
**Describe what happened:**

I can find the OTLP config in [https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml)

```
## OTLP ingest related configuration
  otlp:
    receiver:
      protocols:
        # datadog.otlp.receiver.protocols.grpc - OTLP/gRPC configuration
        grpc:
          # datadog.otlp.receiver.protocols.grpc.enabled -- Enable the OTLP/gRPC endpoint
          enabled: false
          # datadog.otlp.receiver.protocols.grpc.endpoint -- OTLP/gRPC endpoint
          endpoint: "0.0.0.0:4317"
          # datadog.otlp.receiver.protocols.grpc.useHostPort -- Enable the Host Port for the OTLP/gRPC endpoint
          useHostPort: true

        # datadog.otlp.receiver.protocols.http - OTLP/HTTP configuration
        http:
          # datadog.otlp.receiver.protocols.http.enabled -- Enable the OTLP/HTTP endpoint
          enabled: false
          # datadog.otlp.receiver.protocols.http.endpoint -- OTLP/HTTP endpoint
          endpoint: "0.0.0.0:4318"
          # datadog.otlp.receiver.protocols.http.useHostPort -- Enable the Host Port for the OTLP/HTTP endpoint
          useHostPort: true
```

**Describe what you expected:**

Does the helm config support all the OTLP configs that Datadog Agent support? for example `max_recv_msg_size_mib`
[https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml)

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by clamoriniere** [comment]
Hi @LiuKay 

thanks for opening this issue.

Currently only the parameters defined in the values.yaml are supported, But you can configure `max_recv_msg_size_mib` by adding the environment variable `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_MAX_RECV_MSG_SIZE_MIB` in the chart option `agents.containers.agent.env` 

something like:

```yaml
agents:
  containers:
    agent:
    - name: DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_MAX_RECV_MSG_SIZE_MIB
      value: 10
```

please let us know it you are able to configure the OTLP as you would like thanks to the chart. If yes please close the issue.
