### ISSUE TITLE
Add support for configuring DD_DOGSTATSD_TAGS

### ISSUE THREAD

**Issue by babilen5** [DataDog/helm-charts#111]
**Describe what happened:**

In order to add tags to custom DogStatsD metrics, users currently have to manually configure the [DD_DOGSTATSD_TAGS] environment variable.

This currently requires users to pass the following configuration:

```
agents:
  containers:
    agent:
      env:
        - name: DD_DOGSTATSD_TAGS
          value: '["env:foo","service:bar","version:0.0.1","team:quux"]'
```

**Describe what you expected:**

It would be fantastic to be able to configure `DD_DOGSTATSD_TAGS` in a similar way to `DD_TAGS`. In particular I would have expected the following to work:

```
datadog:
  dogstatsd:
    tags:
      - "env:foo"
      - "service:bar"
      - "version:0.0.1"
      - "team:quux"
```

**Steps to reproduce the issue:**

Configure the `DD_DOGSTATSD_TAGS` environment variable.

[DD_DOGSTATSD_TAGS]: https://docs.datadoghq.com/agent/kubernetes/?tab=helm#dogstatsd-custom-metrics
