### ISSUE TITLE
Support for sidecar 

### ISSUE THREAD

**Issue by brettcurtis** [DataDog/helm-charts#1111]
**Describe what happened:**

Setting up Database Monitoring for Google Cloud SQL managed Postgres mentions the use of a proxy [here](https://docs.datadoghq.com/database_monitoring/setup_postgres/gcsql/?tab=kubernetes#working-with-hosts-through-a-proxy) however I'm unable to add a sidecar to the cluster agent using the helm charts. Google recommends this approach for many [reasons](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#run_the_in_a_sidecar_pattern) and we'd like to continue implementing the sidecar approach for Datadog as well. 

**Describe what you expected:**

**edit** - Working with support I understand this needs to be on the node agent not the cluster agent since the node agent is the agent that will connect to SQL and run the checks.

I'd like to be able to define a sidecar, something like this:

```yaml
agents:
  image:
    name: agent
    tag: 7.45.0

  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 512Mi

  sidecarContainers:
    name: cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.3.0
    args:
      - "--private-ip"
      - "--port=6000"
    securityContext:
      runAsNonRoot: true
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
```
