### ISSUE TITLE
Kubelet CA certificate location changes on AKS 1.16+

### ISSUE THREAD

**Issue by TJEvans** [DataDog/helm-charts#114]
**Describe what happened:**
Datadog/datadog agent helm chart deploys successfully into an Azure Kubernetes Services instance but does not return data due to certificate validation error.

> Error running check kubelet: [{"message": "Unable to detect the kubelet URL automatically: cannot set a valid kubelet host: cannot connect to kubelet using any of the given hosts: [XX.XXX.X.X] [aks-agentpool-XXXXXXXX-vmssXXXXX.internal.cloudapp.net. aks-agentpool-XXXXXXXX-vmssXXXXX], Errors: [Get \"https://XX.XXX.X.X:XXXXX/pods\": x509: cannot validate certificate for XX.XXX.X.X because it doesn't contain any IP SANs Get \"https://aks-agentpool-XXXXXXXX-vmssXXXXX.internal.cloudapp.net.:XXXXX/pods\": x509: certificate is valid for aks-agentpool-XXXXXXXX-vmssXXXXX, not aks-agentpool-XXXXXXXX-vmssXXXXX.internal.cloudapp.net. Get \"https://aks-agentpool-XXXXXXXX-vmssXXXXX:XXXXX/pods\": x509: certificate signed by unknown authority cannot connect: http: \"Get \\\"http://XX.XXX.X.X:XXXXX/\\\": dial tcp XX.XXX.X.X:XXXXX: connect: connection refused\" cannot connect: http: \"Get \\\"http://aks-agentpool-XXXXXXXX-vmssXXXXX.internal.cloudapp.net.:XXXXX/\\\": dial tcp XX.XXX.X.X:XXXXX: connect: connection refused\" cannot connect: http: \"Get \\\"http://aks-agentpool-XXXXXX-XXXXX:XXXX/\\\": dial tcp XX.XXX.X.X:XXXXX: connect: connection refused\"]", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 828, in run\n    self.check(instance)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kubelet/kubelet.py\", line 295, in check\n    raise CheckException(\"Unable to detect the kubelet URL automatically: \" + kubelet_conn_info.get('err', ''))\ndatadog_checks.base.errors.CheckException: Unable to detect the kubelet URL automatically: cannot set a valid kubelet host: cannot connect to kubelet using any of the given hosts: [XX.XXX.X.X] [aks-agentpool-XXXXXXXX-vmssXXXXX.internal.cloudapp.net. aks-agentpool-XXXXXXXX-vmssXXXXX], Errors: [Get \"https://XX.XXX.X.X:XXXXX/pods\": x509: cannot validate certificate for XX.XXX.X.X because it doesn't contain any IP SANs Get \"https://aks-agentpool-XXXXXXXX-vmssXXXXX.internal.cloudapp.net.:XXXXX/pods\": x509: certificate is valid for aks-agentpool-XXXXXXXX-vmssXXXXX, not aks-agentpool-XXXXXXXX-vmssXXXXX.internal.cloudapp.net. Get \"https://aks-agentpool-XXXXXXXX-vmssXXXXX:XXXXX/pods\": x509: certificate signed by unknown authority cannot connect: http: \"Get \\\"http://XX.XXX.X.X:XXXXX/\\\": dial tcp XX.XXX.X.X:XXXXX: connect: connection refused\" cannot connect: http: \"Get \\\"http://aks-agentpool-XXXXXXXX-vmssXXXXX.internal.cloudapp.net.:XXXXX/\\\": dial tcp XX.XXX.X.X:XXXXX: connect: connection refused\" cannot connect: http: \"Get \\\"http://aks-agentpool-XXXXXX-XXXXX:XXXX/\\\": dial tcp XX.XXX.X.X:XXXXX: connect: connection refused\"]\n"}]

**Describe what you expected:**
Would have hoped to not need to provide as many value.yaml overrides to support this environment.  Does the helm deployment already have a conditional that checks for AKS environment?  If not documenting here incase anyone else runs into it.

```
  # agents.volumes -- Specify additional volumes to mount in the dd-agent container
  volumes: 
     - name: k8s-certs 
       hostPath: 
         path: /etc/kubernetes/certs
         type: ''

  # agents.volumeMounts -- Specify additional volumes to mount in all containers of the agent pod
  volumeMounts: 
     - name: k8s-certs
       mountPath: /etc/kubernetes/certs
       readOnly: true

  # datadog.env -- Set environment variables for all Agents
  ## The Datadog Agent supports many environment variables.
  ## ref: https://docs.datadoghq.com/agent/docker/?tab=standard#environment-variables
  env: 
     - name: DD_KUBELET_CLIENT_CA
       value: /etc/kubernetes/certs/kubeletserver.crt
```

**Additional environment details (Operating System, Cloud provider, etc):**
Microsoft Azure AKS.  Related Bug with solution - https://github.com/DataDog/datadog-agent/issues/5942
