### ISSUE TITLE
Redis config yaml not getting created/generated

### ISSUE THREAD

**Issue by kamal-brill** [DataDog/helm-charts#1204]
**Describe what happened:**
We have defined the `redisdb.yaml` under `datadog->confd`, but it's not generating the config yaml under `/etc/datadog-agent/conf.d/redisdb.d/`

**Describe what you expected:**
config defined in `datadog->confd->redisdb.yaml` should generate `/etc/datadog-agent/conf.d/redisdb.d/conf.yaml`

**Steps to reproduce the issue:**

````yaml
replicaCount: 1
image:
  registry: docker.io
  repository: datadog/agent
  tag: 7.33.1
  pullPolicy: Always
serviceAccount:
  create: false
  name: data-dog-sa

extraEnvVarsMap:
  DD_KUBELET_TLS_VERIFY: "False"
  DD_LOGS_ENABLED: "False"
  DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "True"

extraEnvVars:
 - name: DD_API_KEY
   valueFrom:
    secretKeyRef:
        name: api-keys
        key: DD_API_KEY

datadog:
  apiKeyExistingSecret: api-keys
  kubelet:
    tlsVerify: false
  checks:
    redisdb: true
  confd:
    redisdb.yaml: |-
      init_config:
      instances:
        - host: "host1-outside-k8s.com"
          port: "6379"
          password: "plain-password-text"
          timeout: "30"
          ssl: true

        - host: "host2-outside-k8s.com"
          port: "6379"
          password: "plain-password-text"
          timeout: "30"
          ssl: true
     
name: deployment
ports:
- containerPort: 8080
  protocol: TCP
  name: http
affinity: {}
cluster_agent:
  cmd_port: 5005
apm_config:
  enabled: true
  env: dev
resources:
  limits:
    cpu: "1"
    memory: 3Gi
  requests:
    cpu: "1"
    memory: 2Gi
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
process_config:
      enabled: "disabled"
      process_dd_url: https://process.datadoghq.com
logs_config:
  container_collect_all: "false"
````

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by khewonc** [comment]
Hi @kamal-brill, I believe the config would be mounted in `/etc/datadog-agent/conf.d` as mentioned [here](https://github.com/DataDog/helm-charts/tree/main/charts/datadog#confd-and-checksd). As long as the `redisdb.yaml` config is in `/etc/datadog-agent/conf.d`, it should be getting picked up by the agent. If you're seeing errors with the redisdb check or if the check is missing, would you mind creating a [support ticket](https://docs.datadoghq.com/help/) and sending a [node agent flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6v7) for the team to investigate?

**Comment by kamal-brill** [comment]
@khewonc Okay, then I misunderstood the other way. I thought config defined in the above helm chart yaml would create the `redisdb.yaml` in `/etc/datadog-agent/conf.d`. 

The problem we have is, in the ConfigMap, we aren't sure how to use the password from env var as we define `redisdb.yaml` as single key-value pair, like below,

````yaml
apiVersion: v1
data:
  redisdb.yaml: |-
    cluster: yes
    init_config:
    instances:
      - host: host1-outside-k8s.com
        port: 6379
        password: secret-password
        tags:
          cacheclusterid: api-nonprod
        ssl: true
        socket_timeout: 30

      - host: host2-outside-k8s.com
        port: 6379
        password: secret-password-2
        tags:
          cacheclusterid: api-nonprod
        ssl: true
        socket_timeout: 30
kind: ConfigMap
````
