### ISSUE TITLE
`commonLabels` not applying

### ISSUE THREAD

**Issue by biasedbit** [DataDog/helm-charts#1212]
**Describe what happened:**

```yaml
commonLabels:
  foo: bar

registry: public.ecr.aws/datadog
targetSystem: linux
datadog:
  apiKey: ******
  site: us5.datadoghq.com

clusterAgent:
  admissionController:
    enabled: true
    configMode: service
    failurePolicy: Fail
    mutateUnlabelled: true
```

**Describe what you expected:**

I'd expect to see `foo=bar` _somewhere_ but I can't find it anywhere in Deployments or Pods.

**Steps to reproduce the issue:**

Following the DataDog Agent [setup steps for helm](https://docs.datadoghq.com/containers/cluster_agent/setup/?tab=helm).

**Additional environment details (Operating System, Cloud provider, etc):**

Chart version: 3.40.2
Cloud Provider: EKS 1.24
