### ISSUE TITLE
podLabelsAsTags not work with kubernetes_state metrics

### ISSUE THREAD

**Issue by tiendungitd** [DataDog/helm-charts#1213]
**Describe what happened:**

- I've deployed DataDog Agent Helm Chart 2.32.3 onto EKS 1.23
- Enable podLabelsAsTags in value.yaml as below

```
datadog:
  kubeStateMetricsEnabled: false
  clusterName: mngd-eks-serverstest
  networkMonitoring:
    enabled: true
  logLevel: INFO
  podLabelsAsTags: 
    app.kubernetes.io/name: appname
    app.kubernetes.io/instance: appinstance
```
- The problem is that `appname` tag is only present in custom and standard metrics while missing in kubernetes_state metrics such as `kubernetes_state.pod.status_phase`.
![image](https://github.com/DataDog/helm-charts/assets/21011388/c17c4518-b491-4cfd-88ff-0b1438a27346)

**Describe what you expected:**
I would expect ' kubernetes_state.pod.status_phase`, `kubernetes_state.hpa.condition` to have an `appname` tag, currently, I have to use `kube_app_name` tag

**Additional environment details (Operating System, Cloud provider, etc):**
EKS 1.23

Not sure if I need to enable something in the helm chart?
