### ISSUE TITLE
Multiple hostPort option

### ISSUE THREAD

**Issue by djtecha** [DataDog/helm-charts#123]
Running the most up-to-date helm chart I'm trying to get a Jenkins EKS pod to be able to communicate with the daemonset running on the same node. I can get the logic to work where I open the hostPort for dogstatsD and that works for sending metrics. But for the logging section it has to get shipped to a custom integration for Jenkins that accepts a TCP log. I'm not sure I can open multiple hostPorts to the daemonset using the current helm chart. Basically I need to be able to open both 8125 (for the dogstatsD) and 8126 for the jenkins log receiver.

```
datadog:
  apiKeyExistingSecret: datadog-api
  log_format_json: true
  logLevel: warn

  confd:
    jenkins.yaml: |-
      logs:
        - type: tcp
          port: 8126
          service: ops
          source: jenkins
          tags:
            - jenkins_job

  leaderElection: true
  collectEvents: true

  processAgent:
    enabled: true
    processCollection: true

  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true

  networkMonitoring:
    enabled: true

  dogstatsd:
    originDetection: true
    useHostPort: true
    useHostPID: true
    nonLocalTraffic: true

```
