### ISSUE TITLE
When installing Datadog for Windows, the `process-agent` container isn’t mounting the `auth-token` volume

### ISSUE THREAD

**Issue by alee2233** [DataDog/helm-charts#1235]
### **Describe what happened:**
We are following this guide ([docs](https://docs.datadoghq.com/agent/troubleshooting/windows_containers/#mixed-clusters-linux--windows
)) to install the Datadog Agent for a mixed (Linux and Windows) cluster.

When setting `targetSystem: "windows"`, the following is seen in the `process-agent` container logs:

> `process-agent 2023-11-09 19:20:22 UTC | PROCESS | INFO | (pkg/config/remote/client.go:301 in pollLoop) | retrying the first update of remote-config state (could not acquire agent auth token: unable to read authentication token file: open C:/ProgramData/Datadog/auth/token: The system cannot find the path specified.)`

This is because the Helm template doesn't mount the `auth-token` when `targetSystem: "windows"` (but I think it still should?): https://github.com/DataDog/helm-charts/blob/220d92e4087c0a0c12e0eb4577b68b48c84b016a/charts/datadog/templates/_container-process-agent.yaml#L64-L68

We can currently work around this by patching the DaemonSet:
`kubectl patch ds datadog-agent-windows -n monitoring --patch '{"spec": {"template": {"spec": {"containers": [{"name": "process-agent", "volumeMounts": [{"name": "auth-token", "mountPath": "C:/ProgramData/Datadog/auth"}]}]}}}}'` 

However, I think that template should be updated so both Linux and Windows installations will mount that volume.

### **Describe what you expected:**
No logs with `unable to read authentication token file: open C:/ProgramData/Datadog/auth/token: The system cannot find the path specified.` in the `process-agent` container.

### **Steps to reproduce the issue:**
1. Follow the guidance on installing Datadog in a mixed Linux+Windows cluster: https://docs.datadoghq.com/agent/troubleshooting/windows_containers/#mixed-clusters-linux--windows
2. View the `process-agent` container logs from a Datadog Agent running on a Windows Node.

### **Additional environment details (Operating System, Cloud provider, etc):**
The cluster is running on **AWS EKS**.

Windows Node System Info:
```
  Kernel Version:             10.0.20348.2031
  OS Image:                   Windows Server 2022 Datacenter
  Operating System:           windows
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.18
  Kubelet Version:            v1.28.2-eks-a5df82a
  Kube-Proxy Version:         v1.28.2-eks-a5df82a
``` 

Helm Chart Details:
```
  repository = "https://helm.datadoghq.com"
  chart      = "datadog"
  version    = "3.44.1"
```

Helm Installation 1 values (Linux Nodes):
```
clusterAgent:
  createPodDisruptionBudget: true
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
datadog:
  apiKeyExistingSecret: datadog-agent
  appKeyExistingSecret: datadog-agent
  clusterName: xxxxxxxxx
  kubeStateMetricsCore:
    enabled: true
  kubeStateMetricsEnabled: false
  nodeLabelsAsTags:
    kubernetes.io/os: os
  prometheusScrape:
    enabled: true
```

Helm Installation 2 values (Windows Nodes):
```
clusterAgent:
  enabled: false
datadog:
  apiKeyExistingSecret: datadog-agent
  appKeyExistingSecret: datadog-agent
  clusterName: xxxxxxxxx
  nodeLabelsAsTags:
    kubernetes.io/os: os
datadog-crds:
  crds:
    datadogMetrics: false
existingClusterAgent:
  join: true
  serviceName: datadog-agent-cluster-agent
  tokenSecretName: datadog-agent-cluster-agent
targetSystem: windows
```
