### ISSUE TITLE
Windows Datadog Node Agents are unable to connect to Cluster Agent

### ISSUE THREAD

**Issue by alee2233** [DataDog/helm-charts#1236]
### **Describe what happened:**
We are following this guide ([docs](https://docs.datadoghq.com/agent/troubleshooting/windows_containers/#mixed-clusters-linux--windows
)) to install the Datadog Agent for a mixed (Linux and Windows) cluster. Both Helm charts installed and pods are in the running state on both Linux and Windows nodes.

Looking at the container logs, the Windows node agents are unable to “join” the existing Datadog Cluster Agent (DCA).

In the `process-agent` container logs:
> `(pkg/process/runner/runner.go:151 in runCheck) | Unable to run check 'pod': temporary failure in clusterAgentClient, will retry later: "https://<DCA-IP>:5005/version" is unavailable: timeout calling "https://<DCA-IP>:5005/version": Get "https://<DCA-IP>:5005/version": dial tcp <DCA-IP>:5005: i/o timeout`

In the `agent` container logs:
> `pkg/autodiscovery/providers/clusterchecks.go:197 in heartbeatSender) | Unable to send extra heartbeat to Cluster Agent, err: DCA Client not initialized by main provider, cannot post heartbeat`

### **Describe what you expected:**
Datadog Agent on Windows nodes can successfully join the existing running Datadog Cluster Agent.

### **Steps to reproduce the issue:**
1. Follow the guidance on installing Datadog in a mixed Linux+Windows cluster: https://docs.datadoghq.com/agent/troubleshooting/windows_containers/#mixed-clusters-linux--windows
2. View the `process-agent` and `agent` container logs from a Datadog Agent running on a Windows Node.

### **Additional environment details (Operating System, Cloud provider, etc):**
The cluster is running on **AWS EKS**.

Windows Node System Info:
```
  Kernel Version:             10.0.20348.2031
  OS Image:                   Windows Server 2022 Datacenter
  Operating System:           windows
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.18
  Kubelet Version:            v1.28.2-eks-a5df82a
  Kube-Proxy Version:         v1.28.2-eks-a5df82a
``` 

Helm Chart Details:
```
  repository = "https://helm.datadoghq.com"
  chart      = "datadog"
  version    = "3.44.1"
```

Helm Installation 1 values (Linux Nodes):
```
clusterAgent:
  createPodDisruptionBudget: true
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
datadog:
  apiKeyExistingSecret: datadog-agent
  appKeyExistingSecret: datadog-agent
  clusterName: xxxxxxxxx
  kubeStateMetricsCore:
    enabled: true
  kubeStateMetricsEnabled: false
  nodeLabelsAsTags:
    kubernetes.io/os: os
  prometheusScrape:
    enabled: true
```

Helm Installation 2 values (Windows Nodes):
```
clusterAgent:
  enabled: false
datadog:
  apiKeyExistingSecret: datadog-agent
  appKeyExistingSecret: datadog-agent
  clusterName: xxxxxxxxx
  nodeLabelsAsTags:
    kubernetes.io/os: os
datadog-crds:
  crds:
    datadogMetrics: false
existingClusterAgent:
  join: true
  serviceName: datadog-agent-cluster-agent
  tokenSecretName: datadog-agent-cluster-agent
targetSystem: windows
```
