### ISSUE TITLE
Cluster Checks pods cannot access/decrypt Secrets Backend w/ k8s secrets

### ISSUE THREAD

**Issue by kzap** [DataDog/helm-charts#1247]
**Describe what happened:**
I tried to use the Secrets Backend as documented [here](https://docs.datadoghq.com/agent/configuration/secrets-management/?tab=linux) to store secrets in a k8s secret and use it in my Cluster Check in Helm `values.yaml` like so:
```yaml
datadog:
  secretBackend:
    command:  "/readsecret_multiple_providers.sh"
    enableGlobalPermissions: false
    roles:
      - namespace: datadog
        secrets:
          - datadog-secret
clusterAgent:
  confd:
    rabbitmq.yaml: |-
        cluster_check: true
        init_config:
        instances:
        - rabbitmq_api_url: https://RABBITMQ-URI/api/
          username: USERNAME
          password: ENC[k8s_secret@datadog/datadog-secret/rabbitmq-secret]
```

I also created a k8s secret object in the `datadog` namespace called `datadog-secret` and put my `rabbitmq-secret` value in there:
```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
  name: datadog-secret
  namespace: datadog
type: Opaque
stringData:
  rabbitmq-secret: "secret"
``` 

**Describe what you expected:**
- When I run my `kubectl exec $clusterDeployment -- agent secret` on the cluster check pod, it SHOULD show its decrypting my secret
    ```sh
    === Checking executable permissions ===
    Executable path: /readsecret_multiple_providers.sh
    Executable permissions: OK, the executable has the correct permissions
    
    Permissions Detail:
    File mode: 100550
    Owner: root
    Group: root
    
    === Secrets stats ===
    Number of secrets decrypted: 1
    ```
- Instead I find it does not list any secrets that it is decrypting:
    ```sh
    === Checking executable permissions ===
    Executable path: /readsecret_multiple_providers.sh
    Executable permissions: OK, the executable has the correct permissions
    
    Permissions Detail:
    File mode: 100550
    Owner: root
    Group: root
    
    === Secrets stats ===
    Number of secrets decrypted: 0
    ```
- Also in the logs of the cluster check pods I find 401 auth errors in my logs indicating its not able to use the correct credentials.

**Steps to reproduce the issue:**
- See above `values.yaml`

- I have found the solution by applying the following fixes which I opened a PR for: https://github.com/DataDog/helm-charts/pull/1246
