### ISSUE TITLE
DataDog violating PodSecurity Policy

### ISSUE THREAD

**Issue by JakeCooper** [DataDog/helm-charts#1269]
**Describe what happened:**

While attempting to upgrade from v1.24 to v1.25, DataDog seems to be adding host mounts to our containers

![CleanShot 2023-12-11 at 22 50 15](https://github.com/DataDog/helm-charts/assets/5499880/45c5d24d-0eb4-4c22-9150-870cc42b8c74)

![CleanShot 2023-12-11 at 22 50 40](https://github.com/DataDog/helm-charts/assets/5499880/0137ff60-1e05-4852-9d49-1439d28633ed)

**Describe what you expected:**
I've turned off dogstatsd socket so I'd expect it to not bind mount to the container

**Steps to reproduce the issue:**

Apply helm chart with these options
```
datadog:
  fullnameOverride: datadog

  agents:
    revisionHistoryLimit: 1
    tolerations:
      - effect: NoSchedule
        key: dedicated
        value: clickhouse
        operator: Equal
    containers:
      initContainers:
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "300m"
      agent:
        resources:
          requests:
            memory: "1500Mi"
            cpu: "250m"
          limits:
            memory: "3000Mi"
            cpu: "1000m"
      processAgent:
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "700Mi"
            cpu: "500m"   
      securityAgent:
        resources:
          requests:
            memory: "25Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "200m"    
      systemProbe:
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "200m" 
      traceAgent:
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "400m"

  datadog:
    kubeStateMetricsEnabled: false # disable the `kube-state-metrics` chart dep installation.
    kubeStateMetricsCore:
      enabled: true                # enable the new check
    apiKeyExistingSecret: datadog-api-key
    collectEvents: true
    dogstatsd:
      useSocketVolume: false
      useHostPort: true
    processAgent: 
      enabled: true
    networkMonitoring:
      enabled: true
    apm:
      portEnabled: true
    logs:
     enabled: true
     containerCollectAll: true
     autoMultiLineDetection: true
    containerExcludeLogs: "kube_namespace:^grafana-.* kube_namespace:^argo-cd$ kube_namespace:^argo-rollouts$ kube_namespace:^datadog$ kube_namespace:^default$ kube_namespace:^kube-node-lease$ kube_namespace:^kube-public$ kube_namespace:^kube-system$ name:kuma-sidecar kube_namespace:^observability$ kube_namespace:^internal-observability$"
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
  
  clusterAgent:
    revisionHistoryLimit: 1
    resources:
      requests:
        memory: "25Mi"
        cpu: "50m"
      limits:
        memory: "150Mi"
        cpu: "200m" 
    replicas: 2
    enabled: true
    rbac:
      create: true
    tokenExistingSecret: datadog-cluster-agent-token   
    admissionController:
      enabled: true
      mutateUnlabelled: true

  clusterChecksRunner:
    revisionHistoryLimit: 1
    resources:
      requests:
        memory: "25Mi"
        cpu: "50m"
      limits:
        memory: "150Mi"
        cpu: "200m" 

```

**Additional environment details (Operating System, Cloud provider, etc):**
GKE
