### ISSUE TITLE
Synthetics Private Location - helm chart example  using configSecret

### ISSUE THREAD

**Issue by thalanil** [DataDog/helm-charts#1274]
**Describe what happened:**
Using:
argocd to deploy datadog synthetic pvt location with the following values:
```
values:
  configSecret: private-location-worker-config
```
Secret `private-location-worker-config` is a valid secret Opaque

**Describe what you expected:**
configFile should be setup using the secret `private-location-worker-config` 

Instead an error is shown on logs saying:
warn: Missing config file and will attempt to use command line instead.
And warning apikey, accesskey, secretkey ,etc are missing or not setup

**Steps to reproduce the issue:**
Deploy argocd app 
Note: datadog secret should be deployed in datadog namespace 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dd-private-location
  namespace: argocd
spec:
  project: default
  source:
    chart: synthetics-private-location
    repoURL: https://helm.datadoghq.com
    targetRevision  : "0.15.*"
    helm:
      values: |
        configSecret: private-location-worker-config
  destination:
    server: "https://kubernetes.default.svc"
    namespace: datadog
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
```

**Additional environment details (Operating System, Cloud provider, etc):**

- On premise
- argocd

**Comment by nidhiben** [comment]
Curious, on how did you configure the secret. I am facing this issue when I am trying to create the secret using SecretProviderClass custom resource and storing the worker configuration AWS secret manager and accessing it via IRSA.

**Comment by jmanuelortizn** [comment]
@nidhiben 

I am using sealed secrets, sealed secret create the opaque secret and I am referencing that opaque secret from helm values

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
```

**Comment by a-Name** [comment]
Hi, did you eventually manage to get your private location running ?
Thanks for the feedback!

**Comment by booyaa** [comment]
@jmanuelortizn Make sure the secret data item is called `synthetics-check-runner.json` as this is what the helm chart is looking for. An example can be found in the secret [template](https://github.com/DataDog/helm-charts/blob/main/charts/synthetics-private-location/templates/secret.yaml#L9) created if you use `--set-file configFile` switch during `helm install`

**Comment by booyaa** [comment]
Since caring is sharing, I'll post hints for the External Secrets using AWS Secrets Manager as the backend. I've edited for brevity

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synthetics-private-location
spec:
  data:
  - remoteRef:
      key: asm/path/to/seccret/item
    # important: this is the secret data item name that the worker looks for and cannot 
    secretKey: synthetics-check-runner.jsonbe changed
  target:
    name: synthetics-private-location
```
