### ISSUE TITLE
Datadog chart 3.51.0 broken due to missing config map

### ISSUE THREAD

**Issue by MattJeanes** [DataDog/helm-charts#1293]
**Describe what happened:**

Installing the datadog chart version 3.51.0 from scratch or upgrading it is broken

The problem appears to have been introduced in https://github.com/DataDog/helm-charts/commit/eafa471c43a17a3d393ffcf7f3752876d83fed56 as the error message references the new config map added in this commit.

I am not sure why it is failing exactly, but everything is working fine in version 3.50.0.

```
upgrade.go:442: [debug] warning: Upgrade "datadog" failed: no ConfigMap with the name "datadog-kpi-telemetry-configmap" found
upgrade.go:460: [debug] Upgrade failed and atomic is set, rolling back to last successful release
```

**Describe what you expected:**

It installs correctly

**Steps to reproduce the issue:**

1. Attempt to install the datadog chart version 3.51.0 using the `Chart.yaml` specified below
2. It fails to install due to a missing config map "datadog-kpi-telemetry-configmap" (assuming 'datadog' is the release name)

**Additional environment details (Operating System, Cloud provider, etc):**

Azure Pipelines, Windows Server 2022, Helm 3.12.3

Something which may possibly affect this is that we install the chart as a dependency twice in the same release, once for Windows and once for Linux:

Our `Chart.yaml`:

```yaml
apiVersion: v2
name: datadog
type: application
version: 1.0.0
dependencies:
  - name: datadog-crds
    version: "~1.3.0"
    repository: "https://helm.datadoghq.com"
  - name: kube-state-metrics
    version: "~5.15.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: datadog
    alias: "datadog-agent-linux"
    version: "~3.50.0"
    repository: "https://helm.datadoghq.com"
  - name: datadog
    alias: "datadog-agent-windows"
    version: "~3.50.0"
    repository: "https://helm.datadoghq.com"
```
