### ISSUE TITLE
kpi-telemetry-configmap cause helm-diff to always show changes

### ISSUE THREAD

**Issue by rohit-gohri** [DataDog/helm-charts#1296]
**Describe what happened:**
Upon upgrading to chart version 3.51.2 every time my CI runs [helm-diff](https://github.com/databus23/helm-diff) plugin it shows a new diff. This is similar to #512 but I don't see any way to disable this:

```yaml
  apiVersion: v1
  data:
-   install_id: 908c847e-9858-40b9-b3b2-52690d1d7712
-   install_time: "1705586396"
+   install_id: fcb2757f-14ac-44b1-aac8-596611d129b6
+   install_time: "1705615578"
    install_type: k8s_manual
  kind: ConfigMap
  metadata:
    labels:
      app.kubernetes.io/instance: datadog-agent
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: datadog-agent
      app.kubernetes.io/version: "7"
      helm.sh/chart: datadog-3.51.2
    name: datadog-agent-kpi-telemetry-configmap
    namespace: default
```

**Describe what you expected:**
I expect the helm chart's rendered output to be static.

**Steps to reproduce the issue:**
Install the helm chart and run helm diff

**Additional environment details (Operating System, Cloud provider, etc):**
