### ISSUE TITLE
[Q] How to specify which pods to collect logs from?

### ISSUE THREAD

**Issue by anhkhoa45** [DataDog/helm-charts#131]
Current datadog-values.yaml logs setting:

```yaml
  ## Enable logs agent and provide custom configs
  logs:
    # datadog.logs.enabled -- Enables this to activate Datadog Agent log collection
    ## ref: https://docs.datadoghq.com/agent/basic_agent_usage/kubernetes/#log-collection-setup
    enabled: true

    # datadog.logs.containerCollectAll -- Enable this to allow log collection for all containers
    ## ref: https://docs.datadoghq.com/agent/basic_agent_usage/kubernetes/#log-collection-setup
    containerCollectAll: true

    # datadog.logs.containerCollectUsingFiles -- Collect logs from files in /var/log/pods instead of using container runtime API
    ## It's usually the most efficient way of collecting logs.
    ## ref: https://docs.datadoghq.com/agent/basic_agent_usage/kubernetes/#log-collection-setup
    containerCollectUsingFiles: true
```

Desired result:

- To include/exclude namespace/pods to collect logs from
- To specify which level of logs to collect from a pod

**Comment by clamoriniere** [comment]
Hi @anhkhoa45

If you want more documentation about how to configure granularly the logs collection you can look at our [datadog documentation website](https://docs.datadoghq.com/agent/kubernetes/log/?tab=helm)

Some pointers in the docs:
* to exclude/include specific containers/namespaces: the environment variables `DD_CONTAINER_INCLUDE_LOGS` and `DD_CONTAINER_EXCLUDE_LOGS ` can be used  ([doc link](https://docs.datadoghq.com/agent/docker/?tab=standard#ignore-containers))
* to only collect logs from specific pods, you can deactivate `containerCollectAll: false` add use [pod's auto-discovery pod annotations](https://docs.datadoghq.com/agent/kubernetes/log/?tab=kubernetes#autodiscovery) to specify logs configuration for each pod.
* to exclude some logs lines, it is possible to configure a [logs filter](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=kubernetes#filter-logs)

Let us know if you find the needed information in our doc.

**Comment by clamoriniere** [comment]
Hi @anhkhoa45 

Did you succeed to configure logs collection as you want? 
Can we close this issue?

**Comment by anhkhoa45** [comment]
@clamoriniere I'll close this issue. Thanks for your help.

**Comment by sevetseh28** [comment]
> Hi @anhkhoa45
> 
> If you want more documentation about how to configure granularly the logs collection you can look at our [datadog documentation website](https://docs.datadoghq.com/agent/kubernetes/log/?tab=helm)
> 
> Some pointers in the docs:
> 
> * to exclude/include specific containers/namespaces: the environment variables `DD_CONTAINER_INCLUDE_LOGS` and `DD_CONTAINER_EXCLUDE_LOGS ` can be used  ([doc link](https://docs.datadoghq.com/agent/docker/?tab=standard#ignore-containers))
> * to only collect logs from specific pods, you can deactivate `containerCollectAll: false` add use [pod's auto-discovery pod annotations](https://docs.datadoghq.com/agent/kubernetes/log/?tab=kubernetes#autodiscovery) to specify logs configuration for each pod.
> * to exclude some logs lines, it is possible to configure a [logs filter](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=kubernetes#filter-logs)
> 
> Let us know if you found the information that you need in our doc.

Im trying to use containerIncludeLogs instead of going to my Pod deployment and changing data there. I would like to directly perform the "filtering" in the helm chart values through `containerIncludeLogs` but it's still not working.
Im using: `containerIncludeLogs: "name:<NAME_OF_POD>"` with `containerCollectAll: false`

**Comment by cristianrat** [comment]
same issue for me. I'm sure I'm doing something wrong, but the docs are not straight forward as far as I can tell

**Comment by solexmb** [comment]
Is there a fix or workaround for this yet?

**Comment by evisdrenova** [comment]
^^anything on this? trying to do the same thing

**Comment by solexmb** [comment]
@evisdrenova  you need to use 
containerExcludeLogs: 
containerIncludeLogs:

**Comment by evisdrenova** [comment]
And that works without having to update the pod deployments? As OP said: "Im trying to use containerIncludeLogs instead of going to my Pod deployment and putting the annotations there. I would like to directly perform the "filtering" in the helm chart values through containerIncludeLogs but it's still not working."

**Comment by solexmb** [comment]
It worked for me. I did mine in my override values.yml file.
You can exclude all containers image with a widecard and include only the container image you want to collect logs from.
Example:
containerExcludeLogs: "image:.*"
containerIncludeLogs: "name:nginx-app"

Where nginx-app is the name of the allowed container image

**Comment by RamBNarayanan** [comment]
@solexmb 

Do I need to do this after setting `containerCollectAll: false` or do i need to set that to true?

**Comment by oshmyrko** [comment]
@RamBNarayanan, you need to enable `containerCollectAll`and then exclude all containers and include only wanted ones, e.g.:
```
datadog:
  logs:
    enabled: true
    containerCollectAll: true

  # https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagent
  containerExcludeLogs: image:.*
  containerIncludeLogs: image:.*my-image-name-without-prefix
```

Otherwise, you would need to use [pod's auto-discovery pod annotations](https://docs.datadoghq.com/containers/kubernetes/log/?tab=daemonset#autodiscovery).

**Comment by MatheusMorozetti** [comment]
Can I filter containerLogs with labels? or just images ?

**Comment by suberjin** [comment]
> Can I filter containerLogs with labels? or just images ?

you can use a 'name', like containerIncludeLogs: "name:my-best-container". I even use namespaces like 
`containerIncludeLogs: "kube_namespace:dev". `

**Comment by guitarboyjr** [comment]
This worked for me with 2 namespaces separated by space char  
```
logs:
    enabled: true
    containerCollectAll: true
  containerIncludeLogs: kube_namespace:istio-.* kube_namespace:dev-.* 
  containerExcludeLogs: kube_namespace:.*
```

**Comment by MVV90** [comment]
I got this to work. The indentation is confusing, because `containerExcludeLogs` is not under `logs`. It is `datadog.containerExcludeLogs` and not `datadog.logs.containerExcludeLogs`.

The format of the `containerExcludeLogs` is also prefixed with `kube_namespace:` regardless of which namespace you are filtering.

Working example, that filters the entire `datadog` namespace pods, and all `kube-` namespace (like `kube-system`),
and includes namespaces such as `production` and `dev`:
```
datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: datadoghq.com
  containerExcludeLogs: kube_namespace:datadog.* kube_namespace:kube-.*
  containerIncludeLogs: kube_namespace:production.* kube_namespace:dev.*
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    autoMultiLineDetection: false
```
