### ISSUE TITLE
Can't add DD_APM_MAX_TPS to cluster agent

### ISSUE THREAD

**Issue by arlando** [DataDog/helm-charts#1346]
**Describe what happened:**

I have an ArgoCD environment and I am attempting to pass the parameter to change the `DD_APM_MAX_TPS` setting. But having trouble changing this. What is the correct way to set this?

**Describe what you expected:**

The `envDict` setting applied to the Datadog cluster agent config as per https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/_container-agent.yaml#L188. Note in the version `3.57.3` this is namespaced under `clusterAgent`. 

**Steps to reproduce the issue:**

```
project: foo
source:
  repoURL: 'https://helm.datadoghq.com'
  targetRevision: 3.57.3
  helm:
    parameters:
      - name: clusterAgent.replicas
        value: '2'
      - name: clusterAgent.envDict[0].DD_APM_MAX_TPS
        value: '1'
  chart: datadog
destination:
  server: 'https://kube.svc'
  namespace: datadog
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

**Additional environment details (Operating System, Cloud provider, etc):**

Helm datadog chart

**Comment by tbavelier** [comment]
This setting `DD_APM_MAX_TPS` is used by the trace-agent container of the core Agent pod, not the cluster Agent. You can simply use `datadog.env` : 
```
datadog:
  env:
  - name: DD_APM_MAX_TPS
    value: 1
```

The `envDict` syntax would be : 
```
datadog:
  envDict:
    DD_APM_MAX_TPS: 1
```

If you want to apply env vars to the cluster Agent, they should be passed with `clusterAgent.env` / `clusterAgent.envFrom` / `clusterAgent.envDict` with the same syntax.

So the syntax with ArgoCD / Helm would be `clusterAgent.envDict.DD_APM_MAX_TPS` as `envDict` is a dictionary : 
<img width="1365" alt="image" src="https://github.com/DataDog/helm-charts/assets/97530782/8d1c4303-b98b-4e96-b530-c99dc19969b5">

As mentioned in the beginning, this is a trace-Agent setting however, so it should be passed with `datadog.env`
