### ISSUE TITLE
Relationship between `containerIncludeMetrics` and `prometheusScrape`

### ISSUE THREAD

**Issue by clarkmcc** [DataDog/helm-charts#1371]
I've wasted a few hours on an interesting behavior between two related but distinct settings in the values.yaml file of the datadog agent and I'd like to get clarification on what the relationship is between all these settings from a metrics perspective only. I've spent a ton of time reviewing the docs, and the Helm chart readme, and I'm still not clear.
- `datadog.containerInclude`
- `datadog.containerIncludeMetrics`
- `datadog.prometheusScrape.enabled`
- `datadog.prometheusScrape.additionalConfigs.autodiscovery.kubernetes_container_names`

```yaml
datadog:
  containerInclude: 'name:^app'
  containerIncludeMetrics: 'name:app_1'
  prometheusScrape:
    enabled: true
    additionalConfigs:
      - autodiscovery:
          kubernetes_container_names:
          - app_1
```
