### ISSUE TITLE
Datadog operator EKS Addon - how to get updates?

### ISSUE THREAD

**Issue by kkopachev** [DataDog/helm-charts#1433]
**Describe what happened:**
Installed DataDog operator as EKS Addon and my resource config failed to apply, because CRD in operator is a version from 3 months ago and does not have helmCheck feature defined.

**Describe what you expected:**
More recent version of operator to be available through EKS addon

**Steps to reproduce the issue:**
Install Operator as EKS addon, try to add DatadogAgent like this:
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: something
    registry: public.ecr.aws/datadog
    credentials:
      apiSecret:
        secretName: datadog
        keyName: apiKey
  features:
    helmCheck:
      enabled: true
```
and see it fails:

> Error from server (BadRequest): error when creating "dd.yaml": DatadogAgent in version "v2alpha1" cannot be handled as a DatadogAgent: strict decoding error: unknown field "spec.features.helmCheck"

**Additional environment details (Operating System, Cloud provider, etc):**
AWS/EKS

Looking at the repo, it looks like EKS addon is treated as second-class citizen in it's own branch. Is that not recommended way to install it nowadays? Should I resort to installing via helm chart instead? Just trying to see what to expect going forward.
