### ISSUE TITLE
[DatadogAgent] Allow custom image repository

### ISSUE THREAD

**Issue by starlightromero** [DataDog/helm-charts#1455]
**Describe what happened:**

I set a custom image on the DatadogAgent custom resource:

```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  ...
spec:
  override:
    nodeAgent:
      image:
        name: custom-repo.io/datadoghq/agent
```

This produced the image `gcr.io/datadoghq/custom-repo.io/datadoghq/agent:7.53.0`

**Describe what you expected:**

I expected the image to be `custom-repo.io/datadoghq/agent:7.53.0`. It would be ideal to be able to use a proxy for the images.

**Steps to reproduce the issue:**

See yaml manifest above.

**Additional environment details (Operating System, Cloud provider, etc):**
