### ISSUE TITLE
Gaps in kube-state-metrics reporting when agent-clusterchecks deployment restarts

### ISSUE THREAD

**Issue by kr3cj** [DataDog/helm-charts#1493]
## TL;DR

Improve the [agent-clusterchecks pod-disruption-budget](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/agent-clusterchecks-pdb.yaml) or probes to make its restart behavior less aggressive in hopes of retaining the `kubernetes_state.*` and `kubernetes.*` metric data.

## Impact

Gaps in kubeStateMetrics during agent-clusterchecks restarts can cause false alerts or misleading dashboards due to inaccurate metrics or missing data.

## Background

We run the agent-clusterchecks as a deployment in our EKS clusters (via this official helm chart) and we enable its pod disruption budget. Additionally, to help with resiliency, we spread the deployment across 3 different nodes in 3 different AZs in our AWS environment like so:

```yaml
  datadog:
    kubeStateMetricsCore:
      enabled: true
      useClusterCheckRunners: true

  clusterChecksRunner:
    enabled: true
    # Datadog recommends 2 replicas and a PDB for HA mode
    replicas: 3
    createPodDisruptionBudget: true

    # make sure we don't surge a new Node
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: function
                  operator: In
                  values:
                    - cluster-critical
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                    - datadog-cluster-critical
                - key: "app.kubernetes.io/component"
                  operator: In
                  values:
                    - clusterchecks-agent
            topologyKey: "kubernetes.io/hostname"
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: datadog-cluster-critical
            app.kubernetes.io/component: clusterchecks-agent
        topologyKey: topology.kubernetes.io/zone
        maxSkew: 1
        whenUnsatisfiable: ScheduleAnyway
```

Occasionally, when we we upgrade our kubernetes nodes or just restart the agent-clusterchecks deployment, we notice that the `kubernetes_state.*` and `kubernetes.*` metrics completely disappear for a minute or few. We have correlated this to the restart behavior of the `agent-clusterchecks` deployment. All 3 pods will restart within about a minute or so of each other. Perhaps this doesn't allow enough time to send the metrics back to datadog before being stopped.

```sh
$ kubectl get pdb/datadog-cluster-critical-clusterchecks -ndatadog
NAME                                     MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
datadog-cluster-critical-clusterchecks   N/A             1                 1                     79d
$ kubectl rollout restart -ndatadog deploy/datadog-cluster-critical-clusterchecks
deployment.apps/datadog-cluster-critical-clusterchecks restarted
$ kubectl get po -ndatadog -lapp.kubernetes.io/component=clusterchecks-agent -ojsonpath='{range .items[*]}{@.metadata.name}{" "}{@.metadata.creationTimestamp}{"\n"}{end}' | column -t
datadog-cluster-critical-clusterchecks-6bb6c7bb67-grczn  2024-08-15T20:08:26Z
datadog-cluster-critical-clusterchecks-6bb6c7bb67-vjwr5  2024-08-15T20:07:39Z
datadog-cluster-critical-clusterchecks-6bb6c7bb67-wxt77  2024-08-15T20:07:07Z
```

![UnhealthyDeployment](https://github.com/user-attachments/assets/825494d0-c6b6-49df-b43e-82a39048c1ad)

![Missing_kubernetes_state_metrics](https://github.com/user-attachments/assets/1927e09a-4d7c-471a-856d-f29563610edf)

![Missing_kubernetes_metrics](https://github.com/user-attachments/assets/9d02c99f-cc48-4b1d-b956-a870f3133028)

<details><summary>Not sure if this is related, our agent-clusterchecks configs</summary>

We also run the cluster-agent as a deployment in a similar way with a PDB but only run 2 replicas. But we see less aggressive restart behavior of its pods:

```yaml
  clusterAgent:
    enabled: true
    # Datadog recommends 2 replicas and a PDB for HA mode
    replicas: 2
    createPodDisruptionBudget: true

    # make sure we don't surge a new Node
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: function
                  operator: In
                  values:
                    - cluster-critical
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                    - datadog-cluster-critical
                - key: "app.kubernetes.io/component"
                  operator: In
                  values:
                    - cluster-agent
            topologyKey: "kubernetes.io/hostname"
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: datadog-cluster-critical
            app.kubernetes.io/component: cluster-agent
        topologyKey: topology.kubernetes.io/zone
        maxSkew: 1
        whenUnsatisfiable: ScheduleAnyway

    confd:
      kube_apiserver_metrics.yaml: |-
        # Force this to run in the clusterchecks-agent
        cluster_check: true
        instances:
          - prometheus_url: "https://kubernetes.default.svc.cluster.local:443/metrics"
```

```sh
$ kubectl get pdb/datadog-cluster-critical-cluster-agent -ndatadog
NAME                                     MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
datadog-cluster-critical-cluster-agent   1               N/A               1                     79d
$ kubectl rollout restart -ndatadog deploy/datadog-cluster-critical-cluster-agent
deployment.apps/datadog-cluster-critical-cluster-agent restarted
$ kubectl get po -ndatadog -lapp.kubernetes.io/component=cluster-agent -ojsonpath='{range .items[*]}{@.metadata.name}{" "}{@.metadata.creationTimestamp}{"\n"}{end}' | column -t
datadog-cluster-critical-cluster-agent-555f965d8c-jt5fr  2024-08-15T20:12:02Z
datadog-cluster-critical-cluster-agent-555f965d8c-mnwbq  2024-08-15T20:11:32Z
```

You can see that in the [cluster-agent PDB](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/cluster-agent-pdb.yaml), it has `minAvailable: 1` instead of the `maxUnavailable: 1` that the [agent-clusterchecks pod-disruption-budget](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/agent-clusterchecks-pdb.yaml) has. Not sure if this is the root cause or not.

</details>

We would expect that the agent-clusterchecks PDB ensure that metrics aren't lost during a restart of its deployment. Or at least minimize the chance of them being lost.

## Troubleshooting

I tried increasing the agent-clustercheck deployment's `startupProbe.initialDelaySeconds` from `15` to `90` to stagger the startup times, but was still able to reproduce the same problem.
