### ISSUE TITLE
Install integration on-the-fly with `agents.containers.initContainers.volumeMounts`

### ISSUE THREAD

**Issue by francoishornoy** [DataDog/helm-charts#1571]
Hi,

Like [this issue](https://github.com/DataDog/helm-charts/issues/1149) (amongst others), we would like to install an integration on the fly instead of having to build and maintain our own image.

We have tried to leverage the `initContainers.volumeMounts` (https://github.com/DataDog/helm-charts/pull/1183) feature by mounting a script into `/etc/cont-init.d` and we can see it's being mounted properly in the `init-config` initContainer and we can confirm in the logs that the integration (`redpanda` FYR) gets downloaded and installed properly.

![Image](https://github.com/user-attachments/assets/18edaaf3-1c86-4dd6-87aa-55a7edbdb0aa)

But I think the issue is that it gets installed in a folder that is not mounted in a volume (`/opt/datadog-agent/embedded/lib/python3.11/site-packages/datadog_checks/`) so the installation is not visible to the main `agent` container. I can confirm by opening a shell on the `agent` container that the redpanda python files are not there.

I think we can manage by using volumes for the above `/opt/datadog-agent/` folder and ensure it's mounted onto the `agent` container, but it requires some knowledge of which folders the `agent integration install` command amends, so not ideal imho.

Is there a simpler solution using `initContainers.volumeMounts` to achieve this?

Regards

For reference, the `agents.containers.initContainers.volumeMounts` and `agents.volumes` look like this:
```
      volumeMounts:
        - name: cont-init-volume
          mountPath: /etc/cont-init.d/install-redpanda-integration.sh
          subPath: install-redpanda-integration.sh

  # agents.volumes -- Specify additional volumes to mount in the dd-agent container
  volumes:
  - name: cont-init-volume
    configMap:
      name: cont-init-configmap
```

And the configMap with the integration installation script:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cont-init-configmap
  namespace: datadog
data:
  install-redpanda-integration.sh: |
    #!/bin/bash
    agent integration install -r -t datadog-redpanda==2.0.0   
```
