### ISSUE TITLE
Unable to Disable APM via the Helm Chart

### ISSUE THREAD

**Issue by hamishdh** [DataDog/helm-charts#1599]
**Describe what happened:**

I am unable to disable APM trace collection via the Helm chart. I had initially enabled it by setting the below config:

```yaml
    datadog:
      apm:
        socketEnabled: true
        portEnabled: true
```

To disable it, I have tried setting the below values:

```yaml
    datadog:
      apm:
        socketEnabled: false
        portEnabled: false
```

The Helm release deploys, however APM traces are still being collected. A 'trace-agent' container is still being created in the DataDog DaemonSet and it has the environment variable: `DD_APM_ENABLED=true`.

The 'agent' / 'process-agent' containers correctly have the environment variable `DD_APM_ENABLED=false`.

Also interestingly, I enabled debug logging by setting `datadog.logLevel: 'DEBUG"` and I observer that the `DD_LOG_LEVEL` environment variable was correctly updated on the 'agent' and 'process-agent' containers, however *not* the 'trace-agent' container.

**Describe what you expected:**

- 'trace-agent' container to be removed from the DaemonSet

**Steps to reproduce the issue:**

1. Enable APM by setting `datadog.apm.socketEnabled: true` & `datadog.apm.portEnabled: true`.
2. Attempt to disable APM by setting datadog.apm.socketEnabled: false` & `datadog.apm.portEnabled: false`.

**Additional environment details (Operating System, Cloud provider, etc):**

- Using `3.7.6` version of Helm Chart
- Running in AWS EKS
- Using FluxCD for Helm deployments

**Comment by celenechang** [comment]
Hi @hamishdh , thanks for opening the issue. I was unable to reproduce what you experienced; do you happen to have anything else set in your values.yaml file under `datadog.apm`?

(From Git history, I don't think Helm chart version would affect this, but it may be worth trying an updated version.)

In my test values.yaml file, toggling `apm.socketEnabled` was sufficient to add/remove the trace agent to/from the pod:

```
datadog:
  apiKey: [redacted]
  appKey: [redacted]

  apm:
    socketEnabled: false # true
```

On the latest chart version, the logic deciding whether the trace agent should be included is [here](https://github.com/DataDog/helm-charts/blob/3df0db954ccc9069057d7475151ad513072b8701/charts/datadog/templates/_helpers.tpl#L470-L471). The only element that is true by default is `datadog.apm.socketEnabled`.

I hope that helps - please let me know if I missed anything.
