### ISSUE TITLE
Enabling the creation of networkPolicy in the helm charts causes networking (DNS) issues for datadog-clusterchecks.

### ISSUE THREAD

**Issue by Vassilis0** [DataDog/helm-charts#1606]
**Describe what happened:**
Enabling the creation of networkPolicy in the helm [charts](https://github.com/DataDog/helm-charts/blob/af0e75fad9327b30064a244061550f64ad2b986d/charts/datadog/values.yaml#L908) causes networking (DNS) issues for the datadog-clusterchecks because the policy created does not allow egress traffic on port 53 .

```
Spec:
  PodSelector:     app=datadog-clusterchecks
  Allowing ingress traffic:
    ‹none> (Selected pods are isolated for ingress connectivity)
  Allowing egress traffic:
    To Port: 443/TCP
    To: <any> (traffic not restricted by destination)
     ------------
    To Port: 5005/TCP
    To:
        PodSelector: app=datadog-cluster-agent
    ------------
    To Port: <any> (traffic allowed to all ports)
    To: <any> (traffic not restricted by destination)
Policy Types: Ingress, Egress
```

More specifically the errors in datadog-clusterchecks for the endpoinds

```
• https://api.datadoghq.com/api/v1/check_run
• https://api.datadoghq.com/api/v2/series
```

```
2024-11-04 16:21:09 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/worker.go:187 in process) | Too many errors for endpoint 'https://7-58-0-app.agent.datadoghq.com/api/v1/check_run': retrying later

2024-11-04 16:21:09 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/worker.go:187 in process) | Too many errors for endpoint 'https://7-58-0-app.agent.datadoghq.com/api/v2/series': retrying later

2024-11-08 14:00:46 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/worker.go:191 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://7-58-0-app.agent.datadoghq.com/intake/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2024-11-06 15:28:47 UTC | CORE | DEBUG | (comp/forwarder/defaultforwarder/transaction/transaction.go:87 in 1) | DNS Lookup failure: lookup 7-58-0-app.agent.datadoghq.com: i/o timeout
```

**Steps to reproduce the issue:**
Enable the creation of networkPolicy in charts for a datadog deployment that runs in AWS EKS with the [network policy](https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy.html) enabled
```
kubectl get networkpolicy 
kubectl describe networkpolicy <networkpolicy-name>
```

check for name resolution from within the datadog-clusterchecks pod

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS 1.30
Datadog Helm chart: 3.77

**Comment by celenechang** [comment]
Hi @Vassilis0 , thanks for opening the issue and for providing those details. Did adding an egress rule on port 53 help resolve the DNS error?

Do you mind opening a [support ticket](https://www.datadoghq.com/support/) so that our team can investigate further? Thank you in advance.

**Comment by Vassilis0** [comment]
Thank you for your reply @celenechang 
Yes, adding egress rule on port 53 help resolve the DNS error but we end up disabling the creation of the Network policy.

Support ticket:  [#1970318](https://help.datadoghq.com/hc/requests/1970318)

**Comment by simonpetty** [comment]
I too raised a support ticket for this (2230565), context being this was on EKS with VPC-CNI being used to enforce network policies. We were advised:

> At present, with VPC-CNI enabled, you do need to define these policies yourself. The Helm chart does not yet ship with a comprehensive VPC-CNI–aware policy set.

I suspect it may relate to this: https://github.com/aws/amazon-network-policy-controller-k8s/issues/146

In case it helps, below are the basic network policies - we had to add others for auto-discovery:
```
# Minimum egress policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: datadog-egress-core
  namespace: datadog
spec:
  podSelector:
    matchLabels:
      app: datadog
  policyTypes: [Egress]
  egress:
    # Agent -> DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 9153 # metrics endpoint
    # Agent -> Cluster Agent
    - to:
        - podSelector:
            matchLabels:
              app: datadog-cluster-agent
      ports:
        - protocol: TCP
          port: 5000 # metrics endpoint
        - protocol: TCP
          port: 5005 # comms
    # Agent -> kube-API
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default  
      ports:
        - protocol: TCP
          port: 443
    # Agent -> kubelet on node IPs (10250). With VPC-CNI NP you usually need a CIDR to node IPs.
    - to:
        - ipBlock:
            cidr: <cidr>/16
      ports:
        - protocol: TCP
          port: 10250
    # Agent -> DataDog intake (FQDNs aren’t supported by NetworkPolicy)
    - to:
        - ipBlock:
            cidr: <redacted>   # route via an egress GW/NAT SG and allow only that CIDR?
      ports:
        - protocol: TCP
          port: 443
    # Agent -> AWS Time Sync Service
    - to:
        - ipBlock:
            cidr: 169.254.169.123/32
      ports:
        - protocol: UDP
          port: 123
    
---
# Allow ingress from all pods to dogstatsd port
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: datadog-ingress
  namespace: datadog
spec:
  podSelector:
    matchLabels:
      app: datadog
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector: <redacted>
      ports:
        - protocol: UDP
          port: 8125 # DogStatsD
        - protocol: TCP
          port: 8126 # APM Traces
```
