### ISSUE TITLE
maxAge setting in DatadogMetric not working

### ISSUE THREAD

**Issue by asierraq** [DataDog/helm-charts#1607]
I have a DatadogMetric manifest like the following:
```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: metric
spec:
  query: ...
```
When I apply it and use it in an HPA, I get the following error:
```
Query returned outdated result, check MaxAge setting, query: ...
```
Then I added the `maxAge: "300"` setting (to my surprise it is a string setting and not an integer) and now I'm not getting any events in the DatadogMetric.

Do you know what could be wrong with this setting?
