### ISSUE TITLE
Cluster Agent Error on CWS Instrumentation webhook when upgrading release with CWS disabled

### ISSUE THREAD

**Issue by bkonicek-calm** [DataDog/helm-charts#1613]
We recently upgraded our datadog helm chart version, and I noticed in the logs the following error

```
datadog-cluster-agent-846448567c-dzggf cluster-agent 2024-11-25 18:37:30 UTC | CLUSTER | ERROR | (pkg/clusteragent/admission/controllers/webhook/controller_base.go:130 in generateWebhooks) | failed to register CWS Instrumentation webhook: can't initialize CWS Instrumentation in remote_copy mode without providing a service account name in config (cluster_agent.service_account_name)
```

We upgraded to chart version `3.80.0` (agent version `7.59.0`)

Our values includes the following, so I'm not sure why it's trying to register a CWS webhook.
```
datadog:
  securityAgent:
    runtime:
      enabled: false
      fimEnabled: false
      useSecruntimeTrack: false
      securityProfile:
        enabled: false
        anomalyDetection:
          enabled: false
        autoSuppression:
          enabled: false
```

Everything seems to be working properly, other than this error.
