### ISSUE TITLE
Setting kubernetesResourcesLabelsAsTags brakes helm templating since 3.73.1

### ISSUE THREAD

**Issue by alexstojda** [DataDog/helm-charts#1631]
Since agent chart version `3.73.1` helm templating fails when setting `datadog.kubernetesResourcesLabelsAsTags`.

Pretty sure the issue stems from this commit https://github.com/DataDog/helm-charts/commit/080279926bbcfa9d387d843e10da26741362811c by @gabedos

## How to reproduce

Run `helm template datadog datadog/datadog` with values: 

```yaml
datadog:
  kubernetesResourcesLabelsAsTags:
    '*': 'kube_%%label%%'
    'labels.mycompany.com/foo': 'bar'
```

You should get an error:
```
Error: YAML parse error on datadog/templates/cluster-agent-rbac.yaml: error converting YAML to JSON: yaml: line 19: did not find expected alphabetic or numeric character
```
