### ISSUE TITLE
Unable to connect to Azure Database for PostgreSQL - Flexible Server via managed identity

### ISSUE THREAD

**Issue by yoon-chi** [DataDog/helm-charts#1663]
Deployed with helm chart version: `3.20.3`
Cluster Agent: 7.43.1

The cluster agent is unable to access the database using workload identity in Azure Kubernetes service (AKS) despite following the setup steps outlined in:

[PostgreSQL 16 setup](https://docs.datadoghq.com/database_monitoring/setup_postgres/azure/?tab=postgres16)

[Managed Authentication in Azure
](https://docs.datadoghq.com/database_monitoring/guide/managed_authentication/?tab=rds)
- Registered a managed identity `staging-datadog` in Azure AD
- Enabled workload identity in an AKS cluster and created federated credential to associate the AKS OIDC endpoint with the managed identity 
- Annotated the cluster-agent service account with client id of the managed identity and labeled cluster agent pods based on [documentation](https://docs.datadoghq.com/database_monitoring/guide/managed_authentication/?tab=rds)
- Created the datadog role `staging-datadog` in the database. The `staging-datadog` role gets created as Microsoft Entra admin. 
- [Configured Postgres >= 16 ](https://docs.datadoghq.com/database_monitoring/setup_postgres/azure/?tab=singleserver) and ensured the role is granted the necessary privileges on the datadog schema and other schemas.

Note: 
-  Metrics show up in Datadog when I switch to password-based auth on the same database
- There are no errors that show in the cluster agent pod's logs that indicate there is a problem with authentication

In datadog-values.yaml 
```
clusterAgent:
  enabled: true
  metricsProvider:
    enabled: false
  replicas: 1
  createPodDisruptionBudget: true
  podLabels:
    azure.workload.identity/use: "true"  
  rbac:
    serviceAccountAnnotations:
      azure.workload.identity/client-id: "<client-id>"
      azure.workload.identity/tenant-id: "<tenant-id>"
  confd:
  # https://github.com/DataDog/integrations-core/blob/master/postgres/datadog_checks/postgres/data/conf.yaml.example
    postgres.yaml: |
      cluster_check: true
      init_config:
      instances:
        - dbm: true
          host: '<fqdn>'
          port: 5432
          username: 'staging-datadog'
          ssl: 'require'
          dbname: '<dbname>'
          tags:
            - 'env: sandbox'
            - 'team: devops'
            - 'service: <app>'
          relations:
            - relation_regex: .*
              relkind:
              - r
              - i
              - S
              - m
              - f
              - p
          collect_activity_metrics: true
          collect_bloat_metrics: true       
          collect_schemas:
            enabled: true
            include_schemas:
              - <app>
            include_tables:
              - <app>.*
          azure:
            deployment_type: flexible_server
            fully_qualified_domain_name: "<fqdn>"
            managed_authentication:
                enabled: true
                client_id: "<client-id>"
                tenant_id: "<tenant-id>"
                identity_scope: "https://ossrdbms-aad.database.windows.net/.default"
```
