### ISSUE TITLE
Autodiscovery of postgres databases?

### ISSUE THREAD

**Issue by justinmchase** [DataDog/helm-charts#1670]
We have multiple postgres databases and there isn't necessarily a good way to know them all up front in such a way that we can hard code them into the `datadog.confd` values.

Ideally there would be a CustomResourceDefinition for us to create configuration for a database instance that way each namespace could report its own database configuration as it is created.

Is such a thing possible now? Are there any other mechanisms for database auto discovery?

```yaml
apiVersion: datadog.com/v1
kind: PostgresMonitor
metadata:
  name: test-app
spec:
  instance:
    host: example.com
    username: example
    password: example
```
