### ISSUE TITLE
dnsConfig templating doesn't seem right

### ISSUE THREAD

**Issue by dghubble** [DataDog/helm-charts#1672]
Something seems wrong with the templating for `dnsConfig`. Possibly some indentation detail. Does this work for anyone else? Better ways to strict template to catch indent or render issues?

```
helm repo add datadog https://helm.datadoghq.com
helm repo update
helm template datadog-agent datadog/datadog \
  --version=3.88.1 \
  --values values.yaml \
  > manifests.yaml
```

```
# values.yaml
datadog:
  apiKeyExistingSecret: "datadog-secret"
  agents:
    enabled: true
    dnsConfig:
      options:
        - name: ndots
          value: "1"
```

```
grep dnsConfig manifests.yaml    # nothing?
grep dnsPolicy manifests.yaml  # huh? this doesn't match what's in this repo
```

https://github.com/DataDog/helm-charts/blob/v3.88.1/charts/datadog/templates/daemonset.yaml#L104

**Comment by levan-m** [comment]
Hello @dghubble, `agents` isn't under `datadog`. Please try using:
```yaml
datadog:
  apiKeyExistingSecret: "datadog-secret"
agents:
  enabled: true
  dnsConfig:
    options:
      - name: ndots
        value: "1"
``` 
```sh
❯ grep dnsConfig -A 5  manifests.yaml
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      hostPID: true
      containers:
```
