### ISSUE TITLE
Setting datadog.logLevel to DEBUG removes the DD_LOG_LEVEL env variable

### ISSUE THREAD

**Issue by jebbench** [DataDog/helm-charts#168]
**Describe what happened:**
Setting `datadog.logLevel` to DEBUG removed the `DD_LOG_LEVEL` env variable

**Describe what you expected:**
For DD_LOG_LEVEL to be set to DEBUG

**Steps to reproduce the issue:**
Using chart version 2.8.5 and the values:

```
datadog:
  apiKeyExistingSecret: ${kubernetes_secret.datadog_secret.metadata.0.name}
  appKeyExistingSecret: ${kubernetes_secret.datadog_secret.metadata.0.name}
  site: datadoghq.eu
  logLevel: DEBUG
  env:
    - name: DD_CONTAINER_EXCLUDE
      value: |-
        kube_namespace:kube-system
        kube_namespace:datadog
  kubeStateMetricsEnabled: true
  clusterChecks:
    enabled: true
  collectEvents: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  orchestratorExplorer:
    enabled: true
    container_scrubbing:
      enabled: false
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true
clusterAgent:
  enabled: true
  token: ${random_password.datadog_cluster_agent_token.result}
```

Produces a deamon set without any reference to DD_LOG_LEVEL.

**Additional environment details (Operating System, Cloud provider, etc):**
Deploying to GKE using Terraform.
