### ISSUE TITLE
datadog-agent redeployed without changes

### ISSUE THREAD

**Issue by tobias-zeptio** [DataDog/helm-charts#169]
**Describe what happened:**
If I do `helm upgrade` without changes, the datadog-agent pods are restarted.

**Describe what you expected:**
Nothing should change in the cluster, if nothing has changed in the deployment.

**Steps to reproduce the issue:**
helm install
helm upgrade

**Additional environment details (Operating System, Cloud provider, etc):**
linux
EKS
k8s 1.19.6
datadog chart 2.8.5

These are the commands run:
```
helm upgrade -n extension -f $app/values.yaml $app $chart \
    --set datadog.clusterName=cluster-$DEPLOY_ENV 
```
with values.yaml:
```
datadog:
  apiKey: <>

  logs:
    enabled: true
    containerCollectAll: true

  env:
    - name: DD_CONTAINER_EXCLUDE_LOGS
      value: "image:gcr.io/datadoghq/agent"
```
