### ISSUE TITLE
Private Action Runners do not allow passing the URN and the Private key as secrets

### ISSUE THREAD

**Issue by ritaCanavarro** [DataDog/helm-charts#1711]
I am trying to use the Private action runners helm charts locally for a PoC of a Datadog workflow that restarts a deployment based on a certain type of monitor and found out that we can only pass the URN and the Private key obtained from Docker config as "normal" uncoded values.

This, in my view, seems to be a bit insecure and I would like to pass these values from a k8s secret, that in its turn reads the values from Vault.

Is there any plan to support passing these two values as base64 encoded k8s secrets and then have the global [secret](https://github.com/DataDog/helm-charts/blob/ee00f3b63ff415027bb1794c988d0d48f8a50679/charts/private-action-runner/templates/secrets.yaml#L9) decoded them when it reads them?

**Comment by chrissav** [comment]
I'm also pulling our Kubernetes secrets from vault and was trying to do the same. In my case I'm using External Secrets and was able to work around this by merging the secret into the one that gets created
```
kind: ExternalSecret
metadata:
  name: private-action-runner-gitlab-secrets
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: private-action-runner-gitlab-secrets # Secret created by Helm Chart
    creationPolicy: 'Merge' # Merge to overwrite secrets from vault
    template:
      engineVersion: v2
      data:
        gitlab_creds.json: "{{ .gitlab_creds | b64dec }}"
        config.yaml: "{{ .config | b64dec }}"
  data:
  - secretKey: gitlab_creds
    remoteRef:
      key: kv/path/to/secret
      property: gitlab_creds.json
  - secretKey: config
    remoteRef:
      key: kv/path/to/secret
      property: config.yaml
```

If passing in a secret is supported that would still be helpful as this work around can cause a conflict if I update the helm chart
