### ISSUE TITLE
Templating error on version > 3.106.1 with Autopilot enabled

### ISSUE THREAD

**Issue by wyardley** [DataDog/helm-charts#1859]
I'm geting a rendering error in some validation / CI checks when trying to update from chart version `3.88.2` to `3.111.1`. It seems like this error comes up starting in v 3.106.1, so probably related to #1260?

I verified that removing this section seems to resolve the templating error:
```yaml
providers:
  gke:
    autopilot: true
```

Simple / minimized repro case:
```yaml
datadog:
  apm:
    enabled: false
    portEnabled: false
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true
  podLabelsAsTags:
    app.kubernetes.io/instance: kube_instance
  clusterChecks:
    enabled: true
  kubeStateMetricsCore:
    enabled: true
    useClusterCheckRunners: true

providers:
  gke:
    autopilot: true

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: false
  admissionController:
    enabled: true
    configMode: service

clusterChecksRunner:
  enabled: true
```

```
% helm template --repo https://helm.datadoghq.com datadog --version 3.107.0 --values tools/values/datadog/values-xyz.yaml
Error: YAML parse error on datadog/templates/agent-clusterchecks-deployment.yaml: error converting YAML to JSON: yaml: line 155: did not find expected key

Use --debug flag to render out invalid YAML
% helm template --repo https://helm.datadoghq.com datadog --version 3.111.0 --values tools/values/datadog/values-xyz.yaml
Error: YAML parse error on datadog/templates/agent-clusterchecks-deployment.yaml: error converting YAML to JSON: yaml: line 157: did not find expected key

Use --debug flag to render out invalid YAML
```

Full error with `--debug`:
```
Error: YAML parse error on datadog/templates/agent-clusterchecks-deployment.yaml: error converting YAML to JSON: yaml: line 157: did not find expected key
helm.go:86: 2025-05-07 10:14:39.794281 -0700 PDT m=+0.960563751 [debug] error converting YAML to JSON: yaml: line 157: did not find expected key
YAML parse error on datadog/templates/agent-clusterchecks-deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:144
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:104
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:168
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:316
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:316
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:95
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
	runtime/proc.go:272
runtime.goexit
	runtime/asm_arm64.s:1223
```
