### ISSUE TITLE
Postgres DB Monitoring

### ISSUE THREAD

**Issue by haydenai-rahul-jain** [DataDog/helm-charts#1862]
Hi team,
I am following the instructions here: https://docs.datadoghq.com/database_monitoring/setup_postgres/aurora/?tab=kubernetes#install-and-configure-the-agent + https://docs.datadoghq.com/database_monitoring/guide/aurora_autodiscovery/?tab=postgres

Currently, 
to deploy the datadog cluster agent, we use the terraform `helm_release` resource. 
Currently I have these values set up:
```
name = clusterAgent.confd.conf_aws_aurora\\.yaml` 
value = yamlencode({
      ad_identifiers = ["_dbm_postgres_aurora"]
      init_config = null
      instances = [{
        host = "%%host%%"
        port = "%%port%%"
        username = "datadog"
        password = "${aws_ssm_parameter.datadog_agent_db_password.value}"
        database_autodiscovery = {
          enabled = true
        }
        relations = [{
          relation_regex = ".*"
        }]
        collect_schemas = {
          enabled = true
        }
        dbm = true
        aws = {
          instance_endpoint = "%%host%%"
          region = "%%extra_region%%"
        }
        tags = [
          "dbclusteridentifier:%%extra_dbclusteridentifier%%",
          "region:%%extra_region%%"
        ]
      }]
    })
```
```
as well as :
 set {
    name = "clusterAgent.datadog_cluster_yaml.database_monitoring.autodiscovery.aurora.enabled"
    value = true
  }
```

and 

```
 set {
    name = "clusterChecksRunner.enabled"
    value = "true"
  }
```

The terraform deploys successfully, but the agent status doesn't show the postgres integration. The datadog agent does have IAM role access. 

I am able to SSH into the cluster agent pod and I see that under conf.d,I see my file so its properly there. Just not sure where to go from here.

**Comment by fanny-jiang** [comment]
Hi @haydenai-rahul-jain, thank you for reporting this. In order to investigate this further, can you please open a [support ticket](https://docs.datadoghq.com/help/) referencing this github issue? Please submit an [agent flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agent) with your ticket, and one of our agents will dig in and get back to your shortly. Thanks!

**Comment by haydenai-rahul-jain** [comment]
Should the autodiscovery of DB instance go into clusterAgent: or agent:? If so, does it go under clusterAgent.confd, clusterAgent.advancedConfd, or datadog.confd


- Depends on if you are using the datadog cluster agent for kubernetes or just the normal datadog agent! Most likely it would be under clusterAgent as under agent would give each agent monitoring access which is redundant.
If you are doing conf_aws_aurora.yaml, it should go underneath advancedconfd under the folder "postgres.D/conf_aws_aurora.yaml" or you could use the file path "postgres.yaml" under confd. Either work. Advancedconfd just allows you to specify the directory (IE: Postgres.D) too.


What's the integration name for the yaml file that we should input? The doc states that we should create postgres.d/conf_aws_aurora.yaml, but how do we input this into Helm?

Under advancedconfd, just specify this as the path. You can also use confd option, just use the name "postgres.yaml" as the integration name for the yaml file if you use this option.


How do we add a custom role with permissions to read the db clusters? 

Wherever your datadog agent is running, you need to give that place access to db clusters via a IAM role. You can make a service account for the datadog agent via IAM/IRSA, and then use the service account field under the rbac field option in helm to specify it. 

And do we add it to agent, clusterAgent, or clusterAgentCheck?

You'd add it to the cluster agent, that's the one doing the checks on the databases. 
Where are the logs?
Wherever your agent is running. For example if it's running in k8s, it should be in the logs of the pod that is running the datadog clusterAgent and the datadog clusterchecks

**Comment by duelyy** [comment]
@haydenai-rahul-jain Thank you for replying! I'm still having trouble with autodiscovery...

```
root@datadog-agent-cluster-agent-5db6cf4d6f-45pgc:/# agent clusterchecks
=== 2 agents reporting ===

Name                                           Running checks
datadog-agent-clusterchecks-7f986d8fb4-2k5fp   0
datadog-agent-clusterchecks-7f986d8fb4-s9sns   0

===== 0 Pod-backed Endpoints-Checks scheduled =====
```

Does the below Helm value look valid? Not sure what's missing.
```
clusterAgent:
  confd:
    postgres.yaml: |-
      ad_identifiers:
        - _dbm_postgres_aurora
      cluster_check: true
      init_config:
      instances:
      - host: "%host%"
        port: "%port%"
        username: datadog
        password: 'ENC[k8s_secret@datadog/dbm-password/dbm_password]'
        dbm: true
        aws:
          instance_endpoint: "%host%"
          region: "%extra_region%"
        tags:
        - "dbclusteridentifier:%extra_dbclusteridentifier%"
        - "region:%extra_region%"
  rbac:
    create: true
    dedicated: true
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::REDACTED:role/eks-cluster-datadogdbm-sa
    serviceAccountName: datadogdbm-sa

clusterChecksRunner:
  enabled: true

database_monitoring:
  autodiscovery:
    aurora:
      enabled: true
```

**Comment by duelyy** [comment]
I've also tried adding rbac to `clusterChecksRunner`, but same results. The doc below says to add rbac to the clusterChecksRunner to monitor AWS managed services..

```
clusterChecksRunner:
  enabled: true
  rbac:
    create: false
    serviceAccountName: datadogdbm-sa

database_monitoring:
  autodiscovery:
    aurora:
      enabled: true
```

https://docs.datadoghq.com/containers/cluster_agent/setup/?tab=helm#monitoring-aws-managed-services

**Comment by duelyy** [comment]
We finally got it working! We were missing this value `ec2_prefer_imdsv2: true`

Below is our working config:

```
clusterAgent:
  confd:
    postgres.yaml: |-
      ad_identifiers:
        - _dbm_postgres_aurora
      cluster_check: true
      init_config:
      instances:
      - host: "%host%"
        port: "%port%"
        username: datadog
        password: 'ENC[k8s_secret@datadog/dbm-password/dbm_password]'
        dbm: true
        aws:
          instance_endpoint: "%host%"
          region: "%extra_region%"
        tags:
        - "dbclusteridentifier:%extra_dbclusteridentifier%"
        - "region:%extra_region%"
  rbac:
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::REDACTED:role/eks-cluster-datadogdbm-sa

  datadog_cluster_yaml:
    database_monitoring:
      autodiscovery:
        aurora:
          enabled: true
    ec2_prefer_imdsv2: true

clusterChecksRunner:
  enabled: true
```
