### ISSUE TITLE
datadog release cannot be upgraded on GKE Autopilot

### ISSUE THREAD

**Issue by Ventilateur** [DataDog/helm-charts#1864]
Hello, I'm deploying datadog with Helm chart on GKE Autopilot. The first helm install went well, but as soon as I do an upgrade, the `datadog-agent` DaemonSet got stuck with the following error:

```json
{
  "denied by autogke-no-write-mode-hostpath": [
    "hostPath volume 'runtimesocketdir' used in container 'trace-agent' uses path '/var/run/containerd' which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].",
    "hostPath volume 'pointerdir' in container 'agent' is accessed in write mode; disallowed in Autopilot.",
    "hostPath volume 'runtimesocketdir' used in container 'agent' uses path '/var/run/containerd' which is not allowed in Autopilot. Allowed path prefixes: [/var/log/].",
    "hostPath volume 'procdir' used in container 'agent' uses path '/proc' which is not allowed in Autopilot. Allowed path prefixes: [/var/log/].",
    "hostPath volume 'cgroups' used in container 'agent' uses path '/sys/fs/cgroup' which is not allowed in Autopilot. Allowed path prefixes: [/var/log/].",
    "hostPath volume 'passwd' used in container 'agent' uses path '/etc/passwd' which is not allowed in Autopilot. Allowed path prefixes: [/var/log/].",
    "hostPath volume 'logdockercontainerpath' used in container 'agent' uses path '/var/lib/docker/containers' which is not allowed in Autopilot. Allowed path prefixes: [/var/log/].",
    "hostPath volume 'procdir' used in container 'init-config' uses path '/proc' which is not allowed in Autopilot. Allowed path prefixes: [/var/log/].",
    "hostPath volume 'runtimesocketdir' used in container 'init-config' uses path '/var/run/containerd' which is not allowed in Autopilot. Allowed path prefixes: [/var/log/]."
  ]
}
```

- GKE version: 1.32.2-gke.1182003
- Helm chart version: 3.114.0

My helm values:

```yaml
agents:
  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi

    processAgent:
      enabled: false

    systemProbe:
      enabled: false

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
  rbac: 
    create: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  admissionController:
    enabled: true

providers:
  gke:
    autopilot: true

datadog:
  apiKeyExistingSecret: datadog-keys
  appKeyExistingSecret: datadog-keys
  site: datadoghq.eu

  kubeStateMetricsCore:
    # Provided by GKE metrics
    enabled: false 

  ignoreAutoConfig:
    - cilium

  apm:
    useLocalService: true
  
  logLevel: WARN
  
  logs:
    enabled: true
    containerCollectAll: true

  containerExclude: "kube_namespace:^kube-.* kube_namespace:^gke-.*"

  prometheusScrape:
    enabled: true

  # Not supported in Autopilot yet
  # https://docs.datadoghq.com/universal_service_monitoring/setup/?tab=helm#supported-versions-and-compatibility
  serviceMonitoring:
    enabled: false

  kubelet:
    tlsVerify: false
    useApiServer: true
```

How to reproduce:
- Install datadog agents with the values above
- Change trace-agent cpu request/limit then re-apply

**Comment by Ventilateur** [comment]
Thanks for your reply. Unfortunately by setting `cloud.google.com/matching-allowlist: datadog-datadog-daemonset-exemption-v1.0.1` I encountered a different error (sorry for the pipes, I copied from k9s):

```
| =======================================================================                                                                                                                                    │
│ Workload Mismatches Found for Allowlist (datadog-datadog-daemonset-exemption-v1.0.1):                                                                                                                      │
│ =======================================================================                                                                                                                                    │
│ Container[0] (init-volume):                                                                                                                                                                                │
│ - Envs:                                                                                                                                                                                                    │
│            - env[0] Mismatch: 'DD_ENV' has no matching string or regex pattern in allowlist.                                                                                                               │
│            - env[1] Mismatch: 'DD_SERVICE' has no matching string or regex pattern in allowlist.                                                                                                           │
│            - env[2] Mismatch: 'DD_INTERNAL_POD_UID' has no matching string or regex pattern in allowlist.                                                                                                  │
│            - env[3] Mismatch: 'DD_EXTERNAL_ENV' has no matching string or regex pattern in allowlist.                                                                                                      │
│            - env[4] Mismatch: 'DD_ENTITY_ID' has no matching string or regex pattern in allowlist.                                                                                                         │
│            - env[5] Mismatch: 'DD_AGENT_HOST' has no matching string or regex pattern in allowlist.     
```

This is kinda weird because when I do `kubectl get workloadallowlist datadog-datadog-daemonset-exemption-v1.0.1 -oyaml` I see `name: ^DD_.*$`, I suppose they should be allowed.

**Comment by Ventilateur** [comment]
I will try upgrading my cluster to `v1.32.3-gke.1785003` similar to you. This issue did not happen before, so it's possible that it's the gke version.

**Comment by Ventilateur** [comment]
Ok I think I found the culprit. Sorry, my original value file is not complete, it should have these additional labels as well. When I add them, the issue arises.

```
agent:
  additionalLabels:
    admission.datadoghq.com/enabled: "true"
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: dd-agent

clusterAgent:
  additionalLabels:
    admission.datadoghq.com/enabled: "true"
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: dd-cluster-agent

```
