### ISSUE TITLE
Exclude/include container log config not honored when datadog.logs.containerCollectUsingFiles = true

### ISSUE THREAD

**Issue by alzabo** [DataDog/helm-charts#191]
**Describe what happened:**
All container logs were sent to Datadog even though DD_CONTAINER_EXCLUDE_LOGS env var was set

**Describe what you expected:**
Subset of logs to be sent to Datadog

**Steps to reproduce the issue:**
```yaml
    values:
      datadog:
        env:
          #
          # Limit logs to only the flux containers
          #
          # There are currently monitors for Datadog that rely on flux logging to DD, so shutting
          # off logs would blind us until the monitors are changed.
          #
          # Docs for overriding log configs per container
          # https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagent
          - name: DD_CONTAINER_INCLUDE_LOGS
            value: image:flux
          - name: DD_CONTAINER_EXCLUDE_LOGS
            value: .*
        logs:
          enabled: true
          containerCollectAll: false
          containerCollectUsingFiles: true
```

**Additional environment details (Operating System, Cloud provider, etc):**
Amazon EKS, version 1.17

Chart version 2.9.1, agent image gcr.io/datadoghq/agent:7.25.0
