### ISSUE TITLE
Cannot use override env with namespaceLabelsAsTags

### ISSUE THREAD

**Issue by ChesterLloyd** [DataDog/helm-charts#1918]
When specifying config in the `spec.global.override.env` section, the `namespaceLabelsAsTags` config stops working. In this case, I no longer see the `environment` tag show up. Removing this override env config resolves the issue.

Example deployment in K8s:
```yaml
---
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: dev-cluster
    site: datadoghq.eu
    logLevel: INFO
    namespaceLabelsAsTags:
      env: environment
  override:
      env:
        - name: DD_CONTAINER_EXCLUDE_LOGS
          value: "name:^thing-1"
        - name: DD_LOGS_CONFIG_PROCESSING_RULES
          value: '[{"type": "exclude_at_match", "name": "exclude_these_logs", "pattern" : ".*things.*"}]'
```

Supplying config in the helm chart does resolve the issue, but I can't see a way of adding the processing rules.

Example with the helm config without the processing rules
```yaml
datadog:
  containerExcludeLogs:
    "name:^thing-1"
```

**Comment by tbavelier** [comment]
Hello @ChesterLloyd ,

To add an override, you need to provide the component name, it cannot be ignored: https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md#override. In your case, you are trying to exclude logs, so the component would be `nodeAgent` (the one responsible to collect logs): https://docs.datadoghq.com/containers/guide/container-discovery-management/?tab=datadogoperator#setting-environment-variables

```yaml
---
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: dev-cluster
    site: datadoghq.eu
    logLevel: INFO
    namespaceLabelsAsTags:
      env: environment
  override:
    nodeAgent:
      env:
        - name: DD_CONTAINER_EXCLUDE_LOGS
          value: "name:^thing-1"
```

I confirmed this worked in my environment.

<img width="1193" alt="Image" src="https://github.com/user-attachments/assets/eded6256-651f-4217-9c94-03aa0e84ce81" />

In any case, you should be using the "superior" `kubernetesResourcesLabelsAsTags` configuration (https://docs.datadoghq.com/containers/kubernetes/tag/?tab=datadogoperator#namespace-labels-as-tags) if you are using at least Agent 7.58+ so these tags are attached to all resources under a given namespace and not only namespace-level resources like ConfigMap:
```yaml
---
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: dev-cluster
    site: datadoghq.eu
    logLevel: INFO
    kubernetesResourcesLabelsAsTags:
      namespaces:
        env: environment
  override:
    nodeAgent:
      env:
        - name: DD_CONTAINER_EXCLUDE_LOGS
          value: "name:^thing-1"
        - name: DD_LOGS_CONFIG_PROCESSING_RULES
          value: '[{"type": "exclude_at_match", "name": "exclude_these_logs", "pattern" : ".*things.*"}]'
```

Could you please try and let us know how it goes ?

**Comment by ChesterLloyd** [comment]
Hi @tbavelier , thank you for getting back to me.

I made a mistake in copying my yaml, I did have the `nodeAgent` key in there already.

I have just tried swapping from:
```yaml
spec:
  # https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md
  global:
    clusterName: dev-cluster
    site: datadoghq.eu
    logLevel: INFO
    namespaceLabelsAsTags:
      env: environment
```

to:
```yaml
  global:
    clusterName: dev-cluster
    site: datadoghq.eu
    logLevel: INFO
    kubernetesResourcesLabelsAsTags:
      namespaces:
        env: environment
```

But received this error:
> one or more objects failed to apply, reason: failed to create typed patch object (datadog/datadog; datadoghq.com/v2alpha1, Kind=DatadogAgent): .spec.global.kubernetesResourcesLabelsAsTags: field not declared in schema


We are using these images, and I can see in the Datadog dashboard, the agent info: `field:metadata_agent_version:7.66.1` which is above 7.58 as you recommended
```yaml
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
```

**Comment by ChesterLloyd** [comment]
Moving it to use the method described under the "helm" tab in the docs, it appears to tag the logs like it did before:

```yaml
datadog:
  kubernetesResourcesLabelsAsTags:
    nodes:
      env: environment
```

Now to tag the hosts too
