### ISSUE TITLE
Datadog Agent doesn't start on Talos clusters

### ISSUE THREAD

**Issue by chdeliens** [DataDog/helm-charts#1939]
Hi!

Similar to https://github.com/DataDog/helm-charts/issues/273, I discovered that deploying the Datadog Agent on a Talos cluster is not working as expected.

The agent's DaemonSet is configured to mount several non-existent `hostPath` volumes from Talos' (read-only) filesystem (I believe this is to detect which OS it runs on).

I have found a workaround which consists of manually patching the `datadog-agent` DaemonSet generated by the Helm chart and replacing the problematic `hostPath` entries with `emptyDir`. My patch file would be:

```patch
809,811c802
<       - hostPath:
<           path: /etc/apt
<           type: ""
---
>       - emptyDir: {}
813,815c804
<       - hostPath:
<           path: /etc/yum.repos.d
<           type: ""
---
>       - emptyDir: {}
817,819c806
<       - hostPath:
<           path: /etc/zypp
<           type: ""
---
>       - emptyDir: {}
825,827c812
<       - hostPath:
<           path: /etc/yum/vars
<           type: ""
---
>       - emptyDir: {}
829,831c814
<       - hostPath:
<           path: /etc/dnf/vars
<           type: ""
---
>       - emptyDir: {}
833,835c816
<       - hostPath:
<           path: /etc/rhsm
<           type: ""
---
>       - emptyDir: {}
```

The reason for replacing it with `emptyDir` is that these paths don't exist on Talos' (readonly) filesystem, and Kubernetes can't create them. Having them as `emptyDir` doesn't harm (since they don't exist anyway) and allows Datadog Agent to boot correctly.

Helm chart version: `datadog-3.118.5`
Talos version: `1.10.4`
Kubernetes version: `1.32.5`

My `values.yaml` file:

```yaml
targetSystem: "linux"
datadog:
  apm:
    hostSocketPath: /var/run/datadog/
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
    compute_stats_by_span_kind: true
    peer_tags_aggregation: true
  profiling:
    enabled: false
  dogstatsd:
    originDetection: true
    useHostPID: true
    useHostPort: true
    nonLocalTraffic: true
  logs:
    containerCollectAll: true
    containerCollectUsingFiles: true
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  site: datadoghq.eu
  systemProbe:
    collectDNSStats: false
    enableOOMKill: true
    enableTCPQueueLength: false
  serviceMonitoring:
    enabled: true
providers:
  talos:
    enabled: true
```

Is this a bug in the Helm Chart, or did I miss a setting? I thought that enabling the `providers.talos` flag would do the trick... 
Thanks in advance for your help!
Christophe.

**Comment by tbavelier** [comment]
Hello @chdeliens ,

The issue comes from `datadog.systemProbe.enableOOMKill` and `datadog.serviceMonitoring.enabled` options you are trying to set. These options causes the flag `runtime-compilation-enabled` to be activated per https://github.com/DataDog/helm-charts/blob/062cf7a8bc09819a468c5818ce78a175ab96e518/charts/datadog/templates/_helpers.tpl#L818-L820 which in turn activates these volumeMounts: https://github.com/DataDog/helm-charts/blob/062cf7a8bc09819a468c5818ce78a175ab96e518/charts/datadog/templates/_daemonset-volumes-linux.yaml#L106-L143

While you can indeed "trick" the chart for instance by setting:
```yaml
datadog:
  systemProbe:
    mountPackageManagementDirs:
    - name: public-key-dir
      mountPath: /host/etc/pki
      hostPath: /etc/pki
```
or modifying the daemonset directly as you did, if you review the logs of the `system-probe` container, you will see it fails to start the OOMKill probing as it can't download the kernel headers that are required to compile the eBPF program used to monitor them:

```shell
╰─❯ k logs dd-datadog-4n9cp -c system-probe | grep -i oom
2025-06-24 11:52:04 UTC | SYS-PROBE | INFO | (cmd/system-probe/modules/oom_kill_probe.go:32 in func14) | Starting the OOM Kill probe
2025-06-24 11:52:04 UTC | SYS-PROBE | WARN | (pkg/collector/corechecks/ebpf/probe/oomkill/oom_kill.go:49 in NewProbe) | error loading CO-RE oom-kill probe: failed to start manager: failed to cleanup tracefs: read kprobe_events: tracefs or debugfs is not available: tracefs: /sys/kernel/tracing is not mounted with tracefs filesystem type
2025-06-24 11:52:04 UTC | SYS-PROBE | ERROR | (pkg/system-probe/api/module/loader.go:89 in Register) | error creating module oom_kill_probe: unable to start the OOM kill probe: unable to find kernel headers
```

```shell
2025-06-24 11:52:04 UTC | SYS-PROBE | INFO | (pkg/util/kernel/headers/download_headers.go:64 in downloadHeaders) | Downloading kernel headers for target distribution talos, release v1.10.4, kernel 6.10.14-linuxkit
2025-06-24 11:52:04 UTC | SYS-PROBE | WARN | (pkg/util/kernel/headers/find_headers.go:165 in GetKernelHeaders) | Unable to find kernel headers: unable to download kernel headers: unable to get kernel header download backend: unsupported distribution 'talos'
``` 

So, this is not directly an issue with the Helm chart but rather whether or not the `system-probe` is supported for Talos Linux since it doesn't ship with kernel headers, and I don't believe they can be installed manually (or in any case, not with a classic package manager that does not exist for Talos). This issue should be reported within our Help portal (https://help.datadoghq.com/hc/en-us) as it will require deeper investigation from the owner team.

In the meantime, you can and should disable system-probe since it doesn't run properly by removing from your `values.yaml`:
```yaml
  systemProbe:
    collectDNSStats: false
    enableOOMKill: true
    enableTCPQueueLength: false
    mountPackageManagementDirs:
    - name: public-key-dir
      mountPath: /host/etc/pki
      hostPath: /etc/pki
  serviceMonitoring:
    enabled: true
```

Afterwards, your configuration should work as expected (tested it successfully with the following cluster:
```shell
╰─❯ k get nodes -owide
NAME                           STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION     CONTAINER-RUNTIME
talos-default-controlplane-1   Ready    control-plane   43m   v1.33.1   10.5.0.2      <none>        Talos (v1.10.4)   6.10.14-linuxkit   containerd://2.0.5
talos-default-worker-1         Ready    <none>          43m   v1.33.1   10.5.0.3      <none>        Talos (v1.10.4)   6.10.14-linuxkit   containerd://2.0.5
╭─ ~                                                                                                                                                                                                                   󱃾 admin@talos-default-3/datadog 14:14:13
╰─❯ k get pod
NAME                                       READY   STATUS    RESTARTS   AGE
dd-datadog-cluster-agent-7f8f6585d-7q4jp   1/1     Running   0          12m
dd-datadog-vxxsk                           2/2     Running   0          11m
dd-datadog-vzmz9                           2/2     Running   0          12m
╭─ ~                                                                                                                                                                                                                   󱃾 admin@talos-default-3/datadog 14:15:00
╰─❯ helm get values dd
USER-SUPPLIED VALUES:
datadog:
  apiKeyExistingSecret: datadog-secret
  apm:
    compute_stats_by_span_kind: true
    hostSocketPath: /var/run/datadog/
    peer_tags_aggregation: true
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
  appKeyExistingSecret: datadog-secret
  clusterName: talos-cluster
  dogstatsd:
    nonLocalTraffic: true
    originDetection: true
    useHostPID: true
    useHostPort: true
  kubelet:
    tlsVerify: false
  logs:
    containerCollectAll: true
    containerCollectUsingFiles: true
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  profiling:
    enabled: false
providers:
  talos:
    enabled: true
targetSystem: linux
```

I'll be closing this issue as it doesn't relate to an issue with the chart, but rather the `system-probe` as mentioned earlier, but feel free to re-open if I misunderstood.

**Comment by tbavelier** [comment]
@chdeliens As I've seen you've opened a ticket in our help portal, regarding control plane monitoring, it's the same "idea" as kubeadm configuration: https://docs.datadoghq.com/containers/kubernetes/control_plane/?tab=helm#Kubeadm. 

First, you need to modify your `machineconfig`, e.g. with `talosctl edit machineconfig --nodes talos-default-controlplane-1` to modify the control plane components (pods/services) to expose their metrics: https://www.talos.dev/v1.10/reference/configuration/v1alpha1/config/#Config.cluster.controllerManager. We are using `extraArgs` and the corresponding option 

<img width="2050" alt="Image" src="https://github.com/user-attachments/assets/a87438c7-f3e0-464f-84e6-5cb773d91e69" />

You can find the required argument in the Kubernetes documentation: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/.

ETCD is slightly different as it doesn't run as a pod, but a service on the node directly. Moreover, the certificates are stored in `/system/secrets/etcd`. Finally, we want to scrape `/metrics` using the node IP. To that end, we use a pod running in `hostNetwork` solely on the master node, such as `kube-scheduler` so `%%host%%` gets replaced with the correct IP: https://docs.datadoghq.com/containers/guide/template_variables/ for more info.

With that, our final configuration (based on yours, removing the problematic `system-probe` parts) becomes:
```yaml
targetSystem: "linux"
datadog:
  kubelet:
    tlsVerify: false
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  clusterName: talos-cluster
  apm:
    hostSocketPath: /var/run/datadog/
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
    compute_stats_by_span_kind: true
    peer_tags_aggregation: true
  profiling:
    enabled: false
  dogstatsd:
    originDetection: true
    useHostPID: true
    useHostPort: true
    nonLocalTraffic: true
  logs:
    containerCollectAll: true
    containerCollectUsingFiles: true
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  ignoreAutoConfig:
    - etcd
    - kube_scheduler
    - kube_controller_manager
  confd:
    etcd.yaml: |-
      # Trick the Agent to only run this check on the host where etcd is running
      # by using `ad_identifiers` for a pod that would only be running on master node.
      # This is to avoid errors when the Agent is running on worker nodes.
      # Another approach would be to run a dummy pod on master node and use it for `ad_identifiers`.
      ad_identifiers:
        - kube-scheduler
      instances:
          # This is the node IP where metrics are exposed because kube-scheduler runs in host network mode.
          # Otherwise, IP could be hardcoded to the master node IP.
        - prometheus_url: https://%%host%%:2379/metrics
          tls_ca_cert: /host/etc/kubernetes/pki/etcd/ca.crt
          tls_cert: /host/etc/kubernetes/pki/etcd/server.crt
          tls_private_key: /host/etc/kubernetes/pki/etcd/server.key      
    kube_scheduler.yaml: |-
      ad_identifiers:
        - kube-scheduler
      instances:
        - prometheus_url: https://%%host%%:10259/metrics
          ssl_verify: false
          bearer_token_auth: true      
    kube_controller_manager.yaml: |-
      ad_identifiers:
        - kube-controller-manager
      instances:
        - prometheus_url: https://%%host%%:10257/metrics
          ssl_verify: false
          bearer_token_auth: true
agents:
  volumes:
    # On Talos, etcd certificates are stored in /system/secrets/etcd
    - hostPath:
        path: /system/secrets/etcd
      name: etcd-certs
  volumeMounts:
    - name: etcd-certs
      mountPath: /host/etc/kubernetes/pki/etcd
      readOnly: true  
providers:
  talos:
    enabled: true
```

```shell
╰─❯ k get pod -owide
NAME                                        READY   STATUS    RESTARTS   AGE     IP            NODE                           NOMINATED NODE   READINESS GATES
dd-datadog-2l9h8                            2/2     Running   0          10m     10.244.1.16   talos-default-controlplane-1   <none>           <none>
dd-datadog-cluster-agent-77f6fcdccc-fbwpx   1/1     Running   0          10m     10.244.1.15   talos-default-controlplane-1   <none>           <none>
dd-datadog-j47s8                            2/2     Running   0          9m37s   10.244.0.17   talos-default-worker-1         <none>           <none>
╭─ ~                                                                                                                                                                                                                   󱃾 admin@talos-default-3/datadog 15:52:48
╰─❯ k exec -it dd-datadog-2l9h8 -- bash
Defaulted container "agent" out of: agent, trace-agent, init-volume (init), init-config (init)
root@dd-datadog-2l9h8:/# agent status | grep -i etcd -A 10
    etcd (8.1.0)
    ------------
      Instance ID: etcd:b7f972f548db0da1 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/etcd.yaml
      Total Runs: 45
      Metric Samples: Last Run: 1,125, Total: 50,625
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 45
      Average Execution Time : 42ms
      Last Execution Date : 2025-06-24 13:54:00 UTC (1750773240000)
      Last Successful Execution Date : 2025-06-24 13:54:00 UTC (1750773240000)
      metadata:
        version.major: 3
        version.minor: 5
root@dd-datadog-2l9h8:/# agent status | grep -i kube_apiserver -A 30
    kube_apiserver_metrics (6.2.0)
    ------------------------------
      Instance ID: kube_apiserver_metrics:ca2dfd34efa93d4f [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kube_apiserver_metrics.d/auto_conf.yaml
      Total Runs: 47
      Metric Samples: Last Run: 10,359, Total: 485,525
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 2, Total: 94
      Average Execution Time : 292ms
      Last Execution Date : 2025-06-24 13:54:22 UTC (1750773262000)
      Last Successful Execution Date : 2025-06-24 13:54:22 UTC (1750773262000)


    kube_controller_manager (7.1.0)
    -------------------------------
      Instance ID: kube_controller_manager:ce85ba278ff50633 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kube_controller_manager.yaml
      Total Runs: 46
      Metric Samples: Last Run: 1,539, Total: 70,794
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 4, Total: 184
      Average Execution Time : 86ms
      Last Execution Date : 2025-06-24 13:54:14 UTC (1750773254000)
      Last Successful Execution Date : 2025-06-24 13:54:14 UTC (1750773254000)


    kube_scheduler (6.1.0)
    ----------------------
      Instance ID: kube_scheduler:3baf83433a8e5373 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kube_scheduler.yaml
      Total Runs: 47
      Metric Samples: Last Run: 144, Total: 6,768
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 4, Total: 188
```
You can see all the components are being monitored successfully:

<img width="2560" alt="Image" src="https://github.com/user-attachments/assets/5c7542de-09c3-40e6-8fb8-978b01d9af48" />

Please note the above is outside the scope of this repository as it is regarding the Agent functionality directly, not the tooling, so further questions on this topic should be done over the ticket / opening an issue on Datadog/datadog-agent.

Thanks!

**Comment by chdeliens** [comment]
Thanks a lot for your answers and guidance @tbavelier 👍 
I'll open a ticket with DD support regarding etcd, as the integration isn't listed when doing `agent status` in the Agent container.

**Comment by tbavelier** [comment]
You're welcome! For reference, I'm working on documenting this process in our control plane documentation https://github.com/DataDog/documentation/pull/32289 so it should be a bit easier to parse/use. I just used these instructions with talos 1.11.1 (k8s 1.34.0)

**Comment by tbavelier** [comment]
Moreover, system-probe should be fixed by https://github.com/DataDog/helm-charts/pull/2105 so you don't need to use the workaround of `mountPackageManagementDirs`. On my AWS cluster, `debugfs` is available, as well as the BTF file, so CO-RE powered features like USM, CNM are working as expected.

**Comment by chdeliens** [comment]
Good to read about the `mountPackageManagementDirs` workaround fix! Thanks.

FYI - starting Datadog Agent v7.69.3 (Helm Chart 3.131.0), I needed extra Helm values to make it work on Talos 1.10 (haven't tested 1.11 yet) or the system-probe container would crash:

```yaml
agents:
  volumes:
    - name: tracefs
      hostPath:
        path: /sys/kernel/tracing
        type: ""
  volumeMounts:
    - name: tracefs
      mountPath: /sys/kernel/tracing
      mountPropagation: None
```

Overall, I really appreciate Datadog's move toward officially supporting the Talos Linux distribution 😃
