### ISSUE TITLE
How to install DatDog agent on worker nodes that have taint by label

### ISSUE THREAD

**Issue by nodesocket** [DataDog/helm-charts#207]
We have three nodes in our cluster that we explicitly set as worker nodes for processing background tasks. This is done by blocking all pods from running on these nodes unless it has the label `high-cpu-node`. I.E. on these worker nodes we set:

```
kubectl taint nodes <worker-node-1> <worker-node-2> <worker-node-3> high-cpu-node=true:NoSchedule
kubectl label nodes <worker-node-1> <worker-node-2> <worker-node-3> high-cpu-node=true
```

The problem is that this Helm install chart is NOT installing the datadog-agent into these worker nodes. Is there a anyway to force DatDog agent to install on all nodes (i.e. apply label high-cpu-node)?

**Comment by nodesocket** [comment]
I tried the following in this Helm chart values.yaml, but  Helm install is still not installing the agent on the worker nodes.

```
datadog:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: high-cpu-node
              operator: In
              values:
              - "true"
  tolerations:
  - key: high-cpu-node
    operator: Equals
    value: "true"
  ```

**Comment by nodesocket** [comment]
Got it working. Values needed to be:

```
agents:
  tolerations:
  - key: high-cpu-node
    operator: Equal
    value: "true"
 ```
