### ISSUE TITLE
Cannot use a dedicated service account for cluster-checks pods when restricted PSPs are enforced

### ISSUE THREAD

**Issue by mvisonneau** [DataDog/helm-charts#208]
**Describe what happened:**

When using a dedicated service account for cluster-checks pods in conjunction of pod security policies, the cluster agent PSP is not "assumable" by the pods anymore.

**Describe what you expected:**

I was expecting the chart to create a rolebinding for the `cluster-checks` service account

**Steps to reproduce the issue:**

```yaml
agents:
  podSecurity:
    podSecurityPolicy:
      create: true

clusterAgent:
  podSecurity:
    podSecurityPolicy:
      create: true

clusterChecksRunner:
  rbac:
    dedicated: true
```
