### ISSUE TITLE
agent.env.DD_APM_ENABLED forced to false in chart

### ISSUE THREAD

**Issue by disconn3ct** [DataDog/helm-charts#220]
`agents.customAgentConfig.apm_config.enabled` conflicts with the [hardcoded disable](https://github.com/DataDog/helm-charts/blob/master/charts/datadog/templates/_container-agent.yaml#L66) in the container-agent template.

The resulting manifest has entries for both true and false in it.

**Comment by clamoriniere** [comment]
Hi @disconn3ct,

The [hardcoded env var](https://github.com/DataDog/helm-charts/blob/master/charts/datadog/templates/_container-agent.yaml#L66) that you linked corresponds to an environment variable set for the "core-agent" container definition, but not the `trace-agent` that provide the APM feature.

If you would like to enable the APM. The chart has a dedicated [field](https://github.com/DataDog/helm-charts/blob/b08b1771cc7544bf590581388804fee7af2a4ab3/charts/datadog/values.yaml#L205) `datadog.apm.enabled` that you can use. It is the simpler way to enable properly the APM functionality.

You can fine more information in the official documentation page [here](https://docs.datadoghq.com/agent/kubernetes/apm/?tab=helm#setup).

Please let us know if you succeed to enable properly APM.

Thanks
Cedric

**Comment by disconn3ct** [comment]
https://github.com/DataDog/helm-charts/blob/master/charts/datadog/values.yaml#L983:
```yaml
  customAgentConfig: {}
  # ...
  #   # Enable APM by setting the DD_APM_ENABLED envvar to true, or override this configuration
  #   apm_config:
  #     enabled: false
```
And on https://www.datadoghq.com/blog/istio-datadog/#receiving-traces:
```
      env:
        [...]
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_APM_NON_LOCAL_TRAFFIC
          value: "true"
        - name: DD_APM_ENV
          value: "<YOUR_ENV_NAME>"
[...]
```

Those (and other similar docs) make no reference to the trace-agent. Maybe this is a doc bug?
