### ISSUE TITLE
Add standard labels in daemonset.yaml in template

### ISSUE THREAD

**Issue by ademar59** [DataDog/helm-charts#230]
**Describe what happened:**

Datadog Agent running 

```
apiVersion: v1
kind: Pod-
  labels:
    app: datadog
    controller-revision-hash: 7844b49b
    pod-template-generation: "1"
```

**Describe what you expected:**

We want to have standard labels in Daemonset pod runnings like you set in the 

```
labels:
    app.kubernetes.io/instance: digipaas-adm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: datadog
    app.kubernetes.io/version: "7"
    helm.sh/chart: datadog-2.5.5
    app: datadog
    controller-revision-hash: 7844b49b
    pod-template-generation: "1"
```

Could be done with _helpers.tpl like https://github.com/Kong/charts/blob/main/charts/kong/templates/deployment.yaml

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

Labels are process as tag to send metrics to **Datadog** and we do not have this information for datadog running pod (agent)
