### ISSUE TITLE
Cluster agent pod spec should include container's runAsNonRoot security context

### ISSUE THREAD

**Issue by Niksko** [DataDog/helm-charts#27]
**Describe what happened:**

I'm trying to create a restrictive PodSecurityPolicy for the Datadog cluster agent. When I create the following policy:

```yaml
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    kubernetes.io/description: 'Custom PSP for the datadog cluster agent'
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
  name: 001-datadog-cluster-agent
spec:
  allowPrivilegeEscalation: false
  allowedProcMountTypes:
    - Default
  fsGroup:
    rule: MustRunAs
    ranges:
      - max: 65535
        min: 1
  hostIPC: false
  hostNetwork: false
  hostPID: false
  hostPorts:
    - max: 65535
      min: 1025
  privileged: false
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
    - AUDIT_CONTROL
    - AUDIT_READ
    - AUDIT_WRITE
    - BLOCK_SUSPEND
    - CHOWN
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    - FOWNER
    - FSETID
    - IPC_LOCK
    - IPC_OWNER
    - KILL
    - LEASE
    - LINUX_IMMUTABLE
    - MAC_ADMIN
    - MAC_OVERRIDE
    - MKNOD
    - NET_ADMIN
    - NET_BIND_SERVICE
    - NET_BROADCAST
    - NET_RAW
    - SETGID
    - SETFCAP
    - SETPCAP
    - SETUID
    - SYS_ADMIN
    - SYS_BOOT
    - SYS_CHROOT
    - SYS_MODULE
    - SYS_NICE
    - SYS_PACCT
    - SYS_PTRACE
    - SYS_RAWIO
    - SYS_RESOURCE
    - SYS_TIME
    - SYS_TTY_CONFIG
    - SYSLOG
    - WAKE_ALARM
  runAsGroup:
    rule: MustRunAs
    ranges:
      - max: 65535
        min: 1
  runAsUser:
    rule: RunAsAny # EXCEPTION: Pod needs to run as root
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - max: 65535
        min: 1
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - projected
    - secret
    - persistentVolumeClaim
---
```

I would expect this policy to be used by the cluster agent pod.

**Describe what you expected:**

Instead of using the above PSP, the cluster agent instead is assigned a more restricted PSP. The pod then fails to be created with the error:

```yaml
state:
        waiting:
          message: container has runAsNonRoot and image will run as root
          reason: CreateContainerConfigError
```

**Steps to reproduce the issue:**

1. Create the above PSP
2. Create a PSP with the line with the # EXCEPTION comment above set to `MustRunAsNonRoot`, with a name that is lexicographically less than 001, eg, `000-restricted`.

**Additional environment details (Operating System, Cloud provider, etc):**

I believe this is this issue: https://github.com/kubernetes/kubernetes/issues/71787

The Pod `securityContext` is:

```yaml
    securityContext:
      fsGroup: 1
      supplementalGroups:
      - 1
```

Where as the container security context is:

```yaml
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - AUDIT_CONTROL
          - AUDIT_READ
          - AUDIT_WRITE
          - BLOCK_SUSPEND
          - CHOWN
          - DAC_OVERRIDE
          - DAC_READ_SEARCH
          - FOWNER
          - FSETID
          - IPC_LOCK
          - IPC_OWNER
          - KILL
          - LEASE
          - LINUX_IMMUTABLE
          - MAC_ADMIN
          - MAC_OVERRIDE
          - MKNOD
          - NET_ADMIN
          - NET_BIND_SERVICE
          - NET_BROADCAST
          - NET_RAW
          - SETFCAP
          - SETGID
          - SETPCAP
          - SETUID
          - SYSLOG
          - SYS_ADMIN
          - SYS_BOOT
          - SYS_CHROOT
          - SYS_MODULE
          - SYS_NICE
          - SYS_PACCT
          - SYS_PTRACE
          - SYS_RAWIO
          - SYS_RESOURCE
          - SYS_TIME
          - SYS_TTY_CONFIG
          - WAKE_ALARM
        readOnlyRootFilesystem: true
        runAsGroup: 1
        runAsNonRoot: true
```

Since the pod spec is what is used to choose a PSP, the wrong PSP is chosen.

I don't see any reason why the Pod spec shouldn't match the container spec
