### ISSUE TITLE
static configurations passed via confd are not picked up by agent

### ISSUE THREAD

**Issue by scott-grimes** [DataDog/helm-charts#274]
### The Problem

Various check configurations added to `datadog.confd` section of values.yaml per the instructions at https://github.com/DataDog/helm-charts/tree/master/charts/datadog#confd-and-checksd fail to run. 

### Steps
1) Define a number of additional static configurations:
```
clusterAgent:
  enabled: true
  confd:
    amazon_msk.yaml: |-
      cluster_check: true
      init_config:
      instances:
      - cluster_arn: <arn>
    redisdb.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - host: <host>
          port: 6379
          tags:
            - cluster_id:<name>
            - node_id:0001
 ...
```

2) Upgrade helm release. Pod logs from `datadog-cluster-agent` show the files getting moved to the datadogs conf.d directory
```
$ kl -f datadog-cluster-agent-664fcf586-8jtmz
...
'/conf.d/redisdb.yaml' -> '/etc/datadog-agent/conf.d/redisdb.yaml'
'/conf.d/amazon_msk.yaml' -> '/etc/datadog-agent/conf.d/amazon_msk.yaml'
...
```

3) datadog-cluster-agent status shows additional `Cluster Checks Dispatching` but nothing in `Collector: Running Checks`
```
$ k exec -it datadog-cluster-agent-664fcf586-8jtmz datadog-cluster-agent status
...
Cluster Checks Dispatching
==========================
  Status: Leader, serving requests
  Active nodes: 2
  Check Configurations: 5
    - Dispatched: 5
    - Unassigned: 0
...
=========
Collector
=========

  Running Checks
  ==============
    
    kubernetes_apiserver
    --------------------
      Instance ID: kubernetes_apiserver [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 5, Total: 18
      Service Checks: Last Run: 3, Total: 9
      Average Execution Time : 1.228s
      Last Execution Date : 2021-06-04 14:41:43.000000 UTC
      Last Successful Execution Date : 2021-06-04 14:41:43.000000 UTC
```

### Documentation Referenced

The docs for adding integrations make it clear that the conf files should be located at datadogs `conf.d/<integration>.d/conf.yaml`

For example for msk integration https://docs.datadoghq.com/integrations/amazon_msk/#configuration the configuration should be placed in `conf.d/amazon_msk.d/conf.yaml`

When reviewing docs for customization using raw manifests at https://docs.datadoghq.com/agent/kubernetes/integrations/?tab=configmap you can see the same requirement, the example given mounts the redisdb conf file at `/conf.d/redisdb.d/conf.yaml`:

```
# [...]
  volumeMounts:
  # [...]
    - name: redisdb-config-map
      mountPath: /conf.d/redisdb.d
  # [...]
volumes:
# [...]
  - name: redisdb-config-map
    configMap:
      name: redisdb-config-map
      items:
        - key: redisdb-config
          path: conf.yaml
# [...]
```

### Question

The instructions for this helm chart https://github.com/DataDog/helm-charts/tree/master/charts/datadog#confd-and-checksd make it seem like there are no other requirements needed to get these configurations working. But the configuration files are not templated into the correct directory by the chart, and so are not picked up by the agent. 

Instead of moving `'/conf.d/redisdb.yaml' -> '/etc/datadog-agent/conf.d/redisdb.yaml'`, should the agent be moving `'/conf.d/redisdb.yaml' -> '/etc/datadog-agent/conf.d/redisdb.d/conf.yaml'`?

Looking at the working `kubernetes_apiserver` configuration, it does indeed come from the subdirectory `      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml.default`

Is there a missing step I'm overlooking? Is the expectation that you should define `datadog.confd`, then hard-code `clusterAgent.volumes` and `clusterAgent.volumeMounts` to match?

**Comment by ahmed-mez** [comment]
Hi @scott-grimes 

The Cluster Agent does not run cluster checks, it dispatches them to the node agents. The `agent clusterchecks` command will give more details about the dispatched checks. More detailed documentation [here](https://docs.datadoghq.com/agent/cluster_agent/clusterchecks/).

Let us know if you have further questions!

**Comment by scott-grimes** [comment]
ah interesting, I was under the impression that the checks would still be surfaced via the `datadog-cluster-agent status`, thanks for the clarification!

**Comment by kamal-brill** [comment]
We are facing the similar issue, i.e. redisdb.d or redisdb.yaml is not created under `conf.d` 

````
replicaCount: 1
image:
  registry: docker.io
  repository: datadog/agent
  tag: 7.33.1
  pullPolicy: Always
serviceAccount:
  create: false
  name: data-dog-sa

extraEnvVarsMap:
  DD_KUBELET_TLS_VERIFY: "False"
  DD_LOGS_ENABLED: "False"
  DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "True"

extraEnvVars:
 - name: DD_API_KEY
   valueFrom:
    secretKeyRef:
        name: api-keys
        key: DD_API_KEY

datadog:
  apiKeyExistingSecret: api-keys
  kubelet:
    tlsVerify: false
  checks:
    redisdb: true
  confd:
    redisdb.yaml: |-
      init_config:
      instances:
        - host: "host1-outside-k8s.com"
          port: "6379"
          password: "plain-password-text"
          timeout: "30"
          slotsRefreshTimeout: "5000"
          tls: "true"
          ssl: "true"
          ssl_check_hostname: "false" 
          ssl_cert_validation: "false"
          ssl_no_verify: "true"
          dnsLookup: "redis"

        - host: "host2-outside-k8s.com"
          port: "6379"
          password: "plain-password-text"
          timeout: "30"
          slotsRefreshTimeout: "5000"
          tls: "true"
          ssl: "true"
          ssl_check_hostname: "false" 
          ssl_cert_validation: "false"
          ssl_no_verify: "true"
          dnsLookup: "redis"
     
name: deployment
ports:
- containerPort: 8080
  protocol: TCP
  name: http
affinity: {}
cluster_agent:
  cmd_port: 5005
apm_config:
  enabled: true
  env: dev
resources:
  limits:
    cpu: "1"
    memory: 3Gi
  requests:
    cpu: "1"
    memory: 2Gi
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
process_config:
      enabled: "disabled"
      process_dd_url: https://process.datadoghq.com
logs_config:
  container_collect_all: "false"
````
