### ISSUE TITLE
Cluster agent connection timeout when trying to send logs to datadog

### ISSUE THREAD

**Issue by jbdelpech** [DataDog/helm-charts#283]
**Describe what happened:**
We are running in AWS EKS cluster. Cluster agent is deployed as Daemonset, and we are trying to send logs to Datadog.

**Network Policies are activated.**

Here is the cluster agent configuration :
```yaml
    logs:
      enabled: true
      containerCollectAll: true
      containerCollectUsingFiles: true
    env:
      - name: DD_LOGS_CONFIG_LOGS_NO_SSL
        value: "false"
      - name: DD_LOGS_CONFIG_USE_HTTP
        value: "true"
```

We got timeout on POST request :
```
2021-06-18 14:11:10 UTC | CLUSTER | ERROR | (pkg/forwarder/worker.go:178 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://1-9-0-app.agent.datadoghq.eu/api/v1/series?api_key=*****************************": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021-06-18 14:11:30 UTC | CLUSTER | ERROR | (pkg/forwarder/worker.go:178 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://1-9-0-app.agent.datadoghq.eu/api/v1/check_run?api_key=*****************************": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Describe what you expected:**
Got 200.

**Steps to reproduce the issue:**
Activate network policies and try to send logs to datadog.

**Steps to fix**
I manually added egress authorization on port 80 with TCP protocol in datadog-cluster-agent network-policy and it fixed the issue.
