### ISSUE TITLE
datadog chart: Allow adding arbitrary initContainers specs to agent Pods

### ISSUE THREAD

**Issue by icelynjennings** [DataDog/helm-charts#286]
I need to run an initContainer before datadog containers run. 

My use case is to run an authorization request before execution.

Currently there is only a way of editing datadog initContainer resources via `agents.containers.initContainers.resources`. This map only affects those initContainers that are preset by default by the Chart's template files for different host operating systems.

**Comment by icelynjennings** [comment]
> Could you elaborate a bit more what is the "authorization request".

Hits a @hashicorp Vault endpoint generating a new Vault `client_token` which should change across Datadog deployments.

> do you need the capability of adding init-container to only the agent running as daemonset,

Only for `datadog-agent`

**Comment by icelynjennings** [comment]
Happy to create this if you're OK with upstreaming?

**Comment by clamoriniere** [comment]
Thanks for the quick response, 

What is the purpose of this `client_token`? who is using it after?

I'm wondering if our ["secret-backend" feature](https://docs.datadoghq.com/agent/guide/secrets-management/?tab=linux) can be use here to call the hashicorp vault sever when the client_token will need to be used. 

We have customers that use the "secret backend" feature to retrieve sensitive information like credential from `vault`. Do you think it can fit your needs?

**Comment by icelynjennings** [comment]
Thanks @clamoriniere. I followed your linked instruction and mounted a compiled secrets-backend binary into the datadog agent container (I modified the documentation's Go example to fit my needs). It may become a better solution to change datadog agent's container image to include Go, so it can compile the binary on startup, or use a Go image initContainer to do the same.

I found the process of distributing the binary into agent containers significantly more involved than authenticating from a discardable initContainer however, particularly because I'm unsure how well my team will be able to maintain this code, compared to a few lines of shell script in an initContainer.

**Comment by icelynjennings** [comment]
> What is the purpose of this client_token? who is using it after?

This token is used by [Datadog's Vault integration](https://docs.datadoghq.com/integrations/vault/?tab=host#configuration)

**Comment by icelynjennings** [comment]
Would @datadog still prefer to hide initContainers from the official chart? I have opened a fork to implement this if you'd like to push it through

**Comment by winnieoursbrun** [comment]
With that, do you think we can install community integration more easily than create a new docker image ?

**Comment by AnthonyHerman** [comment]
FYI in case this helps anyone, you can get the vault integration working with the authenticated metrics endpoint using the agents.podAnnotations with vault injector. This is what my setup looks like ->

```yaml
datadog:
  confd:
    vault.yaml: |-
      init_config: {}
      instances:
        - api_url: http://vault.default.svc.cluster.local:8200/v1
          client_token_path: /vault/secrets/token
agents:
  podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-token: "true"
    vault.hashicorp.com/auth-path: "${var.datadogVaultAuthPath}"
    vault.hashicorp.com/role: "${var.datadogVaultRole}"
    vault.hashicorp.com/agent-pre-populate: "true"
    vault.hashicorp.com/agent-pre-populate-only: "false"
```
