### ISSUE TITLE
[datadog] Can't get the RDS Postgres integration working with datadog chart

### ISSUE THREAD

**Issue by carlosjgp** [DataDog/helm-charts#316]
**Describe what happened:**
Postgres metrics are not reported and no errors are showed on the cluster agent

**Describe what you expected:**
Metrics to be preset

**Steps to reproduce the issue:**
- Create Postgres `12` Aurora RDS instance
- Provision `datadog` user using the [integration instructions](https://docs.datadoghq.com/integrations/postgres/?tab=host)
![image](https://user-images.githubusercontent.com/1277613/125339344-1fc42c80-e349-11eb-8edd-5da24556f662.png)

- Create Kubernetes secret
```
$ kubectl create secret generic <SECRET> --from-literal=DATADOG_USER_PWD=supersecret
```
- Deploy `datadog` chart version `2.19.2` with the configuration
```
clusterAgent:
  confd:
    postgres.yaml: |-
      cluster_check: true
      instances:

        - server: <ENDPOINT>.rds.amazonaws.com
          port: 5432
          user: datadog
          pass: ENC[DATADOG_USER_PWD]
  enabled: true
  env:
  - name: DD_SECRET_BACKEND_COMMAND
    value: /readsecret.sh
  - name: DD_SECRET_BACKEND_ARGUMENTS
    value: /etc/secret-volume
  resources:
    limits:
      cpu: 50m
      memory: 150Mi
    requests:
      cpu: 25m
      memory: 100Mi
  token: <TOKEN>
  volumeMounts:
  - mountPath: /etc/secret-volume
    name: <SECRET>
    readOnly: true
  volumes:
  - name: <SECRET>
    secret:
      optional: false
      secretName: <SECRET>

```

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS 1.20

**Comment by carlosjgp** [comment]
We have used this as a reference, but instead of using agent checks we have used cluster agent checks

    https://docs.datadoghq.com/integrations/postgres/?tab=host
    https://docs.datadoghq.com/agent/cluster_agent/clusterchecks/#setting-up-check-configurations

You can see on the Github issue that, as far as I can see we have met the requirements to configure the postgres integration through clustercheck

> When the IP of a given resource is constant (eg. external service endpoint, public URL, etc.), a static configuration can be passed to the Cluster Agent as YAML files. The file name convention and syntax are the same as the static configurations on the node-based Agent, with the addition of the cluster_check: true line

Looks like to get the Cluster agent working I need to enable another part of the chart... `clusterChecksRunner` to 
> Cluster checks extend this mechanism to monitor noncontainerized workloads, including:
>   - Out-of-cluster datastores and endpoints (for example, RDS or CloudSQL)

But the documentation that the Helm chart pointed me to.
```
  # clusterAgent.confd -- Provide additional cluster check configurations
  ## Each key will become a file in /conf.d
  ## ref: https://docs.datadoghq.com/agent/autodiscovery/
  confd: {}
  #   mysql.yaml: |-
  #     cluster_check: true
  #     instances:
  #       - host: '<EXTERNAL_IP>'
  #         port: 3306
  #         user: datadog
  #         pass: '<YOUR_CHOSEN_PASSWORD>'
```
the other property makes reference to a different page
```
clusterChecksRunner:
  # clusterChecksRunner.enabled -- If true, deploys agent dedicated for running the Cluster Checks instead of running in the Daemonset's agents.
  ## ref: https://docs.datadoghq.com/agent/autodiscovery/clusterchecks/
  enabled: false
```

But this is highly confusing so I decided to go back to the `agent` configuration and move the `confd` configuration to `datadog.confd`

To do this I had to change the secret backend from 
```
    - name: DD_SECRET_BACKEND_COMMAND
      value: /readsecret.sh
```
to
```
    - name: DD_SECRET_BACKEND_COMMAND
      value: /readsecret.py
```
because the `/readsecret.sh` script does not exist on the agents, as pointed in the documentation

something confusing is that the secret I have to mount is not under `datadog.volumes` but instead 
```
datadog:
  confd:
    postgres.yaml: |-
      cluster_check: true
      instances:
        - host: <ENDPOINT>.rds.amazonaws.com
          port: 5432
          user: datadog
          pass: ENC[DATADOG_USER_PWD]
  env:
  - name: DD_SECRET_BACKEND_COMMAND
    value: /readsecret.sh
  - name: DD_SECRET_BACKEND_ARGUMENTS
    value: /etc/secret-volume

agents:
  volumes:
    - name: datadog-postgres
      secret:
        secretName: datadog-postgres
        optional: false

  volumeMounts:
    - name: datadog-postgres
      readOnly: true
      mountPath: /etc/secret-volume
```

I've also noticed that the example provided on the Helm chart values does not follow the same variable names as with postgres
so I had to change this into
```
        - host: <ENDPOINT>.rds.amazonaws.com
          port: 5432
          user: datadog
          pass: ENC[DATADOG_USER_PWD]
```
this
```
        - host: <ENDPOINT>.rds.amazonaws.com
          port: 5432
          username: datadog
          password: ENC[DATADOG_USER_PWD]
```

checking if this integration works
```
$ cat /etc/datadog-agent/conf.d/postgres.yaml 
# Not a cluster check. See https://github.com/DataDog/helm-charts/issues/316
# cluster_check: true
instances:

  - host: <ENDPOINT>.rds.amazonaws.com
    port: 5432
    username: datadog
    password: ENC[DATADOG_USER_PWD]
```


And then the integration works.

But I'm curious about how to make this work with `clustertAgent` instead.

Could someone please point out how to achieve this?
Thanks

**Comment by awilson1801** [comment]
@carlosjgp by chance were you able to get this working using the clusterAgent?

**Comment by carlosjgp** [comment]
Hi @awilson1801 , 

yes I've been able to use `clusterAgent` with the Postgres integration but there are still a couple of problems standing
- Missing global tags for all my integrations running on `clusterAgent` => https://github.com/DataDog/integrations-core/issues/10205
- I'm not able to get all the metrics for the integration dashboards: Postgres, RDS/Aurora postgres 

This is my current deployment for chart version `2.22.10`

```
agents:
  # clusterAgent checks are actually run by the agents or checkRunners. You should mount these secret on one or the other... or both :shrug: 
  volumeMounts:
  - mountPath: /etc/secret-volume
    name: datadog-integrations-secret
    readOnly: true
  volumes:
  - name: datadog-integrations-secret
    secret:
      optional: false
      secretName: datadog-integrations-secret

clusterAgent:
  confd:
    postgres.yaml: |-
      cluster_check: true
      instances:
        - dbm: true
          host: <RDS instance, NOT CLUSTER, endpoint>
          port: 5432
          username: datadog
          password: ENC[RDS]
          tags:
            - dbinstanceidentifier:engprod-infra-1
            - rds_cluster_id:engprod-infra
            - rds_instance_id:engprod-infra-1
  enabled: true

datadog:
  env:  # these env vars enable the "secret reader" feature
  - name: DD_SECRET_BACKEND_COMMAND
    value: /readsecret.py
  - name: DD_SECRET_BACKEND_ARGUMENTS
    value: /etc/secret-volume  # where you have mounted the secret on the agent or checkRunner

  # Added just for clarity
  tags:  # These are missing on the clusterAgent metrics
  - cluster_name:my-cluster
  - env:my-stack-develop
  - stack_name:my-stack
  - stack_type:develop
```

I'd recommend you to read all the documentation carefully... It's a lot of it, to be honest, and I still have not a clear idea of how to get all the metrics I want. I have a ticket open with DD. I will update this once is solved

There are a few things that are putting me a little bit off to continue with this... eg:

[Postgres integration](https://docs.datadoghq.com/integrations/postgres/?tab=host)
![image](https://user-images.githubusercontent.com/1277613/135316730-8ce63fd5-e5d3-45db-8aac-a6f2ef37e174.png)

Vs

[Aurora Postgres](https://docs.datadoghq.com/database_monitoring/setup_postgres/aurora/?tab=postgres10)
![image](https://user-images.githubusercontent.com/1277613/135316798-43c6cfe5-43d5-490f-823d-607b810e2ee1.png)


Notice that the provisioning instructions are different and it has to be done per database... that's a little bit unrealistic for us since developers own the creating the DB so we are considering building something to detect new DBs and provision this or maybe the effort is not worth it... :/

References:
- https://docs.datadoghq.com/database_monitoring/setup_postgres/
- https://docs.datadoghq.com/integrations/amazon_rds/?tab=native
- https://docs.datadoghq.com/database_monitoring/setup_postgres/aurora/?tab=postgres10#install-the-rds-integration
- https://docs.datadoghq.com/integrations/postgres/?tab=host
- https://docs.datadoghq.com/database_monitoring/troubleshooting/?tab=postgres

**Comment by awilson1801** [comment]
This is helpful. It turns out I missed something something AND the instructions provided by datadog were missing info. I appreciate your help!

**Comment by casey-robertson-paypal** [comment]
@carlosjgp - did Datadog ever give you answers?  I was about to embark upon Postgres RDS monitoring and I'm glad I saw this post first.  It almost makes me not want to do it in Kubernetes.

**Comment by casey-robertson-paypal** [comment]
I kind of got this working but continually receive this error:

`(statements.py:242) | Unable to collect statement metrics because pg_stat_statements is not created in this database`

I've triple checked that this is created - I ran the documented steps:  

```
CREATE SCHEMA datadog;
GRANT USAGE ON SCHEMA datadog TO datadog;
GRANT USAGE ON SCHEMA public TO datadog;
GRANT pg_monitor TO datadog;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
```

Verified its presence:

```
SELECT * FROM pg_available_extension_versions WHERE name = 'pg_stat_statements';
        name        | version | installed | superuser | relocatable | schema | requires |                          comment
--------------------+---------+-----------+-----------+-------------+--------+----------+-----------------------------------------------------------
 pg_stat_statements | 1.4     | f         | t         | t           |        |          | track execution statistics of all SQL statements executed
 pg_stat_statements | 1.5     | f         | t         | t           |        |          | track execution statistics of all SQL statements executed
 pg_stat_statements | 1.6     | f         | t         | t           |        |          | track execution statistics of all SQL statements executed
 pg_stat_statements | 1.7     | t         | t         | t           |        |          | track execution statistics of all SQL statements executed
(4 rows)
```

In the Datadog UI I see query SAMPLES but nothing about METRICS.... not sure what to try at this point.

**Comment by lrobles-iterable** [comment]
I'm running into a similar issue where even if i'm using the `/read_secrets_multiple_providers.sh` script, my config file on the host has the literal string `ENC[k8s_secret@xxxxxxxx/xxxxxx` in place


```yaml
datadog:
  clusterAgent:
    confd:
      postgres.yaml: |-
        cluster_check: true
        init_config:
        instances:
          - dbm: true
            host: xxx.xxx.xxx.xxx
            port: 5432
            username: datadog
            password: ENC[k8s_secret@namespace/password/password]
```
