### ISSUE TITLE
[Kubernetes] Not able to collect logs from specific containers by using Helm values 

### ISSUE THREAD

**Issue by sevetseh28** [DataDog/helm-charts#331]
**Describe what happened:**
If I set `containerCollectAll` via the values yaml file all logs appear in my Datadog end which is fine.
 
But I want to only collect logs from a certain App (containers), so as soon as I set `containerCollectAll` to `false` and try to only collect logs via `containerInclude` I dont see any logs on my Datadog end, even if I write a regex to include everything.

**Describe what you expected:**
I expect the DD agents to collect logs from the Pods with a certain name or image depending on the value I set in `containerInclude` or `containerIncludeLogs`

**Steps to reproduce the issue:**
Set:
```yaml
logs:
    containerCollectAll: false
    enabled: true
containerInclude: "image:<NAME_OF_IMAGE>"
```

**Additional environment details (Operating System, Cloud provider, etc):**
Im using a Kubernetes cluster with AKS and Istio on top.

This issue is related to: https://github.com/DataDog/helm-charts/issues/131

**Comment by ahmed-mez** [comment]
Hi @sevetseh28 

In order to achieve that, you'd need to enable `containerCollectAll` and combine `containerInclude` and `containerExclude`:

```yaml
datadog:
  logs:
    containerCollectAll: true
    enabled: true
  containerInclude: "image:<NAME_OF_IMAGE>"
  containerExclude: "image:.*"
```

The detailed documentation of container filtering is documented [here](https://docs.datadoghq.com/agent/kubernetes/?tab=helm#ignore-containers).

Thanks!
