### ISSUE TITLE
Amazon EKS AMI creates containerd socket at diferent path

### ISSUE THREAD

**Issue by rafaelgaspar** [DataDog/helm-charts#338]
**Describe what happened:**

Amazon EKS AMI is currently creating the containerd socket at `/run/dockershim.sock`, the reason for that is that `aws-cni-plugin` still points to that path, so they cannot at the moment just change to `/run/containerd/containerd.sock`.

Setting `criSocketPath: /run/dockershim.sock` works for CRI metrics, but not for containerd metrics.

**Describe what you expected:**

containerd metrics to be available, maybe have a way to set a different mountPath for the criSocketPath inside datadog container so that it recognises it is a containerd socket.

**Steps to reproduce the issue:**

Spin up cluster on EKS and set `--container-runtime containerd` for `bootstrap.sh`

**Additional environment details (Operating System, Cloud provider, etc):**

EKS AMI v1.21.2-13+d2965f0db10712

**Comment by rafaelgaspar** [comment]
BTW, there is also https://github.com/awslabs/amazon-eks-ami/pull/724

**Comment by cw-sakamoto** [comment]
After making the following settings, it worked even if `dockershim.sock` for containerd's cri path.

```
agents:
  volumes:
    - hostPath:
        path: /var/run/dockershim.sock
      name: crisocketpath
  volumeMounts:
    - name: crisocketpath
      mountPath: /var/run/containerd/containerd.sock
      readOnly: true
 ```
