### ISSUE TITLE
Ability to disable and configure autodiscovery in helm charts

### ISSUE THREAD

**Issue by ryan-dyer-sp** [DataDog/helm-charts#34]
**Describe what happened:**
I am running the agent in a k8s cluster using cluster agent and deployed via latest helm chart.  The kube-state-metrics integration is autodiscovered on the masters but is improperly configured.  I can not see a way using the helm chart to disable/reconfigure the autodiscovery configuration for the masters.  I have tried the datadog.confd configuration, but this just places files into /etc/datadog-agent/conf.d/ .   The autodiscovery directory still appears to have precedence for the configuration.  IMO the datadog.confd should work by taking over the /etc/datadog-agent/conf.d/<key> directory .  I have some changes I am working on to the helm template which work for us that I'd be happy to cleanup and submit via PR if it's the correct direction to take.  

The one issue I am finding which has prevented me from submitting thus far is that I have changed the design such that the older datadog.autoconf support no longer can be merged with datadog.confd.  My design is that each key for datadog.confd creates distinct configmap which gets mounted into the agent container at /etc/datadog-agent/conf.d/<key>/conf.yaml .  This allows for overwriting the existing autoconf files/directories.  Due to this design, the existing configmap which appears to merge the older datadog.autoconf values with the newer data.confd values will no longer work.

**Comment by daniel-ciaglia** [comment]
@ryan-dyer-sp is your fork working well? Did you consider merging it back to the main chart?

**Comment by elementalvoid** [comment]
🤔 I found this issue while looking for something else but thought I might be able to add some more information...

I _do_ custom configure the `kube-state-metrics` (KSM) check. I add a _bunch_ of custom label mappings. However, I too would like to be able to disable the autodiscovery for KSM as right now I'm pretty darn sure I monitor it twice (once via autodiscovery and once via custom config).

My team's clusters have been running this way for a few years without negative consequences -- aside from probably excessive memory consumption on the agent doing the KSM checks.

Here's the output of `agent status` for the KSM node:
```
    kubernetes_state (5.6.3)
    ------------------------
      Instance ID: kubernetes_state:95af86c73bda5447 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_state.yaml
      Total Runs: 584
      Metric Samples: Last Run: 52,910, Total: 30,720,970
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 439, Total: 254,407
      Average Execution Time : 7.734s
      Last Execution Date : 2021-01-16 00:24:23.000000 UTC
      Last Successful Execution Date : 2021-01-16 00:24:23.000000 UTC

      Instance ID: kubernetes_state:bf48d2f50b099002 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_state.d/auto_conf.yaml
      Total Runs: 585
      Metric Samples: Last Run: 52,910, Total: 30,773,209
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 439, Total: 254,846
      Average Execution Time : 4.358s
      Last Execution Date : 2021-01-16 00:24:28.000000 UTC
      Last Successful Execution Date : 2021-01-16 00:24:28.000000 UTC
```

We only have a single KSM Pod on this Node yet the DD `agent` configures _two checks_. Notice the runtime difference on them too: the `auto_conf` check takes `4.358s` whereas the `custom` check with additional processing takes `7.734s`.

And here's the relevant helm config (note I'm using YAML anchor/reference to short things up):
```yaml
datadog:
  confd:
    # Update labels in kube-state-metrics (KSM) to make them useful. Joins labels via prometheus labels.
    # https://github.com/DataDog/integrations-core/pull/1040
    # Finding all supported labels
    #   kubectl  port-forward <kube-state-metrics-pod-name> 8080:8080
    #   curl -s localhost:8080/metrics | grep -o '^.*_labels{' | uniq
    kubernetes_state.yaml: |-
      # these get referenced later and merged into the `label_joins` sections
      common_labels: &common_labels
        labels_to_get:
          - namespace
          - label_app
          - label_k8s_app
          - label_app_version
          - label_release
          - label_group
          - label_squad
          - label_department
          - label_primary_slack_channel
          - label_primary_email
          - label_datadog_notification
          - label_service_tier
      ad_identifiers:
        - kube-state-metrics
      init_config:
      instances:
        - kube_state_url: http://%%host%%:%%port%%/metrics
          # join_standard_tags is for unified tagging.
          # see: https://github.com/DataDog/integrations-core/blob/master/kubernetes_state/datadog_checks/kubernetes_state/data/conf.yaml.example#L59-L70
          join_standard_tags: true

          # this configures remaps of KSM metric labels to DD Tags -- if the labels don't exist on a resource that's okay
          labels_mapper:
            label_app: kube_app
            label_k8s_app: kube_app
            label_app_version: kube_app_version
            label_failure_domain_beta_kubernetes_io_zone: failure_domain_zone
            label_node_lifecycle: node-lifecycle
            label_release: release
            label_group: group
            label_squad: squad
            label_department: department
            label_primary_slack_channel: primary-slack-channel
            label_primary_email: primary-email
            label_datadog_notification: datadog-notification
            label_service_tier: service-tier

          # these configure which (mapped or unmapped) labels should be linked to each
          label_joins:
            kube_deployment_labels:
              label_to_match: deployment
              <<: *common_labels
            kube_replicaset_labels:
              label_to_match: replicaset
              <<: *common_labels
            kube_node_labels:
              label_to_match: node
              labels_to_get:
                - label_failure_domain_beta_kubernetes_io_zone
                - label_beta_kubernetes_io_instance_type
                - label_nodegroup_name
                - label_node_lifecycle
            kube_pod_labels:
              label_to_match: pod
              <<: *common_labels
            kube_cronjob_labels:
              label_to_match: cronjob
              <<: *common_labels
            kube_job_labels:
              label_to_match: job
              <<: *common_labels
            kube_service_labels:
              label_to_match: service
              <<: *common_labels
            kube_ingress_labels:
              label_to_match: ingress
              <<: *common_labels
            kube_hpa_labels:
              label_to_match: hpa
              <<: *common_labels
            kube_daemonset_labels:
              label_to_match: daemonset
              <<: *common_labels
```
