### ISSUE TITLE
limit max number of restarts in datadog helm chart

### ISSUE THREAD

**Issue by caleb15** [DataDog/helm-charts#345]
**Describe what happened:**
Datadog Posture Management says that we are failing the `'on-failure' container restart policy is set to '5'` rule.

Rule description: https://docs.datadoghq.com/security_platform/default_rules/cis-docker-1.2.0-5.14/

 The resource in question is the security agent container generated from [this file](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/_container-security-agent.yaml). In [parent file](https://github.com/DataDog/helm-charts/blob/ff98e40b24bb0e8d2eb3bb31d10615dfbaeb1ab9/charts/datadog/templates/daemonset.yaml) you can see that `maxRetries` is not set.

**Describe what you expected:**
Rule passes.

**Steps to reproduce the issue:**
Deploy datadog helm chart with the following values:
```yml
       securityAgent:
          runtime:
            enabled: true
          compliance:
            enabled: true
```

**Additional environment details (Operating System, Cloud provider, etc):**
