### ISSUE TITLE
[Charts/Datadog] Reading DD_VERSION from a ConfigMap, Secret or anything but a literal value is not implemented yet.

### ISSUE THREAD

**Issue by caleb15** [DataDog/helm-charts#348]
**Describe what happened:**
I see warnings saying "Reading DD_VERSION from a ConfigMap, Secret or anything but a literal value is not implemented yet.". I'm not sure if this is causing any errors/data-loss but it's a bit worrying.

**Describe what you expected:**
No warnings. I'm passing DD_VERSION via container env. Which I'm presuming is a literal value? I'm not quite sure what a "literal value" is.

**Steps to reproduce the issue:**
Deploy datadog helm chart

**Additional environment details (Operating System, Cloud provider, etc):**

The error comes from [here](https://github.com/DataDog/datadog-agent/blob/e8a96aa8aa2aa9851b8b537b77542d4d03208ec8/pkg/tagger/collectors/kubelet_extract.go#L217).

I'm passing DD_VERSION as recommended by datadog guide like so:

```yml
# (simplified code as follows)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daphne-{{ $instance }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ $.Chart.Name }}
    instance: {{ $instance }}
    tags.datadoghq.com/env: {{ $.Values.vpc_name }}
    tags.datadoghq.com/service: {{ $.Release.Name }}
    tags.datadoghq.com/version: {{ $.Values.image.tag | trunc 7 | quote }}
  annotations:
    chart/version: "{{ $.Chart.Version }}"
spec:
  replicas: {{ $details.replicas | default 1 }}
  selector:
    matchLabels:
      instance: {{ $instance }}
  template:
    metadata:
      labels:
        name: {{ $.Chart.Name }}
        instance: {{ $instance }}
        tags.datadoghq.com/env: {{ $.Values.vpc_name }}
        tags.datadoghq.com/service: {{ $.Release.Name }}
        tags.datadoghq.com/version: {{ $.Values.image.tag | trunc 7 | quote }}
      annotations:
        ad.datadoghq.com/daphne-{{ $instance }}.logs: '[{"source": "python"}]'
    spec:
      containers:
        - name: my-container
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          command: [
            "ddtrace-run",
          ]
          args: [
            "myService",
          ]
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
```

Event attributes:
```
{
--
agent | PROCESS
filename | pkg/tagger/collectors/kubelet_extract.go
level | WARN
lineno | 224
process | parsePods
timestamp | 1629908542000
}
```

Full log line:
`2021-08-25 16:22:22 UTC | PROCESS | WARN | (pkg/tagger/collectors/kubelet_extract.go:224 in parsePods) | Reading DD_VERSION from a ConfigMap, Secret or anything but a literal value is not implemented yet.`

Some labels:
kube_app_name:datadog
pod_name:datadog-wckbd
container_name:k8s_process-agent_datadog-wckbd_logging_11a3fad8-fc21-444c-86ff-ac82b681412b_0
kube_container_name:process-agent

**Comment by L3n41c** [comment]
Hello @caleb15,

Thanks for reaching out to us !

A literal value is a fixed string value in the form `value: <string>`.
Concretely, the errors you are seeing can be fixed by removing the use of downward API and directly set the value like this:

```diff
--- orig.yaml	2021-08-30 11:00:58.000000000 +0200
+++ fixed.yaml	2021-08-30 11:03:01.000000000 +0200
@@ -47,14 +47,8 @@
                 fieldRef:
                   fieldPath: status.hostIP
             - name: DD_ENV
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.labels['tags.datadoghq.com/env']
+              value: {{ $.Values.vpc_name }}
             - name: DD_SERVICE
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.labels['tags.datadoghq.com/service']
+              value: {{ $.Release.Name }}
             - name: DD_VERSION
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.labels['tags.datadoghq.com/version']
+              value: {{ $.Values.image.tag | trunc 7 | quote }}
```

The drawback of this approach is that the `env`, `service` and `version` values are duplicated between the labels and containers’ env sections.

An elegant solution to this duplication issue is to leverage the [Datadog Admission Controller](https://docs.datadoghq.com/agent/cluster_agent/admission_controller) so that those environment variables get automatically injected to the pod.

Once the [Datadog Admission Controller has been setup](https://docs.datadoghq.com/agent/cluster_agent/admission_controller/#configuration), we can just remove the definition of those standard environment variables from the Deployment’s pod template like this:

```diff
--- orig.yaml	2021-08-30 11:00:58.000000000 +0200
+++ webhook.yaml	2021-08-30 11:15:20.000000000 +0200
@@ -22,6 +22,7 @@
       labels:
         name: {{ $.Chart.Name }}
         instance: {{ $instance }}
+        admission.datadoghq.com/enabled: "true"
         tags.datadoghq.com/env: {{ $.Values.vpc_name }}
         tags.datadoghq.com/service: {{ $.Release.Name }}
         tags.datadoghq.com/version: {{ $.Values.image.tag | trunc 7 | quote }}
@@ -42,19 +43,3 @@
               valueFrom:
                 fieldRef:
                   fieldPath: status.hostIP
-            - name: DD_AGENT_HOST
-              valueFrom:
-                fieldRef:
-                  fieldPath: status.hostIP
-            - name: DD_ENV
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.labels['tags.datadoghq.com/env']
-            - name: DD_SERVICE
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.labels['tags.datadoghq.com/service']
-            - name: DD_VERSION
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.labels['tags.datadoghq.com/version']
```

Check that the variables have properly been injected on the pod.

Here is the final Deployment’s manifest:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daphne-{{ $instance }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ $.Chart.Name }}
    instance: {{ $instance }}
    tags.datadoghq.com/env: {{ $.Values.vpc_name }}
    tags.datadoghq.com/service: {{ $.Release.Name }}
    tags.datadoghq.com/version: {{ $.Values.image.tag | trunc 7 | quote }}
  annotations:
    chart/version: "{{ $.Chart.Version }}"
spec:
  replicas: {{ $details.replicas | default 1 }}
  selector:
    matchLabels:
      instance: {{ $instance }}
  template:
    metadata:
      labels:
        name: {{ $.Chart.Name }}
        instance: {{ $instance }}
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: {{ $.Values.vpc_name }}
        tags.datadoghq.com/service: {{ $.Release.Name }}
        tags.datadoghq.com/version: {{ $.Values.image.tag | trunc 7 | quote }}
      annotations:
        ad.datadoghq.com/daphne-{{ $instance }}.logs: '[{"source": "python"}]'
    spec:
      containers:
        - name: my-container
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          command: [
            "ddtrace-run",
          ]
          args: [
            "myService",
          ]
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
```
