### ISSUE TITLE
PSP doesn't include required apparmor profile by default

### ISSUE THREAD

**Issue by Niksko** [DataDog/helm-charts#35]
**Describe what happened:**

When deploying the chart with the agent PSP enabled, the PSP doesn't allow for the `unconfined` apparmor profile used by default by the system probe container

**Describe what you expected:**

This PSP should allow the unconfined apparmor profile

**Steps to reproduce the issue:**

1. Deploy the Helm chart with:

```
values:
  agents:
    enabled: true
    podSecurity:
      podSecurityPolicy:
        create: true
```

**Additional environment details (Operating System, Cloud provider, etc):**

Chart version 2.4.14
