### ISSUE TITLE
Use of randAlphaNum causes pod updates every upgrade

### ISSUE THREAD

**Issue by damonmaria** [DataDog/helm-charts#364]
**Describe what happened:**
Ran `helm upgrade datadog/datadog` two times without any changes in-between. 

The cluster-agent is updated and restarted.

I assume this is because the cluster-agent-token uses `randAlphaNum` [here](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/secret-cluster-agent-token.yaml#L15).

**Describe what you expected:**
Performing an upgrade with no changes should not cause a restart. 

**Steps to reproduce the issue:**
`helm upgrade datadog/datadog` twice when using the cluster agent.

**Additional environment details (Operating System, Cloud provider, etc):**
Ubuntu 20.04 on bare metal

**Comment by clamoriniere** [comment]
Hello @damonmaria,

Indeed the `randAlphaNum`, can force an update of every pod each time `helm upgrade datadog/datadog` is executed. 

The chart has this logic to avoid asking the user to set a "token" by default. I was made for backward compatibility. 

But to avoid having a new `token` generated each time you upgrade the chart, It is recommended to define the token in you `values.yaml` or with the a `--set` option.
Two parameters can be use for this purpose:
* `clusterAgent.token`: needs to be at least 32 characters a-zA-z ([link](https://github.com/DataDog/helm-charts/blob/fd2fe179a0f78127bf7d3d075d995078a18b3563/charts/datadog/values.yaml#L514))
* `clusterAgent.tokenExistingSecret `: Existing secret name to use for Cluster Agent token, this secret should contains the `token` key with a value to be at least 32 characters a-zA-z ([link](https://github.com/DataDog/helm-charts/blob/fd2fe179a0f78127bf7d3d075d995078a18b3563/charts/datadog/values.yaml#L517))

Please let us know if this explanation helped you to avoid having the issue again.

**Comment by damonmaria** [comment]
Works exactly as advertised. Thanks for the prompt and precise help @clamoriniere.

**Comment by hermannolafs** [comment]
From suggestions in this thread I have solved this for now by adding this template in a wrapper chart we have around the DataDog chart

```yaml
{{- if not (lookup "v1" "Secret" .Release.Namespace ( .Values.datadog.clusterAgent.tokenExistingSecret | quote )) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.datadog.clusterAgent.tokenExistingSecret | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  token: {{ randAlphaNum 32 }}
{{- end }}
```

I adapted this from this stack overflow thread https://stackoverflow.com/questions/56170052/how-not-to-overwrite-randomly-generated-secrets-in-helm-templates/70875930#70875930

**Comment by kayketeixeira** [comment]
Hello @hermannolafs, i used this and it worked in the beginning but after some deploys i got errors 403 in the clusterAgent...

``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: datadog-cluster-agent-secret
data:
  {{- $secret := (lookup "v1" "Secret" "datadog" "datadog-cluster-agent-secret") | default (dict "data" (dict "token" "")) }}
  {{- $token := empty $secret.data.token | ternary ((default (randAlphaNum 32) .Values.clusterAgent.token) | b64enc | quote) $secret.data.token }}
  token: {{ $token }}

```
