### ISSUE TITLE
DatadogMonitor is not "working"

### ISSUE THREAD

**Issue by OceaneLonneux-CAL** [DataDog/helm-charts#390]
**Describe what happened:**
 We are trying to test the new automatic monitor feature and are running into this :
```
kubectl get datadogmonitor datadog-monitor-test
NAME                   ID    MONITOR STATE   LAST TRANSITION   LAST SYNC   SYNC STATUS   AGE
datadog-monitor-test                                                                     45h
```

There is no information, no events on why this is happening. We are following the guide and deployed the template provided in the docs.

**Describe what you expected:**
The monitor to be spin up, or at least errors. 

**Steps to reproduce the issue:**
Charts version:
- datadog: 2.19.4,
- datadog-crds: 0.4.1,
- datadog-operator: 0.7.0.

We have configured `values.yaml` to the following:
```
datadog-operator:
  apiKey: XXX
  appKey: XXX
  nodeSelector:
    kubernetes.io/os: linux
  datadogMonitor:
    enabled: true

datadog-crds:
  crds:
    datadogMonitors: true
```

This is the monitor deployed:
```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: datadog-monitor-test
spec:
  query: "avg(last_10m):avg:system.disk.in_use{*} by {host} > 0.5"
  type: "metric alert"
  name: "Test monitor made from DatadogMonitor"
  message: "We are running out of disk space!"
  tags:
    - "test:datadog"
```

**Additional environment details (Operating System, Cloud provider, etc):**
Azure Kubernetes version 1.21.2.
