### ISSUE TITLE
Notifications not working/not available yet?

### ISSUE THREAD

**Issue by OceaneLonneux-CAL** [DataDog/helm-charts#403]
**Describe what happened:**
Following the example on [Datadog Docs](https://www.datadoghq.com/blog/create-manage-kubernetes-alerts-datadog/), we have the following example:
```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: pods-crashloopbackoff
  namespace: x
spec:
  query: "max(last_10m):max:kubernetes_state.container.status_report.count.waiting{reason:crashloopbackoff, app:k8s-app-1} >= 1"
  type: "query alert"
  name: "[kubernetes] Pod {{pod_name.name}} is CrashLoopBackOff in k8s-app-1 app"
  message: "pod {{pod_name.name}} is in CrashLoopBackOff in k8s-app-1 app. \n Adjust the thresholds of the query to suit your infrastructure."
  tags:
    - "integration:kubernetes"
```
We added in the message part "@someone@email.com" (the @ tag plus the email of the person) to get notified. However, this did not work. When I try to edit in the UI, I can see the part "Notify your Team" is empty. I would expect a field in the `DatadogMonitor` manifest but it seems to not exist yet?

I can't find anything in the docs regarding notifications: is that in progress? 

**Describe what you expected:**

**Additional environment details (Operating System, Cloud provider, etc):**
