### ISSUE TITLE
Cannot create config for Scylla integration

### ISSUE THREAD

**Issue by vavsab** [DataDog/helm-charts#405]
**Describe what happened:**
Trying to enable Scylla check on DataDog agent by [following this manual](https://docs.datadoghq.com/integrations/scylla/).
It says that I need to create `/conf.d/scylla.d/conf.yaml` file and put [this content](https://raw.githubusercontent.com/DataDog/integrations-core/master/scylla/datadog_checks/scylla/data/conf.yaml.example) there.

I tried to use [`conf.d`](https://github.com/DataDog/helm-charts/blob/ff98e40b24bb0e8d2eb3bb31d10615dfbaeb1ab9/charts/datadog/values.yaml#L254) chart property for this but I cannot use subdirectories 
```
confd: {
     ### I get an error here: Invalid value: "scylla.d/conf.yaml": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
      'scylla.d/conf.yaml': '***FIle contents file***',
},
```
**Describe what you expected:**
I would like to have a mechanism of specifying Scylla configuration. Or to know how I can do it another way.

**Steps to reproduce the issue:**
1. Create Kubernetes cluster
2. Setup Scylla db
3. Try to activate Scylla integration by [following this manual](https://docs.datadoghq.com/integrations/scylla/)

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by clamoriniere** [comment]
Hello @vavsab ,

In a kubernetes environment, the best solution to configure a check is to use the agent auto-discovery mechanism documented [here](https://docs.datadoghq.com/agent/kubernetes/integrations/?tab=kubernetes#configuration).

Instead of adding a file in `confd`, you will add kubernetes annotations on top of the scylla db Pods. The agent will detect the annotations on the running pods and schedule the scylla checks.

The `confd` option should only be used for check that needs to runs on every agent on every kubernetes nodes, or with `ad_identifiers` option.

Now I can explain why you get this error (because this is common limitation with kubernetes): the information that you in the `datadog.confd` map, create a configmap. But the "key" in `configmap.spec.data` does not support `/`. To solve it the agent don't need to have a folder for the `scylla.d/` to understand it is a configuration for the scylla check; you can directly use a file `scylla.yaml` like documented [here](https://github.com/DataDog/helm-charts/tree/main/charts/datadog#confd-and-checksd)

```yaml
datadog:
  confd:
    scylla.yaml: |-
      ad_identifiers:
        - scylladb
      init_config:
      instances:
      - prometheus_url: http://localhost:9180/metrics
```

 Let me know if this explanation helped you to configure the scylla db check.

cheers
Cedric

**Comment by vavsab** [comment]
Thanks Cedric. This helped a lot! Now I get data from Scylla into Datadog.

My config:
```yaml
datadog:
  confd:
    scylla.yaml: |-
      ad_identifiers:
        # In my case scylla is using image "scylladb/scylla:4.4.3"
        - scylla
      init_config:
      instances:
      # hostNetworking is disabled in my case
      - prometheus_url: http://%%host%%:9180/metrics
```
