### ISSUE TITLE
Cluster Checks Agent cannot find APM when running on host network

### ISSUE THREAD

**Issue by winjer** [DataDog/helm-charts#408]
**Describe what happened:**

This is being reported by `agent status` on the cluster checks agent pod:

```
=========
APM Agent
=========
  Status: Not running or unreachable on localhost:8126.
  Error: Get "http://localhost:8126/debug/vars": dial tcp 127.0.0.1:8126: connect: connection refused
```

**Describe what you expected:**

It to connect to the APM agent on the datadog agent running on the node.

**Steps to reproduce the issue:**

Deploy the cluster check runner where the APM agent is running on the kubernetes host network.

**Additional environment details (Operating System, Cloud provider, etc):**

Kubernetes cluster at AWS.

Datadog deployed using the latest helm chart.

relevant config is these values for the helm chart:

```
daemonset:
  enabled: true
clusterChecksRunner:
  enabled: true
clusterAgent:
  enabled: true
datadog:
  apm:
    enabled: true
  dogstatsd:
    useHostPort: true
    nonLocalTraffic: true
```

Elsewhere we are using the downward api to provide datadog clients with access to the local node's datadog apm port with:

```
- env:
  - name: DD_AGENT_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
```

The values file provides the capability to set the `DD_AGENT_HOST` environment variable for the cluster checks runner, but not to set it from the downward API, which I guess is what I need?
