### ISSUE TITLE
How to use Traefik integration with this DataDog agent Helm chart

### ISSUE THREAD

**Issue by nodesocket** [DataDog/helm-charts#425]
How can I use the Traefik integration (https://app.datadoghq.com/account/settings#integrations/traefik) with this DataDog agent Helm chart? The Traefik integration instructions mention something along the lines of `datadog-agent integration install -t datadog-traefik==<INTEGRATION_VERSION>
` but since I am installing the DataDog agent via this Helm chart I don't access to run `datadog-agent integration install`.

This seems like a common use-case using the Traefik integration. I know with RabbitMQ I actually just had to add some annotations to my RabbitMQ chart _(see below)_, but since Traefik is not pre-installed I don't think this is going to work.

```
 ## in RabbitMQ Helm chart
  podAnnotations:
    ad.datadoghq.com/rabbitmq.check_names: '["rabbitmq"]'
    ad.datadoghq.com/rabbitmq.init_configs: '[{}]'
    ad.datadoghq.com/rabbitmq.instances: |
      [
        {
          "rabbitmq_api_url":"%%host%%:15672/api/",
          "username":"my-user-here",
          "password":"%%env_RABBITMQ_PASSWORD%%"
        }
      ]
```

**Comment by kthompson23** [comment]
The "recommended" way is to build your own agent image with the integration(s) you want installed.

[Instructions for building a custom agent image](https://docs.datadoghq.com/agent/guide/use-community-integrations/?tab=docker)

The problem is that this chart has been written so that all the images need to share a single registry.

From values.yaml:
```# registry -- Registry to use for all Agent images (default gcr.io)
## Currently we offer Datadog Agent images on:
## GCR - use gcr.io/datadoghq (default)
## DockerHub - use docker.io/datadog
## AWS - use public.ecr.aws/datadog
registry: gcr.io/datadoghq
```

So if you create your own agent and also want to deploy the cluster-agent you'll also need to build a custom cluster-agent image.

**Comment by nodesocket** [comment]
@kthompson23 thanks. I got this working with a bit of effort. Indeed, need to build and maintain my own Docker image now for the Traefik integration. Then when doing the DataDog agent Helm install, I needed to specify the following custom values:

```yaml
agents:
  image:
    pullSecrets:
      - name: regcred  # to auth to our Docker hub account
    repository: myorg/datadog-agent-traefik
    tag: latest
datadog:
  confd:
    traefik.yaml: |-
      ad_identifiers:
        - traefik
      init_config:
      instances:
        - host: traefik-dashboard
          port: 80
 ```
