### ISSUE TITLE
Unified service tagging is not possible.

### ISSUE THREAD

**Issue by yukin01** [DataDog/helm-charts#43]
**Describe what happened:**

Cannot add labels for unified service tagging to metadata of DaemonSet.
It's also inconvenient because I have to redeploy the pod when matchLabels change.

**Describe what you expected:**

A variable should be added to `values.yaml` to add labels for unified service tagging to both metadata and template/metadata only.

https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes

**Steps to reproduce the issue:**

Run the helm template command using this `values.yaml`.

```yaml
datadog:
  agent:
    podLabels:
      tags.datadoghq.com/env: "<ENV>"
      tags.datadoghq.com/service: "<SERVICE>"
      tags.datadoghq.com/version: "<VERSION>"
```

output:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog
  labels:
    helm.sh/chart: "datadog-2.4.14"
    app.kubernetes.io/name: "datadog"
    app.kubernetes.io/instance: "datadog"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "7"
spec:
  selector:
    matchLabels:
      app: datadog
      tags.datadoghq.com/env: <ENV>
      tags.datadoghq.com/service: <SERVICE>
      tags.datadoghq.com/version: <VERSION>
  template:
    metadata:
      labels:
        app: datadog
        tags.datadoghq.com/env: <ENV>
        tags.datadoghq.com/service: <SERVICE>
        tags.datadoghq.com/version: <VERSION>
      name: datadog
```

**Additional environment details (Operating System, Cloud provider, etc):**

Chart version 2.4.14
