### ISSUE TITLE
cluster-agent-deployment is missing DD_CLUSTER_CHECKS_ENABLED env variable

### ISSUE THREAD

**Issue by danemiller** [DataDog/helm-charts#464]
I'd like to restrict cluster checks to a dedicated deployment, and disable cluster checks on the daemonset agents.  

When `datadog.clusterChecks.enabled = false`, cluster agent does not schedule any cluster checks.  This is because `DD_CLUSTER_CHECKS_ENABLED` env variable is missing.  Should we instead always set `DD_CLUSTER_CHECKS_ENABLED: "true"` in [cluster-agent-deployment.yaml](https://github.com/DataDog/helm-charts/blob/44a983ca66a14e5189738e2a8f85751dd629b9d4/charts/datadog/templates/cluster-agent-deployment.yaml#L159)?

I expect...
* daemonset: datadog (no cluster checks)
* deployment: datadog-cluster-agent (assign cluster checks to worker/runner pods)
* deployment: datadog-clusterchecks (run cluster checks assigned from cluster-agent)

...from this config:
```
datadog:
  clusterChecks:
    # disable cluster checks for daemonset, but not for clusterchecks deployment, right!?!
    enabled: false
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
    useClusterCheckRunners: true
clusterAgent:
  enabled: true
agents:
  enabled: true
clusterChecksRunner:
  enabled: true
```
