### ISSUE TITLE
Agent intake timeouts on GKE Autopilot

### ISSUE THREAD

**Issue by ags** [DataDog/helm-charts#467]
**Describe what happened:**

We installed the datadog/datadog chart using the following values:

```yaml
providers:
  gke:
    autopilot: true

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: false

datadog:
  apiKey: ...
  appKey: ...
  logs:
    enabled: true
  apm:
    socketEnabled: false
    portEnabled: true
    port: 8126
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true
    useSocketVolume: false
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
```

Container logs are being collected, and the cluster agent admission controller does appear to be correctly setting the `DD_AGENT_HOST` env var to host node IPs like `10.128.0.48`, but containers are unable to send traces or metrics to the agent. The datadog-go library produces warnings like:

```
WARN: DIAGNOSTICS Unable to reach agent intake: Post "http://10.128.0.48:8126/v0.4/traces": dial tcp 10.128.0.48:8126: i/o timeout (Client.Timeout exceeded while awaiting headers)
```

There are no VPC firewall rules other than the defaults created by GKE Autopilot. Even adding rules to allow ingress and egress from `0.0.0.0/0` doesn't seem to allow containers to talk to the agent.

The [GKE Autopilot docs](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#host_options_restrictions) say that `hostPort` is not supported, but using values based on https://docs.datadoghq.com/integrations/gke/?tab=autopilot, e.g.

```yaml
providers:
  gke:
    autopilot: true

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: false

datadog:
  apiKey: ...
  appKey: ...
  logs:
    enabled: true
  apm:
    enabled: true
```

produced the following warnings:

```
WARNING: dogstatsd with Unix socket is not supported on GKE Autopilot
WARNING: APM with Unix socket is not supported on GKE Autopilot
````

and didn't work (which was expected). Is there a way to run the agent on GKE Autopilot nodes that allows containers to submit APM traces / statsd metrics? It seems like we're missing something as APM is mentioned explicitly in the [Datadog GKE autopilot docs](https://docs.datadoghq.com/integrations/gke/?tab=autopilot), and we're a bit confused about what we're doing wrong!

**Describe what you expected:**

Containers running on GKE Autopilot would be able to send APM traces and statsd metrics to the agent running on the host by configuring clients using the `DD_AGENT_HOST` env var provided by the admission controller.

**Steps to reproduce the issue:**

1. Create a new private GKE Autopilot cluster
2. `helm install datadog-agent -f values.yml datadog/datadog`, where `values.yml` is the config above
3. Deploy a container that has the admission label and tries to use tracing / statsd:

```yaml
spec:
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"
```

```go
statsd, err := statsd.New(os.Getenv("DD_AGENT_HOST"))
if err != nil {
  log.Fatal(err)
}
defer statsd.Close()

tracer.Start(
  tracer.WithEnv("test"),
  tracer.WithService("demo"),
  tracer.WithDebugMode(true),
)
defer tracer.Stop()
```

4. Get warnings about timing out connecting to the agent, and no traces or metrics reported at runtime

**Additional environment details (Operating System, Cloud provider, etc):**

Helm chart version: datadog-2.27.2
