### ISSUE TITLE
Datadog doesn't collect logs from journald source

### ISSUE THREAD

**Issue by ziaenezhad** [DataDog/helm-charts#472]
I'm using a managed cluster that uses `Systemd-journald` service for collecting and storing logging data. I used annotations as described in the doc but no log collected so far.

### My helmfile:
```yaml
repositories:
- name: datadog
  url: https://helm.datadoghq.com

releases:
  - name: datadog
    chart: datadog/datadog
    namespace: monitoring
    version: 2.27.3
    values:
      - values/datadog.yaml.gotmpl
```

### `values/datadog.yaml.gotmpl`
```yaml
datadog:
  apiKey: {{ .Values.datadog.apiKey }}  
  site: {{ .Values.datadog.site }}  
  tags:
    - "env:{{ .Values.environment }}"

  clusterChecks:
    enabled: false

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    enabled: false
  
  kubelet:
    tlsVerify:  false
  
  processAgent:
    enabled: false
  
  orchestratorExplorer:
    enabled: false
    container_scrubbing:
      enabled: false
  
  env:
    - name: DD_CONTAINER_INCLUDE
      value: "image:registry.gitlab.com/foo/bar/core-service"
    - name: DD_CONTAINER_EXCLUDE
      value: "image:.*"
    - name: DD_ENABLE_PAYLOADS_EVENTS
      value: "false"
    - name: DD_ENABLE_PAYLOADS_SERIES
      value: "false"
    - name: DD_ENABLE_PAYLOADS_SERVICE_CHECKS
      value: "false"
    - name: DD_ENABLE_PAYLOADS_SKETCHES
      value: "false"

clusterAgent:
  enabled: false
```

### My Service deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  labels:
    tags.datadoghq.com/env: development
    tags.datadoghq.com/version: "v1.0.0"
spec:
  replicas:  1
  selector:
    matchLabels:
      app: core-service
      type: backend
  template:
    metadata:
      name: core-service
      labels:
        tags.datadoghq.com/env: development
        tags.datadoghq.com/version: "v1.0.0"
        app: core-service
        type: backend
      annotations:
        ad.datadoghq.com/core-service.logs: "[{\"source\": \"journald\", \"service\": \"core-service\"}]"        
    spec:
      containers:
        - name: core-service
          image: registry.gitlab.com/foo/bar/core-service:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:            
            ######################################################################
            ## 🐶 DATADOG
            ######################################################################
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "0.5"
```
