### ISSUE TITLE
Add CAP_CHOWN to the pod security policy and the system probe container

### ISSUE THREAD

**Issue by deadok22** [DataDog/helm-charts#474]
https://github.com/DataDog/datadog-agent/pull/9434/files was merged in Datadog Agent 7.32.0 adding a `chown(2)` syscall on startup. That call requires the CAP_CHOWN capability in some scenarios.

**Comment by Gui774ume** [comment]
Hey @deadok22 👋🏻 

Thanks for reporting the issue, could you provide us more info on the environment you're running and how we could reproduce the bug ?
(we added the cap, but thinking about it again, we're not sure why it fails in the first place)

Thank you !

**Comment by deadok22** [comment]
Hi @Gui774ume!

I was somewhat surprised by this, too. Like, the process creates the file - why would it ever fail a `chown(2)` call on that file? I haven't dug into the root cause as I was in a rush to upgrade the agent (log4shell...).

> system-probe runs as root, always deletes and recreates the file on startup, and should therefore always be capable of changing the user

That's not necessarily true. From `chown(2)` manpage:
```
Only a privileged process (Linux: one with the CAP_CHOWN capability)
may change the owner of a file. The owner of a file may change the
group of the file to any group of which that owner is a member. A
privileged process (Linux: with CAP_CHOWN) may change the group arbi‐
trarily.
```

Here's something interesting from the cluster where the deployment without CAP_CHOWN failed:
```
$ kubectl --context inf-kubernetes --namespace datadog exec -it datadog-agent-clvqk --container system-probe -- id
uid=0(root) gid=0(root) groups=0(root),1(daemon)
$ kubectl --context inf-kubernetes --namespace datadog exec -it datadog-agent-clvqk --container system-probe -- touch /var/run/sysprobe/whatever
touch: setting times of '/var/run/sysprobe/whatever': Operation not permitted
command terminated with exit code 1
$ # the seccomp profile of the sysprobe container doesn't permit the statx syscall so I'm running ls in another one
$ kubectl --context inf-kubernetes --namespace datadog exec -it datadog-agent-clvqk --container agent -- ls -la /var/run/sysprobe/whatever
-rw-r--r-- 1 root daemon 0 Dec 21 01:42 /var/run/sysprobe/whatever
$ # uid=0, gid=1
$ kubectl --context inf-kubernetes --namespace datadog exec -it datadog-agent-clvqk --container system-probe -- id dd-agent
uid=101(dd-agent) gid=0(root) groups=0(root)
```
So the chown(2) implementation didn't let a (root, root) process change (root, daemon) to (dd-agent, root). I don't have time to dig into why, but please let me know if you figure it out (most likely, [this](https://github.com/torvalds/linux/blob/6fdf886424cf8c4fff96a20189c00606327e5df6/fs/attr.c#L21-L46)  failed).

Ok, now how did we get to have those uids and gids? We're on a custom PSP in those clusters. It differs a bit from the one rendered by the helm chart - here are some relevant bits from its definition:
```
spec:
  # Permissive settings to satisfy datadog-agent.
  runAsUser:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true
  allowedCapabilities:
    - SYS_ADMIN
    - SYS_RESOURCE
    - SYS_PTRACE
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
    - IPC_LOCK
    - AUDIT_CONTROL
    - AUDIT_READ
    - CHOWN # added as part of the 7.32.2 upgrade
  defaultAddCapabilities:
    - SYS_RESOURCE # a workaround for a bug in runc - see https://github.com/opencontainers/runc/pull/2871#issuecomment-819265965
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
```

So I guess CAP_CHOWN is not necessary if the chart-rendered PSP is in use. Apologies for the bad report. Please revert the change.
