### ISSUE TITLE
Bug: datadog-cluster-agent: mountPath: Invalid value: "/conf.d": must be unique

### ISSUE THREAD

**Issue by martijnvdp** [DataDog/helm-charts#475]
**Describe what happened:**
if you set both of the following settings in the helm value file:
   datadog.kubeStateMetricsCore.enabled : true

and:
  clusterAgent.advancedConfd 
example:
```
datadog:
  kubeStateMetricsCore:
    enabled: true
clusterAgent:
  advancedConfd:
    mysql.d:
      1.yaml: |-
        cluster_check: true
        instances:
          - server: '1.2.1.1'
            port: 3306
            user: datadog
            pass: 'mypassword'
```

helm install returns: 
**Error: Deployment.apps "datadog-cluster-agent" is invalid: spec.template.spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/conf.d": must be unique**

**Describe what you expected:**
i expected that i could use both settings without issues

**Steps to reproduce the issue:**
use value file with
```
datadog: 
  kubeStateMetricsCore:
    enabled: true
clusterAgent:
  advancedConfd:
    mysql.d:
      1.yaml: |-
        cluster_check: true
        instances:
          - server: '1.2.1.1'
            port: 3306
            user: datadog
            pass: 'mypassword'
```
helm install returns: 
**Error: Deployment.apps "datadog-cluster-agent" is invalid: spec.template.spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/conf.d": must be unique**

**Additional environment details (Operating System, Cloud provider, etc):**

helm with kubernetes on aws
