### ISSUE TITLE
Admission Controller rewrites `ephemeral` volumes to `emptyDir`

### ISSUE THREAD

**Issue by seddarj** [DataDog/helm-charts#489]
**Describe what happened:**
We have a cluster on which the `datadog` helm chart is deployed and the `clusterAgent.admissionController.enabled` &  `clusterAgent.admissionController.mutateUnlabelled` values are set to `true` in order for Datadog to inject configuration through environment variables into the Pods.

Deploying a Pod that uses a Generic Ephemeral Volume (volume of type `ephemeral`) leads to a weird behavior where the volume is changed to an `emptyDir`.

**Describe what you expected:**
We expect the volume spec to remain as is and not be overridden by the datadog admission controller.

**Steps to reproduce the issue:**
* Deploy the `datadog` helm chart with `clusterAgent.admissionController.enabled` and `clusterAgent.admissionController.mutateUnlabelled` both set to `true` on a kubernetes cluster.
* Deploy the following manifest with `kubectl apply`
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - image: nginx:alpine
      name: test
      volumeMounts:
      - mountPath: /data
        name: shared-data
  volumes:
  - ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
          storageClassName: managed-premium
    name: shared-data
```
* Observe that the volume spec has changed to an `emptyDir` by running `kubectl describe pod test`

In order to fix the issue, perform the following steps:
* Delete the Pod with `kubectl delete pod test`
* Disable the admission controller by setting both `clusterAgent.admissionController.enabled` and `clusterAgent.admissionController.mutateUnlabelled` to `false` (setting only one of these is probably enough)
* Deploy the manifest with `kubectl apply`
* Observe that the volume is an Ephemeral Volume and that a PVC has been created for that Pod.

**Additional environment details (Operating System, Cloud provider, etc):**
We ran into these issues on AKS but they should happen across providers. The example Pod manifest above will only truly work on AKS because of the `storageClassName`, you can update it to match your environment for testing purposes.

We had originally opened an issue with the AKS team but it's now clear that the problem is coming from the datadog admission controller. You can see more details about our findings here: https://github.com/Azure/AKS/issues/2705#issuecomment-998812854
