### ISSUE TITLE
K8S resource labels as dd tags via labelsAsTags variable seems not to work

### ISSUE THREAD

**Issue by BlauerPulli** [DataDog/helm-charts#495]
Hey, is anyone successfully using the `datadog.kubeStateMetricsCore.labelsAsTags` value to export labels from a k8s resource as datadog tag? This doesn't work for me though i respect the label transformation done by kube-state-metrics.
Introduced with: https://github.com/DataDog/helm-charts/commit/20748841652b085e12df9b85fc7f0cfbf9f4b16b

**Steps to reproduce the issue:**
Existing label is: `helm.sh/chart: datadog-2.27.8`
Add the following to your values.yaml file:

```
datadog:
  kubeStateMetricsCore:
    labelsAsTags:
      deployment:
        label_helm_sh_chart: label_helm_sh_chart
```

**Additional environment details (Operating System, Cloud provider, etc):**
datadog chart version: 2.28.7
aks: 1.20.7

**Comment by BlauerPulli** [comment]
Found out that:
1. The prefix `label_` was redundant, as it is added in the [agent code](https://github.com/DataDog/datadog-agent/blob/acd6bcb7927c56e069d67b7acb6bfed425673a5f/pkg/collector/corechecks/cluster/ksm/kubernetes_state.go#L508)

2. As the configuration suggerates only `kubernetes_states.*` metrics are affected.

3. It also depends on the respective k8s resource on which metric subset the tags are appearing. In the example below labels on deployment resources are aimed and only added to `kubernetes_state.deployment.*` metrics.
Another example are labels on k8s nodes which only are shown up on `kubernetes_state.node.*` and on a few `kubernetes_state_container.*` metrics.

In my opinion such information should have been added in the commit (at least a working example in the values.yaml file).

For me it works now with:
-> Label on k8s deployment resource is: helm.sh/chart: datadog-2.27.8
```
datadog:
  kubeStateMetricsCore:
    labelsAsTags:
      deployment:
        helm_sh_chart: helm_sh_chart
```
