### ISSUE TITLE
auto_multi_line_detection not supported

### ISSUE THREAD

**Issue by joeybenamy** [DataDog/helm-charts#530]
It appears that [logs_config.auto_multi_line_detection](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=helm#automatic-multi-line-aggregation) is not supported in the Helm chart.  Is there a way to configure auto_multi_line_detection for the Datadog agent in Helm?

**Comment by L3n41c** [comment]
Hello,

With the current version of the Helm chart, you can try to set the `DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION` environment variable with a `values.yaml` that would contain:
```yaml
datadog:
  env:
    - name: "DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION"
      value: "true"
```
