### ISSUE TITLE
Unable to Read API Key from SecretProviderClass

### ISSUE THREAD

**Issue by RobbieMcKinstry** [DataDog/helm-charts#534]
Hi DataDog team! I'm having a really tough time configuring this chart to use a secret generated by the `SecretProviderClass`.

For background, I'm on AWS EKS, Kubernetes 1.21. I've configured EKS integration with AWS SSM such that secrets are populated with values from AWS Parameter Store. I'm attempting to deploy the DD chart using `datadog.apiKeyExistingSecret` to refer to the `Secret` populated by parameter store. I've been able to validate my API key is correct by deploying with `--set datadog.apiKey={{value}}` previously. I've also been able to validate that the `Secret` is populated correctly, and can be mounted to DD pods in the namespace when connected via a `Service Account` -- this also implies that my SA EKS annotation is correct and points to a valid role arn.

I suspect I'm missing something obvious, but I've spent many hours pouring over every ounce of the documentation, and I can't find anything to clue me in on a solution.

What I've observed is that both the ClusterAgent and the DaemonSet containers are emitting an `API Key invalid` error message:

From the process agent: 

```
2022-02-03 21:39:01 UTC | PROCESS | ERROR | (pkg/forwarder/transaction/transaction.go:344 in internalProcess) | API Key invalid, dropping transaction for https://process.datadoghq.com/api/v1/container
```

From the ClusterAgent:
```
2022-02-03 21:39:26 UTC | CLUSTER | ERROR | (pkg/forwarder/transaction/transaction.go:344 in internalProcess) | API Key invalid, dropping transaction for https://1-16-0-app.agent.datadoghq.com/api/v1/check_run?api_key=<DATADOG_API_KEY>
```

I expected the `ClusterAgent` deployment and the `DaemonSet` deployment to be able to load the API key from the secret `datadog-api-key`.

## Code Snippets

**Charts.yml**
```yaml
apiVersion: v2
name: datadog
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.1.0
dependencies:
- name: "datadog"
  version: "2.29.0"
  repository: "https://helm.datadoghq.com"
```

----------
**SecretProviderClass:**

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "datadog-api-key"
  namespace: "datadog"
spec:
  provider: "aws"
  parameters:
    objects: |
        - objectName: "{{My-SSM-Path}}"
          objectType: "ssmparameter"
          objectAlias: "api-key"
        
  secretObjects:
    - data:
      - key: "api-key"
        objectName: "api-key"
      secretName: "datadog-api-key"
      type: "Opaque"
```

----------
**values.yaml**

**NOTE:** I tried this with and without mounting the secrets onto the pod using volumes. I wasn't sure if this was going to be necessary or not. I looked at using the [`SecretBackendCommand`](https://docs.datadoghq.com/agent/guide/secrets-management/?tab=linux#kubernetes) is associated with a volume mount, but that seemed antithetical to providing a value with `apiKeyExistingSecret`, which seems to be the preferred approach, whereas the SecretBackendCommand is for reading secrets into the DD configuration files.

```yaml
env: "dev"

targetSystem: "linux"

datadog:
  registry: "public.ecr.aws/datadog"
  apiKeyExistingSecret: "datadog-api-key"
  networkMonitoring:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  agents:
    rbac:
      serviceAccountAnnotations:
        eks.amazonaws.com/role-arn: "{{MY ROLE ARN}}"
  clusterAgent:
    rbac:
      serviceAccountAnnotations:
        eks.amazonaws.com/role-arn: "{{MY ROLE ARN}}"
    volumeMounts:
      - name: "aws-secrets-inline"
        mountPath: "/mnt/aws-secrets"
        readOnly: true
    volumes:
      - name: "aws-secrets-inline"
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "datadog-api-key"
```

## Repro Steps

1. Create a secret in AWS Parameter Store containing the DD API Key.
2. Create an IAM role authorized to read that ParameterStore secret. Copy the role arn for this Role.
3. Create a new chart, pasting the `values.yaml` file above, replacing `{{MY ROLE ARN}}` with the copied role arn from the previous step.
4. Copy the `SecretsProviderClass` indicated above into your chart's `templates` directory.
5. Deploy the chart with helm to an EKS cluster.

----

**Thank you for your assistance.**
