### ISSUE TITLE
datadog-cluster-checks-runner looking for default secret dd-appsecret

### ISSUE THREAD

**Issue by govind-bt** [DataDog/helm-charts#564]
We are seeing datadog-cluster-checks-runner going into Init:CreateContainerConfigError looking for secret dd-appsecret. Any way we can override this with our secret instead of looking for a default one?

```
datadog-cluster-checks-runner-756d6cd8c9-tzbv2   0/1     Init:CreateContainerConfigError   0          2d18h

Events:
  Type     Reason  Age                       From     Message
  ----     ------  ----                      ----     -------
  Normal   Pulled  19m (x18435 over 2d18h)   kubelet  Container image "gcr.io/datadoghq/agent:latest" already present on machine
  Warning  Failed  9m2s (x18481 over 2d18h)  kubelet  Error: secret "dd-appsecret" not found
```

Snippet from datadog-agent.yaml

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  clusterName: eks-engr
  credentials:
    apiSecret:
      keyName: "api-key"
      secretName: "dd-access-secrets"
    appSecret:
      keyName: "app-key"
      secretName: "dd-access-secrets"
  clusterAgent:
    replicas: 2

  clusterChecksRunner:
    enabled: true
    image:
      name: "gcr.io/datadoghq/agent:latest"
    rbac:
      create: true
    env:
      - name: DD_COLLECT_GCE_TAGS
        value: "false"
```
