### ISSUE TITLE
Custom environment values not being double quoted

### ISSUE THREAD

**Issue by InAnimaTe** [DataDog/helm-charts#57]
**Describe what happened:**
Values for custom environment variables passed to the main container-agent are not being quoted.

```
          - name: DD_LOGS_CONFIG_USE_HTTP
            value: true
          - name: DD_LOGS_CONFIG_LOGS_DD_URL
            value: pvtlink.logs.datadoghq.com:443
```

**Describe what you expected:**
These values to be double quoted as they were when sourcing the chart from the Helm Stable repo.

```
          - name: DD_LOGS_CONFIG_USE_HTTP
            value: "true"
          - name: DD_LOGS_CONFIG_LOGS_DD_URL
            value: "pvtlink.logs.datadoghq.com:443"
```

**Steps to reproduce the issue:**
`helm template` 

**Additional environment details (Operating System, Cloud provider, etc):**
Helm 2.14.x

I looked through the commits on this repo and even tried the first release and none of them appear to quote correctly. Not really sure what's going on but this works fine with the chart sourced from the legacy helm stable repo.

**Comment by Simwar** [comment]
Hi @InAnimaTe 

I tested myself with the datadog helm chart and my agents are getting deployed correctly.

I’m using:

```
containers:
    agent:
      ## @param env - list - required
      ## Additional environment variables for the agent container.
      #
      env:
        - name: DD_LOGS_CONFIG_USE_HTTP
          value: "true"
        - name: DD_LOGS_CONFIG_LOGS_DD_URL
          value: "pvtlink.logs.datadoghq.com:443"
```

My agents are deployed correctly and when I run `agent config` in the agent container I can see:

```
logs_config:
  logs_dd_url: pvtlink.logs.datadoghq.com:443
```

So no issues on my side.
When I do `kubectl get pod <agent-pod> -o yaml` I see this:

```
- name: DD_LOGS_CONFIG_USE_HTTP
  value: "true"
- name: DD_LOGS_CONFIG_LOGS_DD_URL
  value: pvtlink.logs.datadoghq.com:443
```

but this doesn’t introduce any issues on the deployment or the config of the agent, as we can see in the status:

```
==========
Logs Agent
==========

    Sending compressed logs in HTTPS to pvtlink.logs.datadoghq.com on port 443
```
