### ISSUE TITLE
When `targetSystem=windows`, Helm chart should not attempt to deploy `cluster-agent`

### ISSUE THREAD

**Issue by Jberlinsky** [DataDog/helm-charts#574]
**Describe what happened:**

When executing a Helm deployment in line with the documentation found throughout Datadog's documentation and UI (i.e. `helm install datadog datadog/datadog -f values.yaml --targetSystem=windows ...`, the Helm chart attempts to deploy `cluster-agent`, which can ["only be deployed on Linux nodes"](https://docs.datadoghq.com/agent/cluster_agent/setup/?tab=helm).

**Describe what you expected:**

Helm should Do The Right Thing (TM) and not attempt to deploy `cluster-agent` if `targetSystem==windows`

**Steps to reproduce the issue:**

See above

**Additional environment details (Operating System, Cloud provider, etc):**

Windows nodes in GKE cluster

**Comment by clamoriniere** [comment]
Hi @Jberlinsky

Thanks for reporting this issue.
have you followed the [windows deployment documentation](https://github.com/DataDog/helm-charts/tree/main/charts/datadog#how-to-join-a-cluster-agent-from-another-helm-chart-deployment-linux) and set the parameter `existingClusterAgent.join:true`

The cluster-agent is a key component for the Agent deployment on Kubernetes (windows and linux). We recommend to deploy first the helm chart to target the linux Node and deploy the `cluster-agent`, Then deploy the a second instance of the datadog chart to target the windows nodes. 

with at least the following option set

```yaml
targetSystem: windows

existingClusterAgent:
  join: true
  serviceName: "<EXISTING_DCA_SERVICE_NAME>" # from the other datadog helm chart release
  tokenSecretName: "<EXISTING_DCA_SECRET_NAME>" # from the other datadog helm chart release

# Disabled datadogMetrics deployment since it should have been already deployed with the other chart release.
datadog-crds:
  crds:
    datadogMetrics: false

# Disable kube-state-metrics deployment
datadog:
  kubeStateMetricsEnabled: false]
```

please let us know if if solve the deployment problem.
