### ISSUE TITLE
pod logging doesn't work well after configure logs enabled

### ISSUE THREAD

**Issue by socar-grab** [DataDog/helm-charts#581]
**Describe what happened:**
I have configured datadog helm-chart with logs set to enabled. At this time, I cannot show logs in datadog dashboard. Doesn't Datadog agent automatically get the logs of all pods on the Node?

As shown below, it seems that logs are being collected only when the annotation must be attached to the Pods I want to collect logs from

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    tags.datadoghq.com/env: "test-env"
    tags.datadoghq.com/service: "test-service"
    tags.datadoghq.com/version: 0.0.1
spec:
    ....
```

**Describe what you expected:**
I want to automatically get the logs of all Pods  in the cluster without pod annotation.

**Steps to reproduce the issue:**
- configured logs enabled true

**Additional environment details (Operating System, Cloud provider, etc):**
Provider : 1.21.10-gke
