### ISSUE TITLE
 processAgent && traceAgent are not respecting logLevel: off

### ISSUE THREAD

**Issue by denisp13** [DataDog/helm-charts#602]
**Describe what happened:**
Rolling out DataDog agents with disabled logging of processAgent && traceAgent causing pod crashes and the rollout is rolled back

using the following helm values:
```# Agents config
agents:
  containers:
    agent:
      logLevel: off
    processAgent:
      logLevel: off
    traceAgent:
      logLevel: off
    systemProbe:
      logLevel: off
    securityAgent:
      logLevel: off
```
Datadog pods are crushing and restarting with an error:
`critical: Cannot create logger: unknown log level: false`

although the value is set as off , the DD_LOG_LEVEL is defined as false
```      
  - name: DD_LOG_LEVEL
          value: 'false'
```
          
**Describe what you expected:**
Helm chart is rolled out and processAgent && traceAgent are not producing logs

**Steps to reproduce the issue:**
Rollout installation of Datadog K8S chart with disabled agents logs 

**Additional environment details (Operating System, Cloud provider, etc):**
AKS - 1.20.1
Chart version - 2.32.0

**Comment by ahmed-mez** [comment]
Hi @denisp13 

This is happening because `off` is keyword in the Yaml syntax it indicates a false boolean.

Please try adding quotes, it should work:
 
```yaml
agents:
  containers:
    agent:
      logLevel: "off"
    processAgent:
      logLevel: "off"
    traceAgent:
      logLevel: "off"
    systemProbe:
      logLevel: "off"
    securityAgent:
      logLevel: "off"
```

Thanks!
