### ISSUE TITLE
Error when collecting VPA recommendation metrics

### ISSUE THREAD

**Issue by luizsfer** [DataDog/helm-charts#603]
**Describe what happened:**
Error when collecting VPA (VerticalPodAutoscalers) recommendation metrics. The existing metric in KMS (kube-metrics-state) was not being sent to DataDog.

**Describe what you expected:**
The data generated by the VPA, transmitted to the KMS should be collected as metrics by the DataDog agent.

**Steps to reproduce the issue:**
Install the VPA chart and also the DataDog agent chart

**Additional environment details (Operating System, Cloud provider, etc):**
Any environment.

**Comment by JacksonDavenport** [comment]
Hey @luizsfer 
We're taking a look at it. One wrinkle is that VPA isn't always enabled by default in Kubernetes clusters. This could result in spammy logs like the following each check run:

> E0421 23:32:43.221328       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/reflector.go:167: Failed to watch *v1beta2.VerticalPodAutoscaler: failed to list *v1beta2.VerticalPodAutoscaler: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)

So this might get put on hold while we take a look at that. In the meantime you can enable this manually by updating your Helm configuration like in the below example to create a custom `kubernetes_state_core.yaml` file. This should get picked up by the Cluster Agent for the check, rather than the pre-existing `kubernetes_state_core.yaml.default` file.

```yaml
datadog:
  #(...)
clusterAgent:
  confd:
      kubernetes_state_core.yaml: |-
        init_config:
        instances:
          - collectors:
              - secrets
              - nodes
              - pods
              - services
              - resourcequotas
              - replicationcontrollers
              - limitranges
              - persistentvolumeclaims
              - persistentvolumes
              - namespaces
              - endpoints
              - daemonsets
              - deployments
              - replicasets
              - statefulsets
              - cronjobs
              - jobs
              - horizontalpodautoscalers
              - poddisruptionbudgets
              - storageclasses
              - volumeattachments
              - verticalpodautoscalers
```
