### ISSUE TITLE
Auto discovery of pod (service) logs 

### ISSUE THREAD

**Issue by Sandeepb-nextcar** [DataDog/helm-charts#607]
**Describe what happened:**
I'm not able to see my service in the inventory when i added annotations to deployment spec

**Describe what you expected:**
I did use containerCollectAll: true and added  Annotation "ad.datadoghq.com/nginx.logs: '[{"source":"nginx","service":"webapp"}]'"
but dont see service showing up in logs.

**Steps to reproduce the issue:**
do i need to set this containerCollectAll:true or false in order  to show up my service.

**Additional environment details (Operating System, Cloud provider, etc):**
EKS(AWS)

**Comment by clamoriniere** [comment]
Hi @Sandeepb-nextcar 

the annotations need to be added to the PodTemplate spec inside the deployment.

Could you confirm that you have something like this example?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        ad.datadoghq.com/nginx.check_names: '["nginx"]'
        ad.datadoghq.com/nginx.init_configs: '[{}]'
        ad.datadoghq.com/nginx.instances: '[{"nginx_status_url": "http://%%host%%/nginx_status", "tags": "%%tags%%"}]'
        ad.datadoghq.com/nginx.logs: '[{"type": "docker","image": "nginx","service": "nginx","source": "nginx"}]'
    spec:
      containers:
        - name: nginx
          image: nginx:latest
 ```
