### ISSUE TITLE
Allow for internal UDP datadog service without requiring internalTrafficPolicy

### ISSUE THREAD

**Issue by rexroof** [DataDog/helm-charts#608]
**Describe what happened:**
I want to publish metrics to my datadog agent internally to dogstatsd.
Is there a reason that I need to have hostPorts enabled?  I just want to send traffic internally to a kubernetes service. 
Why is the internalTrafficPolicy set if the hostPort is not set? 

is there a reason I need to publish hostPorts at all if I'm not trying to publish metrics on the host interface?

**Describe what you expected:**
Expected service `datadog` with 8125/UDP port to be created

**Steps to reproduce the issue:**

installed datadog helm chart using these values:

```
  datadog:
      apiKeyExistingSecret: "datadog-apikey"
      clusterName: "may-sandbox-cluster"
      agents:
        localService:
          forceLocalServiceEnabled: true
      dogstatsd:
        enabled: true
      logs:
        enabled: true
        containerCollectAll: true
      systemProbe:
        collectDNSStats: false
```
**Additional environment details (Operating System, Cloud provider, etc):**

AWS EKS kubernetes version 1.20
