### ISSUE TITLE
Postgres agent fails to start check and report metrics, though I can view that under agent configcheck/clusterchecks

### ISSUE THREAD

**Issue by fgielow** [DataDog/helm-charts#635]
**Describe what happened:**
Postgres fails to report metrics. I can view it listed under `agent configcheck` and `agent clusterchecks` but not under `agent status`.

**Describe what you expected:**
Postgres reports metrics as expected and I can see it listed under `agent status`

**Steps to reproduce the issue:**

Initially, I am running an Azure hosted Postgres v12, which is not listed explicitly under datadog's but since I can follow all the steps and datadog only needs to be able to run SQL commands there, I'd expec that to work.

Using docs for [RDS with the kubernetes agent](https://docs.datadoghq.com/database_monitoring/setup_postgres/rds/?tab=kubernetes) as basis, I have:
- Configured required parameters and enabled `shared_preload_libraries`
- Created the datadog user
- Added all required permissions
- Followed verification steps and confirm they succeed
- Deployed the kubernetes agent

Below is the yaml configuration for chart parameters that I am running, displaying only variables that differ from defaults:
```yaml
clusterAgent:
  confd:
    postgres.yaml: |
      cluster_check: true
      init_config:
      instances:
        - dbm: true
          host: -REDACTED-
          port: 5432
          username: datadog
          password: -REDACTED-
  enabled: true
datadog:
  apiKey: -REDACTED-
  apm:
    portEnabled: true
  appKey: -REDACTED-
  clusterAgent:
    enabled: true
    metricsProvider:
      enabled: true
  clusterChecks:
    enabled: true
  collectEvents: true
  kubelet:
    hostCAPath: /etc/kubernetes/certs/kubeletserver.crt
    tlsVerify: false
  leaderElection: true
  logs:
    containerCollectAll: true
    enabled: true
  rbac:
    create: true
  site: datadoghq.eu
targetSystem: linux


```

Below are the outputs from the agent commands:

$ **agent configcheck**
```yaml
2022-05-20 20:00:03 UTC | CLUSTER | WARN | (pkg/util/log/log.go:592 in func1) | Unknown environment variable: DD_LEADER_LEASE_NAME
2022-05-20 20:00:03 UTC | CLUSTER | WARN | (pkg/util/log/log.go:592 in func1) | Unknown environment variable: DD_CLUSTER_AGENT_TOKEN_NAME
2022-05-20 20:00:03 UTC | CLUSTER | WARN | (pkg/util/log/log.go:592 in func1) | Agent configuration relax permissions constraint on the secret backend cmd, Group can read and exec
2022-05-20 20:00:03 UTC | CLUSTER | INFO | (pkg/util/log/log.go:572 in func1) | Features detected from environment: kubernetes,orchestratorexplorer

=== kubernetes_apiserver check ===
Configuration provider: file
Configuration source: file:/etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml.default
Instance ID: kubernetes_apiserver:d884b5186b651429
{}
~
===

=== orchestrator check ===
Configuration provider: file
Configuration source: file:/etc/datadog-agent/conf.d/orchestrator.d/conf.yaml.default
Instance ID: orchestrator:d884b5186b651429
{}
~
Auto-discovery IDs:
* _kube_orchestrator
===

=== postgres cluster check ===
Configuration provider: file
Configuration source: file:/etc/datadog-agent/conf.d/postgres.yaml
Instance ID: postgres:80f22d438a13674
dbm: true
host: -REDACTED-
password: -REDACTED-
port: 5432
username: datadog
~
===

```

$ **agent clusterchecks**
```yaml

2022-05-20 20:00:38 UTC | CLUSTER | WARN | (pkg/util/log/log.go:592 in func1) | Unknown environment variable: DD_LEADER_LEASE_NAME
2022-05-20 20:00:38 UTC | CLUSTER | WARN | (pkg/util/log/log.go:592 in func1) | Unknown environment variable: DD_CLUSTER_AGENT_TOKEN_NAME
2022-05-20 20:00:38 UTC | CLUSTER | WARN | (pkg/util/log/log.go:592 in func1) | Agent configuration relax permissions constraint on the secret backend cmd, Group can read and exec
2022-05-20 20:00:38 UTC | CLUSTER | INFO | (pkg/util/log/log.go:572 in func1) | Features detected from environment: kubernetes,orchestratorexplorer
=== 2 agents reporting ===

Name                             Running checks
aks-rancher-REDACTED-0-c-REDACTED 1
aks-rancher-REDACTED-1-c-REDACTED 0

===== Checks on aks-rancher-REDACTED-0-c-REDACTED=====

=== postgres check ===
Configuration provider: file
Configuration source: file:/etc/datadog-agent/conf.d/postgres.yaml
Instance ID: postgres:ffaf89b6488c9ef6
dbm: true
empty_default_hostname: true
host: -REDACTED-
password: -REDACTED-
port: 5432
tags:
- cluster_name: -REDACTED-
- kube_cluster_name: -REDACTED-
username: datadog
~
===

===== 0 Pod-backed Endpoints-Checks scheduled =====

```

What catches my attention above is the comment "0 Pod-backed Endpoints-Checks scheduled" - is there any further configuration or env vars required so postgres checker gets scheduled?

$ **agent status**
```yaml
2022-05-20 20:01:17 UTC | CLUSTER | WARN | (pkg/util/log/log.go:592 in func1) | Unknown environment variable: DD_LEADER_LEASE_NAME
2022-05-20 20:01:17 UTC | CLUSTER | WARN | (pkg/util/log/log.go:592 in func1) | Unknown environment variable: DD_CLUSTER_AGENT_TOKEN_NAME
2022-05-20 20:01:17 UTC | CLUSTER | WARN | (pkg/util/log/log.go:592 in func1) | Agent configuration relax permissions constraint on the secret backend cmd, Group can read and exec
Getting the status from the agent.
2022-05-20 20:01:17 UTC | CLUSTER | INFO | (pkg/util/log/log.go:572 in func1) | Features detected from environment: kubernetes,orchestratorexplorer
===============================
Datadog Cluster Agent (v1.19.0)
===============================

  Status date: 2022-05-20 20:01:17.137 UTC (1653076877137)
  Agent start: 2022-05-20 19:39:03.417 UTC (1653075543417)
  Pid: 1
  Go Version: go1.17.6
  Build arch: amd64
  Agent flavor: cluster_agent
  Check Runners: 4
  Log Level: INFO

  Paths
  =====
    Config File: /etc/datadog-agent/datadog-cluster.yaml
    conf.d: /etc/datadog-agent/conf.d

  Clocks
  ======
    System time: 2022-05-20 20:01:17.137 UTC (1653076877137)

  Hostnames
  =========
    host_aliases: [15031022-32a8-4ba7-b418-8a316e94ead1]
    hostname: -REDACTED-
    socket-fqdn: datadog-agent-cluster-agent-565684865b-tzgst
    socket-hostname: datadog-agent-cluster-agent-565684865b-tzgst
    hostname provider: container
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance and other providers already retrieve non-default hostnames
      azure: azure_hostname_style is set to 'os'
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: GCE metadata API error: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

  Metadata
  ========

Leader Election
===============
  Leader Election Status:  Running
  Leader Name is: datadog-agent-cluster-agent-565684865b-tzgst
  Last Acquisition of the lease: Fri, 20 May 2022 19:40:57 UTC
  Renewed leadership: Fri, 20 May 2022 20:01:14 UTC
  Number of leader transitions: 24 transitions

Custom Metrics Server
=====================
  Disabled: The external metrics provider is not enabled on the Cluster Agent

Cluster Checks Dispatching
==========================
  Status: Leader, serving requests
  Active agents: 2
  Check Configurations: 1
    - Dispatched: 1
    - Unassigned: 0

Admission Controller
====================
  Disabled: The admission controller is not enabled on the Cluster Agent


=========
Collector
=========

  Running Checks
  ==============

    kubernetes_apiserver
    --------------------
      Instance ID: kubernetes_apiserver [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml.default
      Total Runs: 89
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 1, Total: 7
      Service Checks: Last Run: 3, Total: 243
      Average Execution Time : 2.014s
      Last Execution Date : 2022-05-20 20:01:07 UTC (1653076867000)
      Last Successful Execution Date : 2022-05-20 20:01:07 UTC (1653076867000)


    orchestrator
    ------------
      Instance ID: orchestrator:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/orchestrator.d/conf.yaml.default
      Total Runs: 134
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 6ms
      Last Execution Date : 2022-05-20 20:01:15 UTC (1653076875000)
      Last Successful Execution Date : 2022-05-20 20:01:15 UTC (1653076875000)

=========
Forwarder
=========

  Transactions
  ============
    Cluster: 7
    ClusterRole: 14
    ClusterRoleBinding: 14
    CronJob: 0
    DaemonSet: 7
    Deployment: 7
    Dropped: 0
    HighPriorityQueueFull: 0
    Ingress: 0
    Job: 0
    Node: 20
    PersistentVolume: 7
    PersistentVolumeClaim: 7
    Pod: 0
    ReplicaSet: 14
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Role: 7
    RoleBinding: 7
    Service: 7
    ServiceAccount: 7
    StatefulSet: 7

  Transaction Successes
  =====================
    Total number: 311
    Successes By Endpoint:
      check_run_v1: 88
      intake: 3
      orchestrator: 132
      series_v1: 88

  On-disk storage
  ===============
    On-disk storage is disabled. Configure `forwarder_storage_max_size_in_bytes` to enable it.

==========
Endpoints
==========
  https://app.datadoghq.eu - API Key ending with:
      - REDACTED

=====================
Orchestrator Explorer
=====================
  Collection Status: The collection is at least partially running since the cache has been populated.
  Cluster Name: -REDACTED-
  Cluster ID: -REDACTED-
  Container scrubbing: enabled

  ======================
  Orchestrator Endpoints
  ======================
    https://orchestrator.datadoghq.eu - API Key ending with: REDACTED

  ===========
  Cache Stats
  ===========
    Elements in the cache: 556

    ClusterRoleBinding
      Last Run: (Hits: 109 Miss: 0) | Total: (Hits: 12535 Miss: 763)

    ClusterRole
      Last Run: (Hits: 124 Miss: 0) | Total: (Hits: 14260 Miss: 868)

    Cluster
      Last Run: (Hits: 1 Miss: 0) | Total: (Hits: 115 Miss: 7)

    CronJob
      Last Run: (Hits: 0 Miss: 0) | Total: (Hits: 0 Miss: 0)

    DaemonSet
      Last Run: (Hits: 10 Miss: 0) | Total: (Hits: 1150 Miss: 70)

    Deployment
      Last Run: (Hits: 25 Miss: 0) | Total: (Hits: 2875 Miss: 175)

    Job
      Last Run: (Hits: 0 Miss: 0) | Total: (Hits: 0 Miss: 0)

    Node
      Last Run: (Hits: 1 Miss: 1) | Total: (Hits: 219 Miss: 25)

    PersistentVolumeClaim
      Last Run: (Hits: 1 Miss: 0) | Total: (Hits: 115 Miss: 7)

    PersistentVolume
      Last Run: (Hits: 1 Miss: 0) | Total: (Hits: 115 Miss: 7)

    Pod
      Last Run: (Hits: 0 Miss: 0) | Total: (Hits: 0 Miss: 0)

    ReplicaSet
      Last Run: (Hits: 105 Miss: 0) | Total: (Hits: 12075 Miss: 735)

    RoleBinding
      Last Run: (Hits: 34 Miss: 0) | Total: (Hits: 3910 Miss: 238)

    Role
      Last Run: (Hits: 20 Miss: 0) | Total: (Hits: 2300 Miss: 140)

    ServiceAccount
      Last Run: (Hits: 77 Miss: 0) | Total: (Hits: 8855 Miss: 539)

    Service
      Last Run: (Hits: 27 Miss: 0) | Total: (Hits: 3105 Miss: 189)

    StatefulSet
      Last Run: (Hits: 2 Miss: 0) | Total: (Hits: 230 Miss: 14)

```

**Additional environment details (Operating System, Cloud provider, etc):**

I've added the following env variables to running containers:

```yaml
- name: DD_AGENT_HOST
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
- name: DD_ENV
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['tags.datadoghq.com/env']
- name: DD_SERVICE
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['tags.datadoghq.com/service']
- name: DD_VERSION
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['tags.datadoghq.com/version']
- name: DD_TRACE_SAMPLE_RATE
  value: "1"
- name: DD_PROFILING_ENABLED
  value: "true"
```
