### ISSUE TITLE
AKS cluster using `datadog.kubelet.hostCAPath` has to set `tlsVerify: false` when upgrading

### ISSUE THREAD

**Issue by bamarch** [DataDog/helm-charts#636]
**Describe what happened:**

We are using AKS and configured as per https://docs.datadoghq.com/agent/kubernetes/distributions/?tab=helm#AKS.

This is our config snippet

```yaml
  kubelet:
    # datadog.kubelet.host -- Override kubelet IP
    host:
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    # AKS workaround recommended by Datadog https://github.com/DataDog/helm-charts/issues/114#issuecomment-768413178
    # ca.crt mounted by the service account is not the one used to target Kubelet
    # Kubelet cert does not have SAN for node IP, nor the reverse-lookup of the node IP
    hostCAPath: /etc/kubernetes/certs/kubeletserver.crt
```

Upgrading from `2.27.8` to `2.32.6` and keeping the configuration the same results in a status failure for "Kubelet".

```

    kubelet (7.2.1)
    ---------------
      Instance ID: kubelet:5bbc63f3938c02f4 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubelet.d/conf.yaml.default
      Total Runs: 1
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 2ms
      Last Execution Date : 2022-05-23 12:48:43 UTC (1653310123000)
      Last Successful Execution Date : Never
      Error: Unable to detect the kubelet URL automatically: impossible to reach Kubelet with host: aks-usrhighmem02-12168730-vmss000002. Please check if your setup requires kubelet_tls_verify = false. Activate debug logs to see all attempts made
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1071, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kubelet/kubelet.py", line 295, in check
          raise CheckException("Unable to detect the kubelet URL automatically: " + kubelet_conn_info.get('err', ''))
      datadog_checks.base.errors.CheckException: Unable to detect the kubelet URL automatically: impossible to reach Kubelet with host: aks-usrhighmem02-12168730-vmss000002. Please check if your setup requires kubelet_tls_verify = false. Activate debug logs to see all attempts made
```

We don't get logs in the Datadog app for this cluster anymore

It looks like the agent was upgraded to `7.35.0`, I've tested with `7.34.0` and this issue isn't present

**Describe what you expected:**

The "Kubelet" status check would remain working and logs would continue being visible in the Datadog app

**Steps to reproduce the issue:**

1: Use AKS

2: Configure the helm chart as per the docs from https://docs.datadoghq.com/agent/kubernetes/distributions/?tab=helm#AKS for using the support added in https://github.com/DataDog/helm-charts/pull/195

```yaml
  kubelet:
    # datadog.kubelet.host -- Override kubelet IP
    host:
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    # AKS workaround recommended by Datadog https://github.com/DataDog/helm-charts/issues/114#issuecomment-768413178
    # ca.crt mounted by the service account is not the one used to target Kubelet
    # Kubelet cert does not have SAN for node IP, nor the reverse-lookup of the node IP
    hostCAPath: /etc/kubernetes/certs/kubeletserver.crt
```

**Additional environment details (Operating System, Cloud provider, etc):**

AKS cluster
Using private networking with public DNS

---

The error message itself states "Error: Unable to detect the kubelet URL automatically: impossible to reach Kubelet with host: aks-usrhighmem02-12168730-vmss000002. Please check if your setup requires kubelet_tls_verify = false. Activate debug logs to see all attempts made"

Adding `kubelet.tlsVerify: false` to the chart values does fix the issue, so we aren't blocked and there is a workaround (i.e. accept the slightly weakened security posture)

I'm mainly wondering if support has dropped for the method of using `hostCAPath` to fix this issue, and whether documentation could do with updating if that's true? Or something in the changelog to warn people upgrading. Otherwise maybe it is an unintentional regression in the underlying `kubelet.py` core integration
