### ISSUE TITLE
cluster-agent should warn about missing app key if external metrics is set

### ISSUE THREAD

**Issue by fredleger** [DataDog/helm-charts#680]
**Describe what happened:**
- deployed datadog with cluster-agent enabled
- wanted to use DD as an external metrics provider
- forget about missing app key
- spend a couple of hours debugging a strange error message ( API error 403 Forbidden: {"status":********@datadoghq.com"}, strconv.Atoi: parsing "": invalid syntax])

**Describe what you expected:**
- a clear message stating that the 403 is indeed because i don't have an app-key defined
- a mention in the doc (https://docs.datadoghq.com/fr/containers/cluster_agent/troubleshooting/) that you should double check your application key

**Steps to reproduce the issue:**
- usual datadog with helm deploy + 

```yaml
        clusterAgent:
          enabled: true
          admissionController:
            enabled: true
          metricsProvider:
            enabled: true
            useDatadogMetrics: true
```
- no `datadog.appKey` set

**Additional environment details (Operating System, Cloud provider, etc):**
- linux
- scaleway cloud proivider with kapsule cluster

**Ideas**
I guess this can be avoided by a simple mention in the troobleshooting documentation and maybe a check at server bootstrap in order to check if external metrics is configured and the application key is missing we reached a dead end. For the record it also slow down the startup of the cluster-agent so this is a double win fix :-)
