### ISSUE TITLE
Im using the daemonset deployed with the official helm chart. Why am I seeing "Reached the limit on the maximum number of files in use: 100" errors?

### ISSUE THREAD

**Issue by red8888** [DataDog/helm-charts#705]
**Describe what happened:**
I tried to open this issue in the dd agent repo but was directed here: https://github.com/DataDog/datadog-agent/issues/12862

When I look at the agent daemonset logs I see this:
`| CORE | WARN | (pkg/logs/internal/launchers/file/file_provider.go:87 in filesToTail) | Reached the limit on the maximum number of files in use: 100
`

**Describe what you expected:**
I'm running the daemonset which is reading from stdout. What is this error related to? What files is it watching thats filling up the queue? I have not configured the daemonset agent to watch any files.

**Additional environment details (Operating System, Cloud provider, etc):**

```
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: datadog-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: datadog-agent
    app.kubernetes.io/version: "7"
    helm.sh/chart: datadog-2.35.6
```
