### ISSUE TITLE
Helm install fails: Error calling semverCompare: Invalid Semantic Version

### ISSUE THREAD

**Issue by nodesocket** [DataDog/helm-charts#712]
## Describe what happened:

> Error: INSTALLATION FAILED: template: datadog/templates/daemonset.yaml:114:14: executing "datadog/templates/daemonset.yaml" at <include "container-process-agent" .>: error calling include: template: datadog/templates/_helpers.tpl:689:32: executing "process-agent-config-file-flag" at <semverCompare "^6.36.0 || ^7.36.0" $version>: error calling semverCompare: Invalid Semantic Version

**This is blocking us from installing the DataDog agent in Kubernetes clusters. This previously worked, thus I believe is a regression.**

## Describe what you expected:

Helm install should complete.

## Steps to reproduce the issue:

```shell
helm install datadog -f values/datadog.yaml --set datadog.apiKey=<DATADOG_API_KEY_HERE> --set datadog.clusterName=<ENV_NAME_HERE> datadog/datadog
```

Contents of `values/datadog.yaml` is:

```
datadog:
  confd:
    traefik.yaml: |-
      ad_identifiers:
        - traefik
      init_config:
      instances:
        - host: traefik-dashboard
          port: 80
  env:
    - name: "DD_KUBELET_TLS_VERIFY"
      value: "false"
    - name: "RABBITMQ_PASSWORD"
      value: "<RABBITMQ_PASSWORD_HERE>"
  systemProbe:
    enableOOMKill: true
```

## Additional environment details (Operating System, Cloud provider, etc):

Helm version: `version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}`
