### ISSUE TITLE
Missing imagePullPolicy for seccomp-setup

### ISSUE THREAD

**Issue by nu12** [DataDog/helm-charts#719]
**Describe what happened:** Hello, I'm trying to set **all** image pull policies to Always, as part of the best practices adopted by the team. I noticed that seccomp-setup container is the only one missing this property.

**Describe what you expected:** I expected to have a way to specify image pull policy for seccomp-setup container.

**Steps to reproduce the issue:**

Create the following values.yaml file:
```
targetSystem: "linux"

datadog:
  securityAgent:
    runtime:
      enabled: true

agents:
  image:
    pullPolicy: Always
```

Get the seccomp spec, run:

```bash
helm template datadog-agent datadog/datadog --values values.yaml -n datadog | yq '. | select(.metadata.name == "datadog-agent" and .kind == "DaemonSet") | .spec.template.spec.initContainers[2]'
```

This is the output:
```
name: seccomp-setup
image: "gcr.io/datadoghq/agent:7.38.1"
command:
  - cp
  - /etc/config/system-probe-seccomp.json
  - /host/var/lib/kubelet/seccomp/system-probe
volumeMounts:
  - name: datadog-agent-security
    mountPath: /etc/config
  - name: seccomp-root
    mountPath: /host/var/lib/kubelet/seccomp
    mountPropagation: None
resources: {}
```

As we can see, there is no pull policy in the snippet above.

For comparison, get the spec of init-volume, run:

```bash
helm template datadog-agent datadog/datadog --values values.yaml -n datadog | yq '. | select(.metadata.name == "datadog-agent" and .kind == "DaemonSet") | .spec.template.spec.initContainers[0]'
```

As we can see below, other initContainers have imagePullPolicy.

```
name: init-volume
image: "gcr.io/datadoghq/agent:7.38.1"
imagePullPolicy: Always
command: ["bash", "-c"]
args:
  - cp -r /etc/datadog-agent /opt
volumeMounts:
  - name: config
    mountPath: /opt/datadog-agent
resources: {}
```

**Additional environment details (Operating System, Cloud provider, etc):**

N/A

----------------

As we can see [here](https://github.com/DataDog/helm-charts/blob/e535f1d9f92c6bf5d406fbabef3aa353bafe812c/charts/datadog/templates/_containers-init-linux.yaml#L4) and [here](https://github.com/DataDog/helm-charts/blob/e535f1d9f92c6bf5d406fbabef3aa353bafe812c/charts/datadog/templates/_containers-init-linux.yaml#L15), other initContainers have their image pull policy inherited from the agent config. I was wondering if we can add the same in [this file](https://github.com/DataDog/helm-charts/blob/ff98e40b24bb0e8d2eb3bb31d10615dfbaeb1ab9/charts/datadog/templates/_system-probe-init.yaml), either having an specific option in the values file or inheriting the value form the agents as the other ones.

Let me know if this is something I should give a go.

Thank you
