### ISSUE TITLE
security-agent permission ERROR: cannot list resource "endpoints"

### ISSUE THREAD

**Issue by damienleger** [DataDog/helm-charts#720]
**Describe what happened:**

I've got plenty of those errors

![image](https://user-images.githubusercontent.com/16499022/185078534-b83f76d7-6703-43df-a1e2-fecb89b32c33.png)

```
datadog-rs9m5 security-agent 2022-08-17 08:53:28 UTC | SECURITY | ERROR | (pkg/util/kubernetes/apiserver/apiserver_kubelet.go:28 in NodeMetadataMapping) | Could not collect endpoints from the API Server: "endpoints is forbidden: User \"system:serviceaccount:datadog:datadog\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope
```

**Describe what you expected:**

To not have this error.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

My setup is as follow: `helm upgrade -n datadog datadog -f values.yaml -f values.common.yaml -f values.production.secrets.yaml datadog/datadog --version=2.37.4`

with values.yaml being this one untouched https://github.com/DataDog/helm-charts/blob/datadog-2.37.4/charts/datadog/values.yaml

and the other two below

values.common.yaml
```
datadog:
  env:
    # https://github.com/DataDog/helm-charts/issues/600
    - name: DD_LOGS_CONFIG_OPEN_FILES_LIMIT
      value: 200
  loglevel: WARN
  site: 'datadoghq.eu'
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
  nodeLabelsAsTags:
    kubernetes.io/hostname: nodename
  podLabelsAsTags:
    env: env
    service: service
    app.kubernetes.io/version: version
  dogstatsd:
    useSocketVolume: false
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    socketEnabled: false
  processAgent:
    processCollection: true
  networkMonitoring:
    enabled: true
  # syntax here: https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagent
  containerExcludeLogs: "kube_namespace:(amazon-cloudwatch|cypress|datadog) name:(cluster-autoscaler|kube-proxy|amazon-k8s-cni-init|amazon-k8s-cni)"
clusterAgent:
  replicas: 2
  createPodDisruptionBudget: true
clusterChecksRunner:
  enabled: true
agents:
  containers:
    agent:
      logLevel: WARN
    processAgent:
      logLevel: WARN
    traceAgent:
      logLevel: WARN
    systemProbe:
      logLevel: WARN
    securityAgent:
      logLevel: WARN
```

values.production.secrets.yaml
```
datadog:
  apiKey: xxxxxxxxxxxxxx
  securityAgent:
    runtime:
      enabled: true
clusterAgent:
  confd:
    postgres.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - dbm: true # true to activate
          host: "xxxxxxxxxxxxxx"
          port: 5432
          username: "xxxxxxxxxxx"
          password: "xxxxxxxxxxxxxx"
          ssl: require
```

**Comment by jvlasblom** [comment]
I have the same issue on GCP.
my config.yaml:
```
targetSystem: "linux"
datadog:
  clusterName: xxxxxxxx
  tags: []
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
  apm:
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: false
    collectDNSStats: false
  securityAgent:
    runtime:
      enabled: true
```
