### ISSUE TITLE
CRD's will not deploy correctly with Kustomize

### ISSUE THREAD

**Issue by CmdrSharp** [DataDog/helm-charts#733]
**Describe what happened:**
Datadogs CustomResourceDefinitions will not deploy correctly, as they are right now, with Kubernetes versions >1.21-0, when deployed using Kustomize.
The reason is that Kustomize uses `helm template`, which in turn (unless ran with --validate) does not fetch capabilities.

The root cause can be tracked here:
https://github.com/kubernetes-sigs/kustomize/issues/3816

I will submit a PR that adds the option to override the detected Kubernetes version (since the CRD's make use of capabilities) to deal with this. It also breaks the use of deployment via Anthos Config Management.

**Describe what you expected:**
Datadog should deploy with the correct apiVersions.

**Steps to reproduce the issue:**
1. Set up a cluster with Kubernetes version >1.21-0
2. Using Kustomize, attempt to render the Datadog Operator helm chart. It will fail as the chart will render the `v1beta1` components.

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: datadog-operator
    repo: https://helm.datadoghq.com
    version: 0.8.6
    releaseName: datadog-operator
    namespace: datadog
    includeCRDs: true
    valuesInline:
      replicaCount: 2
      apiKeyExistingSecret: datadog-secret
      appKeyExistingSecret: datadog-secret
      site: datadoghq.eu
      resources:
        limits:
          cpu: 300m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
```

**Additional environment details (Operating System, Cloud provider, etc):**
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5-gke.1504", GitCommit:"817c52cbf6d481f56d82f20f68d9bfd74f8387ef", GitTreeState:"clean", BuildDate:"2022-06-14T18:16:54Z", GoVersion:"go1.17.8b7", Compiler:"gc", Platform:"linux/amd64"}
```
