### ISSUE TITLE
Make vendoring the chart easy

### ISSUE THREAD

**Issue by irl-segfault** [DataDog/helm-charts#741]
Currently, vendoring this helm chart is a bit difficult.  I think most teams eventually will want to vendor this chart to control upgrades as opposed to simply running `helm repo update` on their developer laptops and installing from there.  Vendoring is important for deploying this chart via CI/CD.

Currently, installing this helm chart via a locally checked out repo causes the following error:

```
git clone git clone https://github.com/DataDog/helm-charts.git
cd helm-charts/charts/datadog
helm install datadog .
Error: found in Chart.yaml, but missing in charts/ directory: datadog-crds, kube-state-metrics
```

Updating requirements.yaml to point to a the local filesystem doesn't work, ex.
```
dependencies:
  - name: datadog-crds
    version: 0.4.7
    repository: file://../datadog-crds
    condition: clusterAgent.metricsProvider.useDatadogMetrics
    tags:
    - install-crds
  ```

Do you have any guidance for how to vendor this chart?
