### ISSUE TITLE
DD_HOSTNAME_FILE breaks APM annotating kubernetes tags

### ISSUE THREAD

**Issue by cep21** [DataDog/helm-charts#757]
**Describe what happened:**

I have two helm releases with the only flag difference `useHostnameFromFile: true`

```
helm get all datadog-datadog --revision 17 > /tmp/a
helm get all datadog-datadog --revision 18 > /tmp/b
```

Here is the diff
```
< diff /tmp/a /tmp/b
2c2
< LAST DEPLOYED: Fri Sep 16 21:05:51 2022
---
> LAST DEPLOYED: Fri Sep 16 21:27:01 2022
4,5c4,5
< STATUS: superseded
< REVISION: 17
---
> STATUS: deployed
> REVISION: 18
36a37,40
>   providers:
>     eks:
>       ec2:
>         useHostnameFromFile: false
619c623
<         useHostnameFromFile: true
---
>         useHostnameFromFile: false
1595,1596d1598
<         - name: DD_HOSTNAME_FILE
<           value: /var/lib/cloud/data/instance-id
1697,1699d1698
<         - mountPath: /var/lib/cloud/data/instance-id
<           name: cloudinit-instance-id-file
<           readOnly: true
1747,1748d1745
<         - name: DD_HOSTNAME_FILE
<           value: /var/lib/cloud/data/instance-id
1805,1807d1801
<         - mountPath: /var/lib/cloud/data/instance-id
<           name: cloudinit-instance-id-file
<           readOnly: true
1830,1831d1823
<         - name: DD_HOSTNAME_FILE
<           value: /var/lib/cloud/data/instance-id
1877,1879d1868
<         - mountPath: /var/lib/cloud/data/instance-id
<           name: cloudinit-instance-id-file
<           readOnly: true
1933,1934d1921
<         - name: DD_HOSTNAME_FILE
<           value: /var/lib/cloud/data/instance-id
1991,1994d1977
<       - hostPath:
<           path: /var/lib/cloud/data/instance-id
<           type: File
<         name: cloudinit-instance-id-file
```

Without DD_HOSTNAME_FILE, my APM traces are annotated with the container_id that generates them.  With that flag, my APM traces no longer have kubernetes tags (kube_namespace, etc).

**Describe what you expected:**

I expect to keep kube_namespace, kube_deployment, etc tags

**Steps to reproduce the issue:**

Use `useHostnameFromFile: true` and notice missing kub APM tags

**Additional environment details (Operating System, Cloud provider, etc):**

EKS, kub 1.22, agent 7.38.0

**Comment by cep21** [comment]
```
datadog:
  agents:
    containers:
      agent:
        env:
          - name: DD_LOGS_CONFIG_OPEN_FILES_LIMIT
            value: "500"
    volumeMounts:
      - name: pod-resources
        mountPath: /var/lib/kubelet/pod-resources
        readOnly: true
    volumes:
      - hostPath:
          path: /var/lib/kubelet/pod-resources
        name: pod-resources
    image:
      tag: 7.38.0
    tolerations:
      - operator: Exists
  datadog:
    kubelet:
      tlsVerify: false  # https://github.com/DataDog/integrations-core/issues/2582
    clusterChecks:
      enabled: true
    dogstatsd:
      useHostPID: true
      useHostPort: true
      nonLocalTraffic: true
      useSocketVolume: true
      originDetection: true

    collectEvents: true
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret
    apm:
      socketEnabled: true
      portEnabled: true
    logs:
      enabled: true
      containerCollectAll: true
    # This may be expensive.  We'll see and readjust.
    processAgent:
      enabled: true
  clusterAgent:
    image:
      tag: 3.38.0
    enabled: true
    metricsProvider:
      enabled: true
  clusterChecksRunner:
    enabled: true
    rbac:
      dedicated: true
    image:
      tag: 7.38.0
  providers:
    eks:
      ec2:
        useHostnameFromFile: true
```
