### ISSUE TITLE
Support additional Datadog logs configurations

### ISSUE THREAD

**Issue by jdheyburn** [DataDog/helm-charts#767]
- We use the Datadog helm chart to deploy to our K8s cluster
- We've onboarded Datadog logs and are having to set the configuration for it via environment variables at `agents.containers.agent.env`
- Since this is defined as an array and not a map, we are having to duplicate env vars across a multitude of helm values since they do not merge
- I'd like to propose adding these env vars as config values.yaml so that we have a much tidier experience

Currently I see supported the following log env vars set, along with how we can set them:
- `DD_LOGS_ENABLED` - `datadog.logs.enabled`
- `DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL` - `datadog.logs.containerCollectAll`
- `DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE` - `datadog.logs.containerCollectUsingFiles`
- `DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION` - `datadog.logs.autoMultiLineDetection`

I would like the following env vars added:

### `DD_LOGS_CONFIG_AUDITOR_TTL`

- type: number
- config: `datadog.logs.auditorTTL`

### `DD_LOGS_CONFIG_AUTO_MULTI_LINE_DEFAULT_MATCH_THRESHOLD`

- type: number
- config: `datadog.logs.autoMultiLineDefaultMatchThreshold`

### `DD_LOGS_CONFIG_AUTO_MULTI_LINE_DEFAULT_MATCH_TIMEOUT`

- type: number
- config: `datadog.logs.autoMultiLineDefaultMatchTimeout`

### `DD_LOGS_CONFIG_AUTO_MULTI_LINE_DEFAULT_SAMPLE_SIZE`

- type: number
- config: `datadog.logs.autoMultiLineDefaultSampleSize`

### `DD_LOGS_CONFIG_EXPECTED_TAGS_DURATION`

- type: string
- config: `datadog.logs.expectedTagsDuration`

### `DD_LOGS_CONFIG_PROCESSING_RULES`

- type: TBC
- config: `datadog.logs.processingRules`

Given that this [env var is a JSON string](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=helm#global-processing-rules), would it be in best interest to have this generated by helm so that we do not have a string of JSON everywhere?

---

If there are no objections I can get a PR together of a first draft.

**Comment by clamoriniere** [comment]
Hi @jdheyburn,

thanks for sharing your feedback and propose a chart enhancement that can benefit to everyone. 


To give a bit more context about the current implementation. We have only implemented `datadog.logs.*` options for the common options in kubernetes. but we are open to add more options. However it would be ideal to find a generic solution that allows to add any new parameter without changing the chart again.

Could you explain a bit more the issue of the `list` vs `map`. Could you share an example of the `values.yaml` file were you need to duplicate envvars.

Another approach that I'm thinking of is: define a dedicated list/map of envvars for the configuration of the log-agent. 

A quick feedback on the solution that you propose: maybe some option can be group like
```
datadog:
  log:
    autoMultiLineDefault:
      matchThreshold: ''
      matchTimeout: ''
      sampleSize: ''

```

**Comment by jdheyburn** [comment]
So for env vars, I think it's better to have them defined as a map since when we use helm values files in a hierarchical manner such as below:

```
values/values.yaml
values/production/values.yaml
values/production/cluster-specific/values.yaml
```

Then we can use maps to set some sensible defaults:

```yaml
# values/values.yaml
datadog:
  log:
    enabled: false
```

We can then override them by setting them at a specific level, when we call `helm upgrade -f values/values.yaml -f values/production/values.yaml`:

```yaml
# values/production/values.yaml
datadog:
  log:
    enabled: true
```

The resulting value of `datadog.log.enabled` here is `true`.

---

For lists, the last declaration wins, so given this file:

```yaml
# values/values.yaml
agents:
  containers:
    agent:
      env:
        - name: SOME_ENV_VAR
           value: 0
        - name: ANOTHER_ENV_VAR
           value: 1
```

And this one for production:

```yaml
# values/production/values.yaml
agents:
  containers:
    agent:
      env:
        - name: SOME_ENV_VAR
           value: 1
```

The resulting value of `agents.containers.agent.env` is just the below, ANOTHER_ENV_VAR does not exist. 

```yaml
  - name: SOME_ENV_VAR
    value: 1
```

So to my first comment, we would have to re-declare ANOTHER_ENV_VAR to the desired value. Doing this across multiple hierarchical values files gets messy.

---

Whereas if env var was defined as a map:

```yaml
# values/values.yaml
agents:
  containers:
    agent:
      envMap:
        SOME_ENV_VAR: 0
        ANOTHER_ENV_VAR: 1
```

```yaml
# values/production/values.yaml
agents:
  containers:
    agent:
      envMap:
        SOME_ENV_VAR: 1
```

And then having this templating in the pod template:

```
        env:
        {{- range $k, $v := .Values.agents.containers.agent.envMap }}
        - name: $k
           value: $v
        {{- end }}
```

Then the resulting envMap is SOME_ENV_VAR = 1 and ANOTHER_ENV_VAR  = 1.

I believe having an envMap would solve your comment: 

> However it would be ideal to find a generic solution that allows to add any new parameter without changing the chart again.

---

If we were to implement `envMap` then we do not need the support for the additional values in my original message, because they can just be set there. I don't advocate for changing the behaviour of `env` since it would be a breaking change for the user.

Thanks for your patience, looking forward to your reply 👍🏻

**Comment by jdheyburn** [comment]
@clamoriniere I am happy to start working on the implementation for logs:

```yaml
datadog:
  logs:
    autoMultiLineDefault:
      matchThreshold: ''
      matchTimeout: ''
      sampleSize: ''
    auditorTTL: ''
    expectedTagsDuration: ''
    processingRules: ''
```

WRT the generic solution, I have raised #850 to discuss it there. I'll prioritise this ticket as I believe its ready to go, whereas the other may need further triaging.
