### ISSUE TITLE
enableDefaultOsReleasePaths mountet incorrectly

### ISSUE THREAD

**Issue by vitality411** [DataDog/helm-charts#791]
**Describe what happened:**

If osReleasePath is not equal to /etc/redhat-release, /etc/fedora-release or /etc/lsb-release than the os-release file are mountet even though they do not exist:

https://github.com/DataDog/helm-charts/blob/a2f434b7eb08d2c22ce4efce89543cf7a2d2d6ad/charts/datadog/templates/_container-system-probe.yaml#L58-L77

In addition if I set osReleasePath to /etc/redhat-release for example than /etc/redhat-release will not be mounted due to this.

**Describe what you expected:**

In my opinion the comparision should be set to equal, e.g. only mount /etc/redhat-release when osReleasePath is set to /etc/redhat-release.

**Steps to reproduce the issue:**

Deploy Helm chart
List volumeMounts from system-probe container
```
     volumeMounts:
    - mountPath: /var/log/datadog
      name: logdatadog
    - mountPath: /tmp
      name: tmpdir
    - mountPath: /sys/kernel/debug
      mountPropagation: None
      name: debugfs
    - mountPath: /etc/datadog-agent
      name: config
    - mountPath: /etc/datadog-agent/datadog.yaml
      name: datadog-yaml
      subPath: datadog.yaml
    - mountPath: /etc/datadog-agent/system-probe.yaml
      name: sysprobe-config
      subPath: system-probe.yaml
    - mountPath: /var/run/sysprobe
      name: sysprobe-socket-dir
    - mountPath: /host/proc
      mountPropagation: None
      name: procdir
      readOnly: true
    - mountPath: /host/etc/os-release
      mountPropagation: None
      name: os-release-file
      readOnly: true
    - mountPath: /host/etc/redhat-release
      mountPropagation: None
      name: etc-redhat-release
      readOnly: true
    - mountPath: /host/etc/fedora-release
      mountPropagation: None
      name: etc-fedora-release
      readOnly: true
    - mountPath: /host/etc/lsb-release
      mountPropagation: None
      name: etc-lsb-release
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rpndb
      readOnly: true
```
List volumes in Pod
```  volumes:
...
  - hostPath:
      path: /etc/os-release
      type: ""
    name: os-release-file
  - hostPath:
      path: /etc/redhat-release
      type: ""
    name: etc-redhat-release
  - hostPath:
      path: /etc/fedora-release
      type: ""
    name: etc-fedora-release
  - hostPath:
      path: /etc/lsb-release
      type: ""
    name: etc-lsb-release
...
```

List files on host, please note that /etc/fedora-release and /etc/lsb-release are directories which have been created due to hostPath:
```ls -la /etc/os-release /etc/redhat-release /etc/fedora-release /etc/lsb-release
lrwxrwxrwx. 1 root root 21 Mar 24  2021 /etc/os-release -> ../usr/lib/os-release
lrwxrwxrwx. 1 root root 14 Mar 24  2021 /etc/redhat-release -> centos-release

/etc/fedora-release:
total 12
drwxr-xr-x   2 root root    6 Oct 20 07:49 .
drwxr-xr-x. 85 root root 8192 Oct 20 07:49 ..

/etc/lsb-release:
total 12
drwxr-xr-x   2 root root    6 Oct 20 07:49 .
drwxr-xr-x. 85 root root 8192 Oct 20 07:49 ..
```

**Additional environment details (Operating System, Cloud provider, etc):**
OS: CentOS Linux release 7.9.2009 (Core)
kubeadm cluster

**Comment by clamoriniere** [comment]
Hi @vitality411 

Unfortunately it is not possible during the helm install to know if the paths exist on the host. 
And, to provide a default configuration that works for most of the users, the chart try to mount all the possible path we the agent can fin the OS release information. 

We have added recently the option `datadog.systemProbe.enableDefaultOsReleasePaths` (defaulted to `true`) to avoid trying to mount all the paths.

So you can use in `datadog.osReleasePath` to provide the correct path and `datadog.systemProbe.enableDefaultOsReleasePaths` to disable the others.

```yaml
datadog:
  osReleasePath: "/etc/redhat-release"
  systemProbe:
    enableDefaultOsReleasePaths: false

```

please let us know it is works for you
Thanks
