### ISSUE TITLE
OTLP does not support when PSP enabled

### ISSUE THREAD

**Issue by DingGGu** [DataDog/helm-charts#812]
**Describe what happened:**
```
kubectl describe ds/datadog

Events:
  Type     Reason            Age                   From                  Message
  ----     ------            ----                  ----                  -------
  Warning  FailedCreate      33m (x35 over 24h)    daemonset-controller  Error creating: pods "datadog-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].hostPort: Invalid value: 4317: Host port 4317 is not allowed to be used., ...
```

**Describe what you expected:**
Datadog should deploy when PodSecurityPolicy enabled.

**Steps to reproduce the issue:**
```
datadog:
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true

agents:
  podSecurity:
    apparmor:
      enabled: false
    podSecurityPolicy:
      create: true

    useHostNetwork: true
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by JacksonDavenport** [comment]
Hello @DingGGu 
In this case we would recommend to set the `useHostPort` setting to `false` for this: 

```yaml
datadog:
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
          useHostPort: false
#(...)
```

This will still enable the GRPC receiver on port 4317 for the Agent to receive, however will create this without the Host Port setting. Which should help avoid the `PodSecurityPolicy` from blocking the deployment relative to this Host Port. 

You can see some examples here:
- https://github.com/DataDog/helm-charts/pull/792

Of how you can use the `Service` created by the Helm Chart as an alternative method to send data from the Applications to the Agent without relying the `Host IP:Host Port` method.
