### ISSUE TITLE
Rendered kube-state-metrics deployment uses deprecated flag (--controllers) in v2   

### ISSUE THREAD

**Issue by jorgeAtNesto** [DataDog/helm-charts#825]
**Describe what happened:**

Helm Chart version: `3.1.10`

👋🏼 Hi y'all,
I'm overriding the base `kube-state-metrics.image.tag` default value (which is `v1.9.8`) to prevent kube-state-metrics from using a couple of removed apis in Kubernetes v1.22 (`certificates.k8s.io/v1beta1/certificatesigningrequests` and `extensions/v1beta1/ingresses`). So after looking into the [kube-state-metrics docs](https://github.com/kubernetes/kube-state-metrics#compatibility-matrix), I found out that I need to use v2.5.0+ (I'm currently using kubernetes `v1.24` on GKE) which I diligently specified in my `values.yaml` file as follows:

**Config**
```YAML
# # kube-state-metrics.image -- Override default image information for the kube-state-metrics container.
  image:
  #  # kube-state-metrics.repository -- Override default image registry for the kube-state-metrics container.
  #  repository: k8s.gcr.io/kube-state-metrics/kube-state-metrics
  #  # kube-state-metrics.tag -- Override default image tag for the kube-state-metrics container.
    tag: v2.5.0
  #  # kube-state-metrics.pullPolicy -- Override default image pullPolicy for the kube-state-metrics container.
  #  pullPolicy: IfNotPresent
```

Then, on deployment time, kube-state-metrics container started crashlooping because it uses a [deprecated flag in version 2](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cli-arguments.md) (`--collectors`). The rendered kube-state-metrics deployment manifest passes the following args: 
```YAML
args:
  - '--collectors=certificatesigningrequests'
  - '--collectors=configmaps'
  - '--collectors=cronjobs'
  - '--collectors=daemonsets'
  - '--collectors=deployments'
  - '--collectors=endpoints'
  - '--collectors=horizontalpodautoscalers'
  - '--collectors=ingresses'
  - '--collectors=jobs'
  - '--collectors=limitranges'
  - '--collectors=mutatingwebhookconfigurations'
  - '--collectors=namespaces'
  - '--collectors=networkpolicies'
  - '--collectors=nodes'
  - '--collectors=persistentvolumeclaims'
  - '--collectors=persistentvolumes'
  - '--collectors=poddisruptionbudgets'
  - '--collectors=pods'
  - '--collectors=replicasets'
  - '--collectors=replicationcontrollers'
  - '--collectors=resourcequotas'
  - '--collectors=secrets'
  - '--collectors=services'
  - '--collectors=statefulsets'
  - '--collectors=storageclasses'
  - '--collectors=validatingwebhookconfigurations'
  - '--collectors=volumeattachments'
  - '--telemetry-port=8081'  
```

And here's the failing container logs:
```
unknown flag: --collectors
Usage of /kube-state-metrics:
unknown flag: --collectors
# followed by a printed help cmd 
```

**Describe what you expected:**

In order to prevent the deployment from failing, I need a new flag to override based container args (which use deprecated flags). 

**Steps to reproduce the issue:**
1. Install helm chart v3.1.10 using your preferred method (ours is wrapping helm with pulumi).
2. Configure your values as displayed above (see Config).

**Additional environment details (Operating System, Cloud provider, etc):**

GKE: v1.24
local: MacOS Monterey v12.6 M1
Helm: version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
