### ISSUE TITLE
Datadog Helm Chart - ContainerCreateError from 3.5.0 (/usr/src: read-only file system)

### ISSUE THREAD

**Issue by CmdrSharp** [DataDog/helm-charts#829]
**Describe what happened:**
Starting from version 3.5.0, we can no longer deploy the `datadog` helm chart into our Anthos Kubernetes cluster. It creates the datadog-cluster-agent fine, but the individual datadog pods fail to spin up. More specifically, the `system-probe` container fails with `CreateContainerError`.

```
  Warning  Failed     42s                kubelet            Error: failed to generate container "fdc39d9b57c2d54333925914e847682c6a6956b763158ed8628f6a770c571397" spec: failed to generate spec: failed to mkdir "/usr/src": mkdir /usr/src: read-only file system
```

Installing 3.4.0 works fine, so this is a new regression.

**Describe what you expected:**
Pod should spin up normally.

**Steps to reproduce the issue:**

`helm install datadog -f datadog.yaml datadog/datadog --namespace datadog --version 3.5.0`

```yaml
---
targetSystem: "linux"
datadog:
  clusterName: <CLUSTER-NAME-REDACTED>
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: datadoghq.eu
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
    collectVpaMetrics: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    portEnabled: true
  helmCheck:
    enabled: true
    collectEvents: true
  networkMonitoring:
    enabled: true
  serviceMonitoring:
    enabled: true
  prometheusScrape:
    enabled: false
  processAgent:
    enabled: true
    processCollection: true
  containerExclude: "image:gcr.io/gke-on-prem-release/fluent-bit"
clusterAgent:
  replicas: 2
  createPodDisruptionBudget: true
  admissionController:
    mutateUnlabelled: true
agents:
  useConfigMap: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  customAgentConfig:
    kubelet_tls_verify: false
    vector:
      logs:
        enabled: true
        url: "http://vector-haproxy.datadog:8282/"
      metrics:
        enabled: true
        url: "http://vector-haproxy.datadog:8282/"
```

**Additional environment details (Operating System, Cloud provider, etc):**
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7-gke.1400", GitCommit:"cec695fcf394f7b5cc56b7bc70b5ecf99d043455", GitTreeState:"clean", BuildDate:"2022-11-02T09:29:16Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
```
