### ISSUE TITLE
[synthetics-private-location] `commonLabels` duplicated in Deployment

### ISSUE THREAD

**Issue by martinpiegay** [DataDog/helm-charts#840]
**Describe what happened:**
When setting some `commonLabels` in Values, the deployment of the chart fails.

Example in the _values.yaml_:
```yaml
commonLabels:
  team_name: dev
```

That produce: 
```yaml
# Source: synthetics-private-location/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetics-private-location
  labels:
    helm.sh/chart: synthetics-private-location-0.15.5
    app.kubernetes.io/name: synthetics-private-location
    app.kubernetes.io/instance: synthetics-private-location
    **team_name: dev**
    app.kubernetes.io/version: "1.29.0"
    app.kubernetes.io/managed-by: Helm
    **team_name: dev**
```

**Describe what you expected:** 

I expected that `commonLabels` were not duplicated because it makes my Flux HelmRelease fail.

**Steps to reproduce the issue:**

Create a `./values_test.yaml` file and copy the example provided in `Describe what happened` section . Then, run `helm template synthetics-private-location ./synthetics-private-location -f ./values_test.yaml`
