### ISSUE TITLE
How to add annotations to datadog-kube-state-metrics deployment?

### ISSUE THREAD

**Issue by gajus** [DataDog/helm-charts#845]
Need a configuration to add annotations to `datadog-kube-state-metrics` so that we could [apply log filtering rules](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes) using fluent-bit.

I tried

```yaml
kubeStateMetricsCore:
  enabled: true
  podAnnotations:
    fluentbit.io/exclude: 'true'
```

but it looks like that does not propagate

**Comment by clamoriniere** [comment]
Hi @gajus 

with `kubeStateMetricsCore` the deployment of `kube-state-metrics` is not required. the check is executed by default in the cluster-agent deployment

```yaml
datadog:
  # (...)
  kubeStateMetricsCore:
    enabled: true
```

Since the datadog chart version `v3.0.0`,  `kube-state-metrics` chart dependency should be disable by default,  because `datadog.kubeStateMetricsEnabled` is set to false by default. (please check that is is the case in your configuration)

at the end you should have 

```yaml
datadog:
  # (...)
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
```

please let us know if it solve your issue.
