### ISSUE TITLE
[helm-charts/charts/datadog] Cluster Agent exposes port 8000 for Admission Controller but does not document it on containerPorts

### ISSUE THREAD

**Issue by michelzanini** [DataDog/helm-charts#848]
**Describe what happened:**

Our security team is doing a penetration test in order to discover open ports and they found `8000` port to be open on Cluster Agent, but we previously didn't know it was used because the Deployment of cluster agent only show these below as being used ports:

```
      ports:
        - containerPort: 5005
          name: agentport
          protocol: TCP
        - containerPort: 5000
          name: agentmetrics
          protocol: TCP
```

**Describe what you expected:**

I would expect the port 8000 to be seen on container port list if its used.
I know I can disable Admission Controller for the port to no longer being used, but I guess it would be good to add the containerPort to the YAML if its enabled to better "document" the port's usage.

Not sure this will have any other impact as the docs says this about container ports:

From the [docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#pod-v1-core)

> ContainerPort

> List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network. Cannot be updated.
