### ISSUE TITLE
[helm-charts/charts/datadog] Support for generic environment variables defined as a map

### ISSUE THREAD

**Issue by jdheyburn** [DataDog/helm-charts#850]
- When using Helm values files in a hierarchical manner, any instances of lists are overwritten by values files further down the hierarchy
- This means that we have to duplicate environment variables in multiple places when we want to add a new one
- This behaviour is discussed [here](https://github.com/elastic/helm-charts/issues/53) for another non-Datadog helm chart

Since `.env` and `.envFrom` are already defined, I suggest creating an `.envMap` value which will allow the following:

```yaml
datadog:
  envMap:
    DD_ENVIRONMENT_VARIABLE: "VALUE"
```

Then this would be templated as below:

```
  env:
    {{- range $key, $value := .Values.datadog.envMap }}
    - name: {{ $key }}
      value: {{ $value | quote }}
    {{- end }}
```

Since this is an extension to env vars, after some analysis I found that the following would need to be created in total

```
datadog.envMap
agents.containers.agent.envMap
agents.containers.processAgent.envMap
agents.containers.securityAgent.envMap
agents.containers.systemProbe.envMap
agents.containers.traceAgent.envMap
clusterAgent.envMap
clusterChecksRunner.envMap
```

Additionally, this will allow us to prevent having to constantly add new values to the helm chart when future functionality is released, users can add the config via the helm values:

```yaml
agents:
  containers:
    agent:
      envMap:
        DD_SOME_FUTURE_ENV_VAR: VALUE
```

Note: this enhancement was originally discussed in:
- #767
