### ISSUE TITLE
Autopilot gke of datadog/datadog failed to create resource due to request denied

### ISSUE THREAD

**Issue by dtabata** [DataDog/helm-charts#853]
**Describe what happened:**
After upgrading the GKE Autopilot Cluster version, an error occurs in `app sync` of datadog by ArgoCD.

We are running `REGULAR` and `STABLE` clusters and have versioned each, but both have the same error.
``` shell
GKE Autopilot REGULAR: `1.22.12-gke.2300` --> `1.24.5-gke.600`
GKE Autopilot STABLE : `1.22.12-gke.2300` --> `1.23.11-gke.300`

The `1.22.12-gke.2300` is no longer supported and cannot be used😢
```

<br />

helm version 3.2.0
Based on [these issues](https://github.com/DataDog/helm-charts/issues/549#issuecomment-1324395393), I tried using 3.3.2, but the results did not change.

<br />

**Received this error:**
one or more objects failed to apply, reason: admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints. Violations details: {"[denied by autogke-no-write-mode-hostpath]":["hostPath volume dsdsocket in container agent is accessed in write mode; disallowed in Autopilot.","hostPath volume os-release-file used in container agent uses path /etc/os-release which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume runtimesocketdir used in container agent uses path /var/run which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume procdir used in container agent uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume cgroups used in container agent uses path /sys/fs/cgroup which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume dsdsocket in container trace-agent is accessed in write mode; disallowed in Autopilot.","hostPath volume runtimesocketdir used in container trace-agent uses path /var/run which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume os-release-file used in container process-agent uses path /etc/os-release which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume runtimesocketdir used in container process-agent uses path /var/run which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume cgroups used in container process-agent uses path /sys/fs/cgroup which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume passwd used in container process-agent uses path /etc/passwd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume procdir used in container process-agent uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume dsdsocket used in container process-agent uses path /var/run/datadog which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume procdir used in container init-config uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume runtimesocketdir used in container init-config uses path /var/run which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/]."]} Requested by user: 'system:serviceaccount:argocd:argocd-manager', groups: 'system:serviceaccounts,system:serviceaccounts:argocd,system:authenticated'.

**Describe what you expected:**
Chart to provision in Autopilot without any errors.

**Steps to reproduce the issue:**
Here is the values we are using with the chart.
Chart.yaml
``` yaml
apiVersion: v2
name: datadog
type: application
version: 0.0.1
dependencies:
  - name: datadog
    version: "3.2.0"
    repository: "https://helm.datadoghq.com"
```

values.yaml
``` yaml
externalSecret:
  name: example
  gcpServiceAccount: example@example.iam.gserviceaccount.com
  gcpsm:
    projectID: example
    auth:
      workloadIdentity:
        clusterLocation: asia-northeast1
        clusterName: example-dev
  secret:
    apiKey:
      remoteRef:
        key: dd-api-key
    appKey:
      remoteRef:
        key: dd-app-key

providers:
  gke:
    autopilot: true

datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret

  kubeStateMetricsCore:
    enabled: true

  kubeStateMetricsEnabled: false

  logs:
    enabled: true
    containerCollectAll: false
    containerCollectUsingFiles: false

  processAgent:
    enabled: true
    processCollection: true

  networkMonitoring:
    enabled: false

  securityAgent:
    runtime:
      enabled: false

    compliance:
      enabled: false

  ignoreAutoConfig:
  - cilium

  useHostPID: false

agents:
  enabled: true

  image:
    tag: 7.40.1

  priorityClassCreate: true
  priorityClassName: datadog-agent
  priorityClassValue: 1000000000

  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

    processAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

  nodeSelector:
    cloud.google.com/gke-spot: "true"

  tolerations:
    - key: cloud.google.com/gke-spot
      operator: Equal
      value: "true"
      effect: NoSchedule

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "50%"
      
clusterAgent:
  enabled: true

  image:
    tag: 7.40.1

  priorityClassName: datadog-agent

  metricsProvider:
    enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: false

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 512Mi

  nodeSelector:
    cloud.google.com/gke-spot: "true"

  tolerations:
    - key: cloud.google.com/gke-spot
      operator: Equal
      value: "true"
      effect: NoSchedule
```

**Additional environment details (Operating System, Cloud provider, etc):**
The moment I implemented the GKE version upgrade, I started getting errors in `app sync` with ArgoCD.
Does this mean that datadog is not compatible with the new GKE Autopilot Cluster version?
