### ISSUE TITLE
synthetics-private-location - how to reference secret 

### ISSUE THREAD

**Issue by kderck** [DataDog/helm-charts#860]
Describe what happened:

We use [Flux](https://fluxcd.io) with the [HelmRelease](https://fluxcd.io/flux/guides/helmreleases) to create a HelmChart for Synthetics Private Location. To protect the ConfigFile which has credentials we use a [Secret](https://fluxcd.io/flux/guides/helmreleases/) which allows the HelmRelease to be created and it will fetch the ConfigFile from a Secret. No matter how I create this secret I am getting `unable to merge value from key 'DATADOG_SYNTHETICS_CONFIG' in Secret 'datadog/datadog-synthetics-config' into target path 'configFile': key " }" has no value`

```yaml
# Release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synthetics-private-location
  namespace: datadog
spec:
  interval: 5m
  chart:
    spec:
      chart: synthetics-private-location 
      sourceRef:
        kind: HelmRepository
        name: datadog
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: datadog-synthetics-config
      valuesKey: DATADOG_SYNTHETICS_CONFIG
      targetPath: configFile
```

```yaml
# Secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: datadog-synthetics-config
  namespace: datadog
stringData:
  DATADOG_SYNTHETICS_CONFIG: "{
      \"datadogApiKey\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",
      \"id\": \"pl:xxxxxxxxxxxxxxxxxxx\",
      \"site\": \"xxxxxxxxxxxx\",
      \"accessKey\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",
      \"secretAccessKey\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",
      \"privateKey\": \"-----BEGIN RSA PRIVATE KEY-----\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n-----END RSA PRIVATE KEY-----\",
      \"publicKey\": {
        \"pem\": \"-----BEGIN PUBLIC KEY-----\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n-----END PUBLIC KEY-----\n\",
        \"fingerprint\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"
      }
    }"
```

I have tried to `escape` the json. I have tried `|-`. Base64 encoding with `data` I have also tried targeting  `configSecret` and the problem persists.
