### ISSUE TITLE
DD_CONTAINER_INCLUDE not working

### ISSUE THREAD

**Issue by bappr** [DataDog/helm-charts#9]
Hey guys,

I deployed the datadog helm chart, version `2.4.2`.
And I just override the values file with those values:

```
datadog:
    apiKeyExistingSecret: datadog

    clusterName: kinto-dev

    logLevel: INFO

    kubeStateMetricsEnabled: false

    logs:
      enabled: true
      containerCollectAll: true

    containerInclude: "kube_namespace:kinto-*."

    processAgent:
      enabled: false

agents:
    enabled: true

    containers:
      agent:
        logLevel: INFO
```

However, it still push logs from all the namespaces to datadog.

Am I doing something wrong?

**Comment by a7i** [comment]
Hi @bappr shouldn't that be `"kube_namespace:kinto-.*"`?

**Comment by bappr** [comment]
Hey @a7i 
Yeah I did not catch it when I posted here hehe but I saw it after.
So even with the correct wildcard, it's not working it's just sending all the logs. I am considering using something else than datadog cuz the logs are a huge mess right now.

**Comment by mars64** [comment]
@bappr I _think_ Datadog takes the position of "default greedy allow" -- which is to say, I think you need to set up the exclude rule AND include rule. See https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagent#exclude-containers for more info. 

e.g.

```
datadog:
  containerInclude: "kube_namespace:kinto-.*"
  containerExclude: "kube_namespace:.*"
```

**Comment by bappr** [comment]
@mars64 u are right! thanks a lot!!!

**Comment by R1Daneel** [comment]
Is this a wanted behavior? I did not see anything in the documentation that would make me think to it

**Comment by V1ct0rHM** [comment]
@mars64 I'm having this issue with the `containerIncludeLogs` even trying what you said, stills not working.
I put in my values:
            containerExcludeLogs: "kube_namespace:.*"
            containerIncludeLogs: "kube_namespace:xx-prod.*"

**Comment by R1Daneel** [comment]
@V1ct0rHM there is an error in the regex fro the `containerExcludeLogs` key. The regex should be `.*` instead of only `.`.

**Comment by kycfeel** [comment]
Hi there.

I'm also having an issue with the logs.

I'm trying to only collect the logs from the container's name starting with "server".

Am I missing here something?

```
# Helm values.yaml

# datadog.containerExcludeLogs -- Exclude logs from the Agent Autodiscovery,
# as a space-separated list
containerExcludeLogs: "name:.*"

# datadog.containerIncludeLogs -- Include logs in the Agent Autodiscovery, as
# a space-separated list
containerIncludeLogs: "name:server.*"
 ```
 
 Thanks!

**Comment by kycfeel** [comment]
@R1Daneel Hey. Thanks a lot.

Can I ask one more question?

I want to collect logs from containers that include specific keywords.

My containers got random names but have "server", "web", or "nginx" keywords in the middle.

I tried the configuration below but seems like it's only working for the "server" keyword. 

The "web" or "nginx" keywords are getting ignored and the logs are not getting collected.

Can you help me with this too?

Much appreciated.

```

# datadog.containerExcludeLogs -- Exclude logs from the Agent Autodiscovery,
# as a space-separated list
containerExcludeLogs: "name:.*"

# datadog.containerIncludeLogs -- Include logs in the Agent Autodiscovery, as
# a space-separated list
containerIncludeLogs: "name:.*nginx.* name:.*-server-.* name:.*-web-.*"

```

**Comment by R1Daneel** [comment]
The regex seems ok to me. You can use services like this https://regex101.com/ to verify if those regexes cover your use cases

**Comment by V1ct0rHM** [comment]
> @V1ct0rHM there is an error in the regex fro the `containerExcludeLogs` key. The regex should be `.*` instead of only `.`

Thanks @R1Daneel, Yeah, I put that already, sorry when I wrote the comment the github automatically excluded the *

**Comment by guitarboyjr** [comment]
This worked for me with 2 namespaces separated by space char  
```
logs:
    enabled: true
    containerCollectAll: true
  containerIncludeLogs: kube_namespace:istio-.* kube_namespace:dev-.* 
  containerExcludeLogs: kube_namespace:.*
```
