### ISSUE TITLE
Use existing service account with rbac

### ISSUE THREAD

**Issue by nitrocode** [DataDog/helm-charts#904]
**Describe what happened:**

I have the following set in `values.yaml`

```yaml
clusterAgent:
  rbac:
    create: true
    serviceAccountName: zzzzz-datadog-sa

agents:
  rbac:
    create: true
    serviceAccountName: zzzzz-datadog-sa
```

I see that the serviceAccountName is skipped if rbac is true and used only when rbac is false

```shell
$ helm template . --set 'datadog.agents.rbac.create=false' --set 'datadog.clusterAgent.rbac.create=false' | grep zzzzz | wc -l
2
$ helm template . --set 'datadog.agents.rbac.create=true' --set 'datadog.clusterAgent.rbac.create=true' | grep zzzzz | wc -l
0
```

**Describe what you expected:**

I expected rbac to be created and the existing service account to be used.

**Steps to reproduce the issue:**

1. Create namespace, iam role, and service account in terraform
2. Install datadog helm chart with the above values.yaml file
3. Acknowledge that RBAC is created but the serviceAccountName passed in is not used

**Additional environment details (Operating System, Cloud provider, etc):**

- eks
- argocd
- helm

Could be related to this issue

- https://github.com/DataDog/helm-charts/issues/208

## potential workarounds

1. set `fullnameOverride` (feels like a hack) with `rbac.create=true`, but this would try to use the existing service account and create the service account.

    ```yaml
    fullnameOverride: zzzzz-datadog-sa
    ```
    
    https://github.com/DataDog/helm-charts/blob/76658074d3238e0b8ac7e0c790e7e24ee54cf804/charts/datadog/templates/_helpers.tpl#L474-L481
    
    https://github.com/DataDog/helm-charts/blob/76658074d3238e0b8ac7e0c790e7e24ee54cf804/charts/datadog/templates/_helpers.tpl#L92-L103

1. or perhaps use the service account annotation. This would mean we'd have to break from our current practice of creating the service-account in terraform which already has knowledge of the iam role. This method would work but it would not be DRY.

    https://github.com/DataDog/helm-charts/blob/76658074d3238e0b8ac7e0c790e7e24ee54cf804/charts/datadog/templates/rbac.yaml#L130-L140

    ```yaml
    agents:
      rbac:
        serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::<snip>:role/datadog-sa
    ```

The best solution would be to disable the `ServiceAccount` creation via a boolean and reuse an existing `serviceAccountName` passed in under `rbac` (for `clusterAgent` and `agents`). This would create all the rbac resources without the service account.

This could either be a new boolean like `serviceAccountCreate: false` or since the `serviceAccountName` is already ignored if `create: false`, we could just check if `serviceAccountName` has a value, if so, override the existing name.
