### ISSUE TITLE
How to use datadog.advancedConfd.openmetrics.d

### ISSUE THREAD

**Issue by sinkr** [DataDog/helm-charts#906]
**Describe what happened:**
I am attempting to configure a simple Prometheus check, however, my  `openmetrics.d` file never gets written.  If I write it as datadog.confd.openmetrics.yaml, I get a module error and the check doesn't load.

I have tried a ticket with Datadog support, but they seem to know nothing about Helm charts, at least at the initial tier of support.

**Describe what you expected:**
I expect `datadog.advancedConfd.openmetrics.d.conf.yaml `to be put in `/etc/datadog-agent/conf.d/openmetrics.d/conf.yaml`.

**Steps to reproduce the issue:**
1. Take this config block:
```
datadog:
  advancedConfd:
    openmetrics.d:
      conf.yaml: |-
        cluster_check: false
        instances:
          - host: kafka-kafka-0.strimzi.svc.cluster.local
            port: 9404
            name: kafka-0
```

2. Run Helm.
3. Login to an agent
4. Look for `/etc/datadog-agent/conf.d/openmetrics.d/conf.yaml`

I don't doubt I'm doing something wrong here, but I can't figure out what.

**Additional environment details (Operating System, Cloud provider, etc):**
EKS 1.24
Helm 3.11.0
Datadog Helm Chart 3.9.0
