### ISSUE TITLE
Datadog agent doesn't deploy on GKE Autopilot

### ISSUE THREAD

**Issue by huib-coalesce** [DataDog/helm-charts#947]
**Describe what happened:**
Given a GKE cluster in Autopilot mode.
When I deploy the datadog helm chart, the `datadog-agent-cluster-agent` gets deployed, but not the `datadog-agent` DaemonSet.

Then Helm provides the following error:
```
hostPath volume procdir used in container init-config uses path /proc which is not allowed in Autopilot. 
hostPath volume runtimesocketdir used in container init-config uses path /var/run/containerd which is not allowed in Autopilot.
```

**Describe what you expected:**
A `datadog-agent` should be deployed on each node.

**Steps to reproduce the issue:**

Create a kube secret in the default namespace
```
kubectl create secret generic datadog-agent-token --from-literal api-key="<your apy key>"
```

Deploy the helm chart for the agent
```
helm install datadog-agent datadog/datadog -f datadog-agent-values.yaml --version 3.19.1
```

with `datadog-agent-values.yaml`
```
datadog:
  apiKeyExistingSecret: datadog-agent-token

  clusterName: k8s-dev-testing

  kubeStateMetricsCore:
    enabled: true
  kubeStateMetricsEnabled: false

  logs:
    enabled: false
    containerCollectAll: false

  apm:
    enabled: true

  leaderElection: true
  collectEvents: true

  prometheusScrape:
    enabled: false

  processAgent:
    enabled: true
    processCollection: true

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: false
  rbac:
    create: true

agents:
  enabled: true
  priorityClassCreate: true
  containers:
    agent:
      # resources for the Agent container
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      # resources for the Trace Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

    processAgent:
      # resources for the Process Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

providers:
  gke:
    autopilot: true
```

Results in
```
W0315 13:43:42.871865    6661 warnings.go:70] Autopilot set default resource requests on DaemonSet default/datadog-agent for containers init-volume, init-config, as resource requests were not specified, and adjusted resource requests to meet requirements. See http://g.co/gke/autopilot-defaults and http://g.co/gke/autopilot-resources
W0315 13:43:42.871931    6661 warnings.go:70] spec.template.spec.containers[0].env[13].name: duplicate name "DD_PROVIDER_KIND"
W0315 13:43:42.871944    6661 warnings.go:70] spec.template.spec.containers[1].env[10].name: duplicate name "DD_PROVIDER_KIND"
W0315 13:43:42.871952    6661 warnings.go:70] spec.template.spec.containers[2].env[10].name: duplicate name "DD_PROVIDER_KIND"
W0315 13:43:43.372647    6661 warnings.go:70] Autopilot set default resource requests for Deployment default/datadog-agent-cluster-agent, as resource requests were not specified. See http://g.co/gke/autopilot-defaults
Error: INSTALLATION FAILED: admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints.
Violations details: {"[denied by autogke-no-write-mode-hostpath]":["hostPath volume procdir used in container init-config uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume runtimesocketdir used in container init-config uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/]."]}
```

`kubectl describe allowlistedworkload datadog-agents`
results in
```
Name:         datadog-agents
Namespace:    
Labels:       addonmanager.kubernetes.io/mode=Reconcile
Annotations:  components.gke.io/component-name: policyexemptor
              components.gke.io/component-version: 0.0.35
              components.gke.io/layer: addon
API Version:  auto.gke.io/v1
Kind:         AllowlistedWorkload
Metadata:
  Creation Timestamp:  2022-06-15T19:15:33Z
  Generation:          1
  Managed Fields:
    API Version:  auto.gke.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:components.gke.io/component-name:
          f:components.gke.io/component-version:
          f:components.gke.io/layer:
        f:labels:
          f:addonmanager.kubernetes.io/mode:
      f:spec:
        f:containers:
    Manager:         kube-addon-manager
    Operation:       Apply
    Time:            2022-11-13T00:59:58Z
  Resource Version:  124973110
  UID:               8333d7cd-39c0-479e-bea3-d1510f4bd3f2
Spec:
  Containers:
    Command:
      agent
      run
    Exemptions:
      Constraint Name:  autogke-no-write-mode-hostpath
      Constraint Parameters:
        Read Host Paths:
          /var/run/containerd
          /proc
          /sys/fs/cgroup
          /var/lib/docker/containers
        Write Host Paths:
          /var/autopilot/addon/datadog/
      Constraint Name:  autogke-no-host-port
      Constraint Parameters:
        Host Ports:
          8125
    Image:  ^gcr\.io/datadoghq/agent*
    Command:
      process-agent
      -config=/etc/datadog-agent/datadog.yaml
    Exemptions:
      Constraint Name:  autogke-no-write-mode-hostpath
      Constraint Parameters:
        Read Host Paths:
          /proc
          /sys/fs/cgroup
          /var/run/containerd
          /etc/passwd
    Image:  ^gcr\.io/datadoghq/agent*
    Command:
      trace-agent
      -config=/etc/datadog-agent/datadog.yaml
    Exemptions:
      Constraint Name:  autogke-no-write-mode-hostpath
      Constraint Parameters:
        Read Host Paths:
          /var/run/containerd
      Constraint Name:  autogke-no-host-port
      Constraint Parameters:
        Host Ports:
          8126
    Image:  ^gcr\.io/datadoghq/agent*
    Args:
      for script in $(find /etc/cont-init.d/ -type f -name '*.sh' | sort) ; do bash $script ; done
    Command:
      bash
      -c
    Exemptions:
      Constraint Name:  autogke-no-write-mode-hostpath
      Constraint Parameters:
        Read Host Paths:
          /proc
          /var/run/containerd
    Image:  ^gcr\.io/datadoghq/agent*
Events:     <none>
```

Looking at the `init-config` from the `--dry-run`:
(`helm install datadog-agent datadog/datadog -f datadog-agent-values.yaml --version 3.19.1 --dry-run --debug`)
```
        - name: init-config
          image: "gcr.io/datadoghq/agent:7.43.1"
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
          args:
            - |
              for script in $(find /etc/cont-init.d/ -type f -name '*.sh' | sort); do
                bash $script
              done
...
          volumeMounts:
...
            - name: procdir
              mountPath: /host/proc
              mountPropagation: None
              readOnly: true
            - name: runtimesocketdir
              mountPath: /host/var/run/containerd
              mountPropagation: None
              readOnly: true
          env:
...
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "datadog-agent-token"
                  key: api-key
...
            - name: DD_PROVIDER_KIND
              value: gke-autopilot
```

So the GKE exemption has `$script ; done` but the chart has `$script done`. But I have no idea of that makes a difference or not.

**Additional environment details (Operating System, Cloud provider, etc):**

Cluster:
Release channel `Regular channel`
Version `1.24.9-gke.3200`

Based on the closed GitHub issues, I was hoping that it would just work:
https://github.com/DataDog/helm-charts/issues/549
https://github.com/DataDog/helm-charts/issues/894
https://github.com/DataDog/helm-charts/issues/853
