### ISSUE TITLE
extra empty line in helmchecks

### ISSUE THREAD

**Issue by pc-brizkowsky** [DataDog/helm-charts#953]
Related the feature added in this PR https://github.com/DataDog/helm-charts/pull/752

**Describe what happened:**
After adding these values in the values.yaml file 
``` yaml 
  helmCheck:
    enabled: true
    collectEvents: true
    valuesAsTags:
      config.env: env
      image.tag: version
```
The resulting yaml has a empty line that prevents the cluster-agent-confd configmap from being used correctly by the application.

``` yaml
apiVersion: v1
data:
  helm.yaml: |-
    init_config:
    instances:
      - collect_events: true
        helm_values_as_tags:

          config.env: env
          image.tag: version
```

**Describe what you expected:**
I expected this 

``` yaml
apiVersion: v1
data:
  helm.yaml: |-
    init_config:
    instances:
      - collect_events: true
        helm_values_as_tags:
          config.env: env
          image.tag: version
```

https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/_helm_check_config.yaml#L10

Steps to reproduce are listed in the description of the Issue. Using the helm chart as documented.

Currently the fix is easy and I have a PR incoming with that change.
