### ISSUE TITLE
Issue while installing datadog agent on windows 

### ISSUE THREAD

**Issue by sujith1594** [DataDog/helm-charts#955]
**Describe what happened:**
While trying to install datadog helm chart on windows eks cluster getting below error.

`Error: Error response from daemon: invalid volume specification: '\\.\pipe\docker_engine:\\.\pipe\docker_engine:ro': invalid mount config for type "npipe": field ReadOnly must not be specified`

When I remove `readOnly: true `  from the daemonset it is working fine.

**Describe what you expected:**

Datadog agents must be running successfully on windows nodes

**Steps to reproduce the issue:**

Below is the values file I used

```yaml
datadog:
  apiKey: <api_key>
  appKey: <app_key>
  clusterName: <cluster_name>
  kubeStateMetricsEnabled: false
  dogstatsd:
    useHostPort: true
  logs:
    enabled: true
  apm:
    portEnabled: true
clusterAgent: 
  image:
    doNotCheckTag: true
agents:
  image:
    doNotCheckTag: true       
  priorityClassName: system-node-critical
  tolerations:
  - effect: NoSchedule
    key: os
    operator: Equal
    value: windows
targetSystem: windows
existingClusterAgent:
  join: true
  serviceName: datadog-cluster-agent
  tokenSecretName: datadog-cluster-agent
datadog-crds:
  crds:
    datadogMetrics: false
```

**Additional environment details (Operating System, Cloud provider, etc):**

Cloud Provider : AWS
Distribution: EKS
Version: 1.23
