### ISSUE TITLE
Enable Vector export using Datadog Helm chart

### ISSUE THREAD

**Issue by snahelou** [DataDog/helm-charts#956]
Hello

Regarding [this documentation](https://docs.datadoghq.com/fr/getting_started/observability_pipelines/?tab=awseks#connect-the-agent-and-the-worker) to enable observability pipelines, I would like to enable the vector exporter in Datadog agent. After spending some times reading your Helm chart, I didn't find a way to provide this configuration (neither env vars, nor custom config). 

Do you know how to provide this kind of configuration ? 
Is there any way to inject (using configmap?) a piece of configuration in the dd agent? 

Thanks a lot,

**Comment by snahelou** [comment]
I finally found a solution using customAgentConfig
```
    agents:
      useConfigMap: true
      customAgentConfig:
        vector:
          logs:
            enabled: true
            url: "http://datadog-vector-observability-pipelines-worker:8282"
```
