### ISSUE TITLE
Creating files in subdirectories in conf.d?

### ISSUE THREAD

**Issue by g-linville** [DataDog/helm-charts#968]
The instructions for using the `datadog.conf\.d` value indicate that all the keys specified will become files inside of that directory.

I am trying to configure the [Istio integration](https://docs.datadoghq.com/integrations/istio/#configuration), so I need to create a file at `conf.d/istio.d/conf.yaml`. I tried creating a key called `istio.d/conf.yaml` but the slash is not allowed in the ConfigMap so Kubernetes rejects it. This is basically what I tried:

```yaml
datadog:
  conf.d:
    istio.d/conf.yaml: |-
      <configuration stuff here>
```

How can I create this file inside of `conf.d/istio.d`?
