### ISSUE TITLE
kubeStateMetricsCore does not report anything

### ISSUE THREAD

**Issue by PSanetra** [DataDog/helm-charts#973]
**Describe what happened:**
We enabled `datadog.kubeStateMetricsCore.enabled` and disabled `datadog.kubeStateMetricsEnabled`. After this change no `kubernetes_state.*` metrics were reported anymore. I saw that `kubernetes_state_core.yaml.default` was indeed mounted in `/conf.d`.

**Describe what you expected:**
I expected `datadog.kubeStateMetricsCore.enabled` would report `kubernetes_state.*` metrics from Kubernetes to Datadog.

**Steps to reproduce the issue:**
See above

**Additional environment details (Operating System, Cloud provider, etc):**
OS: Linux
Cloud provider: AKS
Helm Chart Version: 3.23.0
Agent Version: 7.43.1

**Comment by CharlyF** [comment]
Hi @PSanetra - Thanks for opening this issue.
Could you share the render of the chart? One thing I am interested in is seeing that KSM Core is running in the Cluster Agent (and maybe as a Cluster Level Check in Cluster Check Workers).

**Comment by CharlyF** [comment]
Thank you this is very helpful.
So it seems indeed that the check is mounted in the Cluster Agent and it should work. (it also seems like you are using the Cluster Check Runners, more on that later). 
With the current setup, could you use `agent status` in the Datadog Cluster Agent (in the leader, the agent status command in a Cluster Agent pod will output the pod_name of the leader at the bottom if it's a follower).
I would expect to see something like this:

```
    kubernetes_state_core
    ---------------------
      Instance ID: kubernetes_state_core:9ecd386c7c831a27 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_state_core.d/kubernetes_state_core.yaml.default
      Total Runs: 5,393
      Metric Samples: Last Run: 1,356, Total: 7,298,705
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 12, Total: 64,656
      Average Execution Time : 19ms
      Last Execution Date : 2023-03-30 12:57:59 UTC (1680181079000)
      Last Successful Execution Date : 2023-03-30 12:57:59 UTC (1680181079000)
```

The logs of the pod could also be helpful. 
I want to solve this first, but eventually, I would also recommend using:
`datadog.kubeStateMetricsCore.useClusterCheckRunners`, since this is the best practice to distribute the check onto the cluster check runners.

**Comment by PSanetra** [comment]
@CharlyF I have now enabled the legacy kube state metrics again, but when I still had kubeStateMetricsCore enabled, I already checked that command and that `kubernetes_state_core` check was missing in the output. The file in `/etc/datadog-agent/conf.d/kubernetes_state_core.d/kubernetes_state_core.yaml.default` was missing, too, but was present in `/conf.d/kubernetes_state_core.yaml.default`. Does this make sense?

I can check it again when I have time.

**Comment by CharlyF** [comment]
Understood - I am not able to reproduce unfortunately so we'd be happy to dig more into it.

In the meantime, we released the [Datadog Operator 1.0](https://docs.datadoghq.com/getting_started/containers/datadog_operator/#pagetitle), if you want to give this a try, I believe the `DatadogAgent` you would need to get the same featureset and config is:
```yaml
kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
  namespace: datadog
spec:
  features:
    orchestratorExplorer:
      enabled: true
      scrubContainers: true
    clusterChecks:
      enabled: true
      useClusterChecksRunners: true
    externalMetricsServer:
      enabled: true
      useDatadogMetrics: false
    admissionController:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    kubeStateMetricsCore:
      enabled: true
  global:
    credentials:
      apiKey: <DATADOG_API_KEY>
      appKey: <DATADOG_APP_KEY>
  override:
    nodeAgent:
      image:
        jmxEnabled: true
```
