### ISSUE TITLE
APM Socket Path Is Not Mounted if DSD Socket is Not Enabled

### ISSUE THREAD

**Issue by oliverisaac** [DataDog/helm-charts#975]
https://github.com/DataDog/helm-charts/blob/e33ce0c14aa4188d8f0ef66acb5d5e935cf4b115/charts/datadog/templates/_container-trace-agent.yaml#L89-L93

If your values.yaml config is:

```
datadog:
  apm:
    enabled: true
    socketEnabled: true
    socketPath: /var/run/datadog/apm.socket
  dogstatsd:
    socketPath: /var/run/datadog/dsd.socket
    useSocketVolume: false
```

Where datadog.dogstatsd.useSocketVolume is false, then the APM socket is not mounted into the daemonset. Causes error messages like the below:

```
[dd-trace-processor] WARN datadog.trace.agent.common.writer.ddagent.DDAgentApi - Error while sending 1 (size=684B) traces. Total: 1, Received: 1, Sent: 0, Failed: 1. java.io.IOException: No such file or directory (Will not log errors for 5 minutes)
``` 

The check for mounting the /var/run/datdog volume should probably include a check if the .datadog.dogstatsd.useSocketVolume is true or false.

**Comment by CharlyF** [comment]
Hi @oliverisaac - Thanks for opening this up.
Indeed this is not ideal, as a temporary solution would it be acceptable to set:
`.datadog.apm.socketPath` at a different directory path to circumvent this mounting issue?
Something like:
```
datadog:
  apm:
    enabled: true
    socketEnabled: true
    socketPath: /var/run/datadog/apm/apm.socket
  dogstatsd:
    socketPath: /var/run/datadog/dsd/dsd.socket
    useSocketVolume: false
```
?
