### ISSUE TITLE
Error converting YAML to JSON error on helm chart

### ISSUE THREAD

**Issue by joesteffee** [DataDog/helm-charts#976]
Error: YAML parse error on datadog/templates/agent-apiservice.yaml: error converting YAML to JSON: yaml: line 10: did not find expected key

This error was introduced with version 3.23.0 of the helm chart, still a problem with 3.24.0

Chart applies without error

Deploy datadog helm chart with terraform:
```
resource "helm_release" "datadog_agent" {
  name       = "datadog-agent"
  chart      = "datadog"
  repository = "https://helm.datadoghq.com"
  version    = "3.24.0"
  namespace  = local.datadog_namespace
  timeout    = 900
  set_sensitive {
    name  = "datadog.apiKey"
    value = "someAPIKey"
  }
  set_sensitive {
    name  = "datadog.appKey"
    value = "someAppKey"
  }
  set {
    name  = "datadog.logs.enabled"
    value = true
  }
  set {
    name  = "datadog.logs.containerCollectAll"
    value = true
  }
  set {
    name  = "datadog.containerExclude"
    value = "kube_namespace:data-dog"
  }
  set {
    name  = "datadog.podSecurityPolicy.create"
    value = true
  }
  set {
    name  = "datadog.logs.autoMultiLineDetection"
    value = true
  }
  set {
    name  = "datadog.leaderElection"
    value = true
  }
  set {
    name  = "datadog.collectEvents"
    value = true
  }
  set {
    name  = "datadog.kubeStateMetricsCore.enabled"
    value = true
  }
  set {
    name  = "clusterChecks.enabled"
    value = true
  }
  set {
    name  = "clusterAgent.enabled"
    value = true
  }
  set {
    name  = "clusterAgent.podSecurityPolicy.create"
    value = true
  }
  set {
    name  = "clusterAgent.admissionController.enabled"
    value = true
  }
  set {
    name  = "clusterAgent.metricsProvider.enabled"
    value = true
  }
  set {
    name  = "networkMonitoring.enabled"
    value = true
  }
  set {
    name  = "systemProbe.enableTCPQueueLength"
    value = true
  }
  set {
    name  = "systemProbe.enableOOMKill"
    value = true
  }
  set {
    name  = "securityAgent.runtime.enabled"
    value = true
  }
  set {
    name  = "datadog.hostVolumeMountPropagation"
    value = "HostToContainer"
  }
  set {
    name  = "datadog.apm.enabled"
    value = true
  }
  set {
    name  = "datadog.dogstatsd.useSocketVolume"
    value = false
  }
  set {
    name  = "datadog.dogstatsd.useHostPort"
    value = true
  }
  set {
    name  = "agents.containers.traceAgent.env[0].name"
    value = "DD_APM_IGNORE_RESOURCES"
  }
  set {
    name  = "agents.containers.traceAgent.env[0].value"
    value = "GET /.*/api/v[0-9]/health"
  }
  set {
    name  = "agents.containers.agent.resources.limits.cpu"
    value = "1"
  }
  set {
    name  = "agents.containers.agent.resources.limits.memory"
    value = "2Gi"
  }
  set {
    name  = "agents.containers.agent.env[0].name"
    value = "DD_EC2_PREFER_IMDSV2"
  }
  set {
    name  = "agents.containers.agent.env[0].value"
    value = "true"
  }
  set {
    name  = "agents.containers.agent.securityContext.allowPrivilegeEscalation"
    value = "false"
  }
  ## https://github.com/DataDog/datadog-agent/issues/15127
  set {
    name  = "commonLabels[0].key"
    value = "kubeaudit.io/allow-read-only-root-filesystem-false"
  }
  set {
    name  = "commonLabels[0].value"
    value = ""
  }
  set {
    name  = "commonLabels[1].key"
    value = "kubeaudit.io/allow-run-as-root"
  }
  set {
    name  = "commonLabels[1].value"
    value = ""
  }
  set {
    name  = "commonLabels[2].key"
    value = "kubeaudit.io/allow-host-path-mount-proc-volume"
  }
  set {
    name  = "commonLabels[2].value"
    value = "required-for-datadog"
  }
  set {
    name  = "commonLabels[3].key"
    value = "kubeaudit.io/allow-namespace-host-PID"
  }
  set {
    name  = "commonLabels[3].value"
    value = ""
  }
  set {
    name  = "agents.podSecurity.podSecurityPolicy.create"
    value = true
  }
  set {
    name  = "agents.containers.initContainers.resources.limits.cpu"
    value = "100m"
  }
  set {
    name  = "agents.containers.initContainers.resources.limits.memory"
    value = "200Mi"
  }
  set_sensitive {
    name = "clusterAgent.confd.postgres\\.yaml"
    value = templatefile(var.postgres_configuration_template, {
      rds_host_address     = var.rds_host_address,
      rds_host_port        = var.rds_host_port,
      rds_datadog_username = var.rds_datadog_username,
      rds_datadog_password = var.rds_datadog_password,
      db_names             = var.monitored_databases,
    })
  }

  depends_on = [
    kubernetes_namespace.datadog
  ]
}
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by CharlyF** [comment]
Hi @joesteffee,

I did some [digging](https://medium.com/@nitinnbisht/annotation-in-helm-with-terraform-3fa04eb30b6e) and I think the issue here is with the tf file/formatting.
I was able to get the extra annotations using:
```
  set {
    name  = "commonLabels.kubeaudit\\.io/allow-read-only-root-filesystem-false"
    value = ""
  }
  set {
    name =  "commonLabels.kubeaudit\\.io/allow-run-as-root"
    value = ""
  }
  set {
    name = "commonLabels.kubeaudit\\.io/allow-host-path-mount-proc-volume"
    value = "required-for-datadog"
  }
  set {
    name = "commonLabels.kubeaudit\\.io/allow-namespace-host-PID"
    value = ""
  }
```

resulting in:
```
            # Source: datadog/templates/install_info-configmap.yaml
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: datadog-agent-installinfo
              namespace: datadog_namespace
              labels:
                helm.sh/chart: 'datadog-3.23.0'
                app.kubernetes.io/name: "datadog-agent"
                app.kubernetes.io/instance: "datadog-agent"
                app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/version: "7"
                kubeaudit.io/allow-host-path-mount-proc-volume: required-for-datadog
                kubeaudit.io/allow-namespace-host-PID: ""
                kubeaudit.io/allow-read-only-root-filesystem-false: ""
                kubeaudit.io/allow-run-as-root: ""
```

Let me know if that helps.
