### ISSUE TITLE
VolumeMounts not found: "datadog"

### ISSUE THREAD

**Issue by cam3ron2** [DataDog/helm-charts#986]
**Describe what happened:**
Upgrading the datadog agents from chart 3.10.6 to higher versions results in no agents being created and the daemonset rollout never progresses. I do not know which version introduces this behavior, but have confirmed that I can replicate the issue when going from 3.10.6 to the following versions:
 - 3.21.x
 - 3.22.x
 - 3.23.x
 - 3.25.x

Related Events:
```shell
Error creating: Pod "datadog-96z27" is invalid: [spec.initContainers[0].volumeMounts[2].name: Not found: "datadog", spec.initContainers[1].volumeMounts[5].name: Not found: "datadog"]
```
**Describe what you expected:**

I expected the daemonset rollout to progress and complete

**Steps to reproduce the issue:**

Deploy chart 3.10.6
Upgrade to 3.25.1

**Additional environment details (Operating System, Cloud provider, etc):**
Chart: 3.25.1
Provider: AKS
K8s Version: 1.25.5

Helm Values: (in the form of yaml-formatted parameters)

```yaml
         parameters:
            - name: fullnameOverride
              value: datadog
            - name: clusterAgent.enabled
              value: "true"
            - name: clusterAgent.replicas
              value: "2"
            - name: clusterAgent.createPodDisruptionBudget
              value: "true"
            - name: clusterAgent.admissionController.enabled
              value: "true"
            - name: clusterAgent.admissionController.mutateUnlabelled
              value: "true"
            - name: clusterAgent.metricsProvider.enabled
              value: "true"
            - name: clusterAgent.metricsProvider.useDatadogMetrics
              value: "true"
            - name: clusterAgent.metricsProvider.createReaderRbac
              value: "true"
            - name: clusterAgent.env[0].name
              value: "DD_ADMISSION_CONTROLLER_ADD_AKS_SELECTORS"
            - name: clusterAgent.env[0].value
              value: "true"
            - name: agents.tolerations[0].effect
              value: "NoSchedule"
            - name: agents.tolerations[0].operator
              value: "Exists"
            - name: agents.containers.agent.env[0].name
              value: DD_LOGS_CONFIG_OPEN_FILES_LIMIT
            - name: agents.containers.agent.env[0].value
              value: "500"
            - name: priorityClassName
              value: "system-node-critical"
            - name: datadog.apiKeyExistingSecret
              value: "datadog-api-key"
            - name: datadog.appKeyExistingSecret
              value: "datadog-app-key"
            - name: datadog.kubeStateMetricsEnabled
              value: "true"
            - name: datadog.kubeStateMetricsCore.enabled	
              value: "false"             
            - name: datadog.apm.portEnabled
              value: "true"
            - name: datadog.clusterName
              value: "REDACTED"
            - name: datadog.criSocketPath
              value: "/var/run/containerd/containerd.sock"
            - name: datadog.dockerSockerPath
              value: "false"
            - name: datadog.kubelet.tlsVerify
              value: "false"
            - name: datadog.site
              value: "datadoghq.com"
            - name: datadog.prometheusScrape.enabled
              value: "false"
            - name: datadog.prometheusScrape.serviceEndpoints
              value: "false"
            - name: datadog.logs.enabled
              value: "true"
            - name: datadog.logs.containerCollectAll
              value: "true"
            - name: datadog.logs.containerCollectUsingFiles
              value: "true"
            - name: datadog.kubeStateMetricsCore.useClusterCheckRunners
              value: "true"
            - name: datadog.kubeStateMetricsCore.labelsAsTags
              value: "true"
            - name: datadog.clusterChecks.enabled
              value: "true"
            - name: datadog.dogstatsd.useHostPort
              value: "true"
            - name: datadog.processAgent.processCollection
              value: "true"
            - name: clusterChecksRunner.priorityClassName
              value: "system-cluster-critical"
            - name: agents.priorityClassName
              value: "system-cluster-critical"
            - name: datadog.securityAgent.runtime.network.enabled
              value: "false"
            - name: providers.aks.enabled
              value: "true"
            - name: datadog.namespaceLabelsAsTags.nielseniq\.com/market
              value: market
            - name: datadog.env[0].name
              value: DD_APM_FEATURES
            - name: datadog.env[0].value
              value: enable_cid_stats
```

Workaround: 
Manually adding the volumes to the helm chart for the datadog daemonset solves the issue. 

Example: 

```yaml
            - name: agents.volumes[0].name
              value: datadog
            - name: agents.volumes[0].emptyDir.sizeLimit
              value: "500Mi"
            - name: agents.volumeMounts[0].name
              value: datadog
            - name: agents.volumeMounts[0].mountPath
              value: /tmp/datadog
            - name: agents.volumeMounts[0].readOnly
              value: "true"
```
