### ISSUE TITLE
`useConfigMap: true` doesn't work with a custom image tag

### ISSUE THREAD

**Issue by scottopell** [DataDog/helm-charts#991]
**Describe what happened:**
`Error: UPGRADE FAILED: template: datadog/templates/datadog-yaml-configmap.yaml:40:10: executing "datadog/templates/datadog-yaml-configmap.yaml" at <semverCompare ">=6.15" $version>: error calling semverCompare: Invalid Semantic Version`

It appears that the `useConfigMap`/`customAgentConfig` codepath does not have a `doNotCheckTag` option, so the parsing to determine agent version fails if the tag does not match the standard format.

**Describe what you expected:**
The helm chart to apply correctly. 

**Steps to reproduce the issue:**
`values.yaml`:
```yaml
agents:
  useConfigMap: true # works if this is false
  image:
    doNotCheckTag: true
    repository: docker.io/datadog/agent-dev
    tag: nightly-fix-743-upgrade-jmxfetch-py3-jmx
```

**Additional environment details (Operating System, Cloud provider, etc):**
Testing in an ubuntu aarch64 VM running microk8s
